# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: e91c51bdb136

import pytest

from archastro.phx_channel import HarnessServiceClient
from archastro.platform import AsyncPlatformClient
from archastro.platform.runtime.http_client import ApiError

# Mark every coroutine in this file as async so the tests run whether or
# not the consuming project sets asyncio_mode=auto.
pytestmark = pytest.mark.asyncio


async def test_agent_sessions_stream_yields_sse_events(harness_service):
    harness = HarnessServiceClient(
        ws_url=harness_service["wsUrl"], control_url=harness_service["controlUrl"]
    )
    await harness.reset()
    await harness.register_stream_scenario(
        {
            "route": "GET /api/v1/agent_sessions/{agent_session}/stream",
            "actions": [{"type": "autoEmit", "event": "session_update"}],
        }
    )
    client = AsyncPlatformClient(
        base_url=harness_service["controlUrl"],
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )
    try:
        events = []
        async for ev in client.v1.agent_sessions.stream("test-value"):
            events.append(ev)
        assert [e["event"] for e in events] == ["session_update"]
    finally:
        await client.close()
        await harness.close()


async def test_agent_sessions_stream_rejects_non_2xx(harness_service):
    harness = HarnessServiceClient(
        ws_url=harness_service["wsUrl"], control_url=harness_service["controlUrl"]
    )
    await harness.reset()
    await harness.register_stream_scenario(
        {
            "route": "GET /api/v1/agent_sessions/{agent_session}/stream",
            "actions": [
                {"type": "status", "code": 402, "body": {"error": {"code": "plan_not_entitled"}}}
            ],
        }
    )
    client = AsyncPlatformClient(
        base_url=harness_service["controlUrl"],
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )
    try:
        with pytest.raises(ApiError):
            async for _ in client.v1.agent_sessions.stream("test-value"):
                pass
    finally:
        await client.close()
        await harness.close()
