# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 04f6f272f827

import pytest

from archastro.phx_channel import HarnessServiceClient
from archastro.platform import AsyncPlatformClient
from archastro.platform.runtime.http_client import ApiError

# Mark every coroutine in this file as async so the tests run whether or
# not the consuming project sets asyncio_mode=auto.
pytestmark = pytest.mark.asyncio


async def test_ai_chat_completions_stream_yields_sse_events(harness_service):
    harness = HarnessServiceClient(
        ws_url=harness_service["wsUrl"], control_url=harness_service["controlUrl"]
    )
    await harness.reset()
    await harness.register_stream_scenario(
        {
            "route": "POST /api/v1/ai/chat/completions/stream",
            "actions": [
                {"type": "autoEmit", "event": "done"},
                {"type": "autoEmit", "event": "error"},
                {"type": "autoEmit", "event": "message_complete"},
                {"type": "autoEmit", "event": "message_delta"},
                {"type": "autoEmit", "event": "tool_call_delta"},
                {"type": "autoEmit", "event": "tool_result"},
            ],
        }
    )
    client = AsyncPlatformClient(
        base_url=harness_service["controlUrl"],
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )
    try:
        events = []
        async for ev in client.v1.ai.chat.completions.stream(
            {"messages": [{"role": "user"}], "opts": {"model": "test-model"}}
        ):
            events.append(ev)
        assert [e["event"] for e in events] == [
            "done",
            "error",
            "message_complete",
            "message_delta",
            "tool_call_delta",
            "tool_result",
        ]
    finally:
        await client.close()
        await harness.close()


async def test_ai_chat_completions_stream_rejects_non_2xx(harness_service):
    harness = HarnessServiceClient(
        ws_url=harness_service["wsUrl"], control_url=harness_service["controlUrl"]
    )
    await harness.reset()
    await harness.register_stream_scenario(
        {
            "route": "POST /api/v1/ai/chat/completions/stream",
            "actions": [
                {"type": "status", "code": 402, "body": {"error": {"code": "plan_not_entitled"}}}
            ],
        }
    )
    client = AsyncPlatformClient(
        base_url=harness_service["controlUrl"],
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )
    try:
        with pytest.raises(ApiError):
            async for _ in client.v1.ai.chat.completions.stream(
                {"messages": [{"role": "user"}], "opts": {"model": "test-model"}}
            ):
                pass
    finally:
        await client.close()
        await harness.close()
