# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: e73922c92163

from datetime import datetime

from pydantic import BaseModel, Field

from .image import ImageSource


class Artifact(BaseModel):
    """
    A versioned artifact produced or managed by an agent, such as a generated file, report, or code output.
    """

    agent: str | None = Field(
        default=None,
        description="ID of the agent that produced this artifact (`agt_...`). `null` if not agent-produced.",
    )
    content_type: str | None = Field(
        default=None,
        description='MIME type of the current version\'s file, e.g. `"text/csv"` or `"image/png"`. `null` if no file is attached.',
    )
    created_at: datetime | None = Field(
        default=None, description="When the artifact was first created (ISO 8601)."
    )
    current_version: str | None = Field(
        default=None,
        description="ID of the current (latest published) artifact version (`artv_...`). `null` if no version has been published.",
    )
    description: str | None = Field(
        default=None,
        description="Optional longer description of the artifact's contents or purpose. `null` if not set.",
    )
    file: str | None = Field(
        default=None,
        description="Storage file ID for the current version (`fil_...`). `null` if no file is attached.",
    )
    file_name: str | None = Field(
        default=None,
        description='Original filename of the current version\'s file, e.g. `"output.csv"`. `null` if no file is attached.',
    )
    file_url: str | None = Field(
        default=None,
        description="Short-lived signed URL for downloading the current version's file. `null` if no file is attached.",
    )
    id: str = Field(..., description="Artifact ID (`art_...`).")
    image_source: ImageSource | None = Field(
        default=None,
        description='Image source metadata for rendering the current version\'s file inline. Present only when `content_type` starts with `"image/"`. `null` otherwise.',
    )
    name: str | None = Field(
        default=None,
        description='Human-readable name for the artifact, e.g. `"Q2 Report"`. `null` if not set.',
    )
    org: str | None = Field(
        default=None, description="ID of the organization this artifact belongs to (`org_...`)."
    )
    sandbox: str | None = Field(
        default=None,
        description="Identifier of the sandbox environment associated with this artifact. `null` if not sandbox-scoped.",
    )
    team: str | None = Field(
        default=None,
        description="ID of the team that owns this artifact (`tea_...`). `null` if not team-scoped.",
    )
    thread: str | None = Field(
        default=None,
        description="ID of the thread in which this artifact was created (`thr_...`). `null` if not thread-scoped.",
    )
    updated_at: datetime | None = Field(
        default=None, description="When the artifact record was last modified (ISO 8601)."
    )
    user: str | None = Field(
        default=None,
        description="ID of the user who created this artifact (`usr_...`). `null` if not user-scoped.",
    )
    version: int | None = Field(
        default=None,
        description="Current version number of the artifact. Increments each time a new version is published.",
    )
