# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 1a52d465f51e


from pydantic import BaseModel

from .image import ImageSource
from .users import User


# Schema for the current developer account.
class Account(BaseModel):
    alias: str | None = None  # Developer alias
    created_at: str  # Account creation date
    email: str  # Email address
    email_verified: bool  # Whether email is verified
    full_name: str | None = None  # Full name
    id: str  # Account ID
    system_role: str  # System role
    timezone: str | None = None  # IANA timezone


# API schema for a single ACL grant entry.
class AclGrant(BaseModel):
    actions: list[str]  # List of allowed actions (e.g. read, write)
    principal: str | None = None
    principal_type: str  # Principal type: user, team, org, org_role, agent, or everyone


# API schema for identifying a principal to remove from an ACL.
class AclRemoveTarget(BaseModel):
    principal: str | None = None  # Principal identifier to remove (omit for everyone)
    principal_type: str  # Principal type to remove


# Reusable API schema for access control lists.
# Supports two modes (mutually exclusive):
# **Replace mode**   send `grants` to replace all entries:
# {"grants": [{"principal_type": "user", "principal": "...", "actions": ["read"]}]}
# Use `{"grants": []}` to clear all entries.
# **Patch mode**   send `add` and/or `remove`:
# {"add": [...grants...], "remove": [{"principal_type": "user", "principal": "..."}]}
# Cannot mix `grants` with `add`/`remove`.
class Acl(BaseModel):
    add: list[AclGrant] | None = None  # Patch mode: grants to add or merge into existing
    grants: list[AclGrant] | None = None
    remove: list[AclRemoveTarget] | None = None  # Patch mode: principals to remove from existing


# API schema for an activity feed entry.
class ActivityFeedEntry(BaseModel):
    agent: str | dict[str, object] | None = None
    app: str | None = None  # Application
    attachments: list[dict[str, object]] | None = None  # Entry attachments
    automation_run: str | None = None  # Automation run
    content: str | None = None  # Longer explanation (markdown)
    correlation_id: str | None = None  # Correlation ID for grouped entries
    created_at: str | None = None  # Creation timestamp
    id: str  # Entry ID (afe_...)
    kind: str | None = None  # Entry kind
    level: str | None = None  # Severity level
    metadata: dict[str, object] | None = None  # Entry metadata
    org: str | None = None  # Organization
    routine_run: str | None = None  # Routine run
    sandbox: str | None = None  # Sandbox identifier
    session_record: str | None = None  # Agent session
    team: str | None = None  # Team
    thread: str | None = None  # Thread
    title: str | None = None  # One-line summary
    updated_at: str | None = None  # Last update timestamp
    user: str | dict[str, object] | None = None


# Schema for a message actor (user or agent).
# Actors represent the entity that sent a message.
# Maps to the actor format from MessageActorHelper.build_actor/1.
class Actor(BaseModel):
    alias: str | None = None  # Actor alias/handle
    id: str | None = None  # Actor ID (format: user-xxx or agent-xxx)
    name: str | None = None  # Actor display name
    profile_picture: ImageSource | None = None  # Profile picture


class ResolvedTool(BaseModel):
    description: str | None = None  # What this tool does
    name: str  # Callable tool function name
    parameters: dict[str, object] | None = None  # JSON Schema describing the expected input


# API schema for background worker status on a routine run.
class WorkerStatus(BaseModel):
    attempt: int  # Current attempt number (0 = not yet attempted)
    max_attempts: int  # Maximum allowed attempts
    status: str  # Worker state: queued, executing, retrying, completed, discarded, or cancelled


# Schema for an API call record.
# Maps to serialized API call output from developer portal API.
class ApiCall(BaseModel):
    api_key_type: str | None = None  # API key type (publishable or secret)
    created_at: str | None = None  # Created timestamp
    error_message: str | None = None  # Error message if request failed
    event_type: str | None = None  # Webhook event type (e.g. push, pull_request)
    full_url: str  # Full request URL with query string
    handler_module: str | None = None  # ApiDsl action module
    id: str  # Public ID (aac_...)
    ip_address: str | None = None  # Client IP address
    latency_ms: int  # Latency in milliseconds
    metadata: dict[str, object] | None = None
    method: str  # HTTP method
    org: str | None = None  # Org if org-scoped
    path: str  # Sanitized path with param placeholders
    query_string: str | None = None  # Query string
    request_body: dict[str, object] | None = None  # Request body payload (webhooks only)
    request_headers: dict[str, object] | None = None  # Request headers (webhooks only)
    request_id: str | None = None  # Request ID from Plug.RequestId
    status_code: int  # HTTP status code
    team: str | None = None  # Team if team-scoped
    thread: str | None = None  # Thread if thread-scoped
    user: str | None = None  # User if user-scoped


# Schema for a documented API endpoint in the developer API explorer.
class ApiExplorerEndpoint(BaseModel):
    deprecated: bool  # Whether the route is deprecated
    description: str | None = None  # Endpoint description
    errors: list[dict[str, object]]  # Documented error responses
    method: str  # HTTP method
    params: list[dict[str, object]]  # Documented params
    path: str  # Route path
    returns: dict[str, object] | None = None  # Return schema description
    scope: str  # Endpoint scope
    tags: list[str]  # Route tags


# Schema for the API explorer response.
class ApiExplorerIndex(BaseModel):
    data: list[ApiExplorerEndpoint]  # Documented API endpoints
    schemas: dict[str, object] | None = None  # Collected schema definitions


# Schema for a sandbox API key.
class SandboxKey(BaseModel):
    created_at: str | None = None  # Created timestamp
    expires_at: str | None = None  # Expiry timestamp
    full_key: str | None = None  # Full key shown only once at creation
    id: str  # Public ID (dsk_...)
    key_hint: str | None = None  # Last 4 chars hint
    key_value: str | None = None  # Full key (publishable only)
    last_used_at: str | None = None  # Last used timestamp
    status: str  # Status (active, revoked)
    type: str  # Key type (publishable, secret)


# Schema for a developer sandbox.
class Sandbox(BaseModel):
    created_at: str | None = None  # Created timestamp
    id: str  # Public ID (dsb_...)
    keys: list[SandboxKey] | None = None  # Sandbox API keys
    name: str  # Sandbox name
    slug: str  # Sandbox slug (unique per app)
    updated_at: str | None = None  # Updated timestamp


# Schema for a developer app.
# Maps to serialized app output from developer portal API.
class App(BaseModel):
    app_slug: str | None = None  # Workspace slug (if set)
    app_url: str | None = None  # App URL
    brand_name: str | None = None  # Brand name for emails
    created_at: str | None = None  # Created timestamp
    description: str | None = None  # App description
    from_name: str | None = None  # From name for emails
    id: str  # Public ID (dap_...)
    marketing_url: str | None = None  # Marketing URL
    muted_color: str | None = None  # Muted hex color
    name: str  # App name
    primary_color: str | None = None  # Primary hex color
    sandboxes: list[Sandbox] | None = None  # App sandboxes with keys
    status: str  # Status (active, suspended)
    support_email: str | None = None  # Support email address
    third_party_oauth_enabled: bool | None = None  # Third-party OAuth enabled
    updated_at: str | None = None  # Updated timestamp


# Schema for an app environment variable response with a masked value.
class AppEnvVarMasked(BaseModel):
    created_at: str | None = None  # Created timestamp
    description: str | None = None  # Optional description
    id: str  # Environment variable ID
    key: str  # Environment variable key
    masked_value: str  # Masked environment variable value
    updated_at: str | None = None  # Updated timestamp


# Schema for masked app environment variable list responses.
class AppEnvVarMaskedList(BaseModel):
    data: list[AppEnvVarMasked]  # Environment variables


# Schema for an app environment variable response that includes the plaintext value.
class AppEnvVarPlaintext(BaseModel):
    created_at: str | None = None  # Created timestamp
    description: str | None = None  # Optional description
    id: str  # Environment variable ID
    key: str  # Environment variable key
    updated_at: str | None = None  # Updated timestamp
    value: str  # Plaintext environment variable value


# Schema for an API key.
# Maps to serialized app key output from developer portal API.
class AppKey(BaseModel):
    created_at: str | None = None  # Created timestamp
    full_key: str | None = None  # Full key shown only once at creation
    id: str  # Public ID (dak_...)
    key_hint: str | None = None  # Last 4 chars hint
    key_value: str | None = None  # Full key (publishable only)
    last_used_at: str | None = None  # Last used timestamp
    status: str  # Status (active, revoked)
    type: str  # Key type (publishable, secret)


# Schema for an app slug mapping.
class AppSlug(BaseModel):
    app: str  # App identifier
    created_at: str | None = None  # Created timestamp
    creator: str | None = None  # Creator identifier
    id: str  # Slug record ID
    slug: str  # Globally unique slug
    updated_at: str | None = None  # Updated timestamp


# API schema for a media variant.
class MediaVariant(BaseModel):
    content_type: str | None = None  # File content type
    created_at: str | None = None  # Creation timestamp
    file: str | None = None  # Storage file
    filename: str | None = None  # Original filename
    height: int | None = None  # Height in pixels
    id: str  # Variant ID
    image_source: ImageSource | None = None  # Image source metadata
    updated_at: str | None = None  # Last update timestamp
    url: str | None = None  # Signed download URL
    variant_key: str | None = None  # Variant key (original, thumbnail, etc)
    width: int | None = None  # Width in pixels


# Schema for a message attachment.
# Attachments can be of various types (file, scraped_link, artifact, task, media, action).
# Fields present depend on the attachment type.
# Maps to format_attachments_for_client/1 output.
class Attachment(BaseModel):
    content_type: str | None = None  # MIME content type (file, artifact, media types)
    description: str | None = None  # Description (scraped_link, artifact, task types)
    filename: str | None = None  # File name (file, artifact, media types)
    height: int | None = None  # Media height (media type)
    id: str  # Attachment ID
    image_height: int | None = None  # Preview image height (scraped_link type)
    image_source: ImageSource | None = None
    image_url: str | None = None  # Preview image URL (scraped_link type)
    image_width: int | None = None  # Preview image width (scraped_link type)
    media_type: str | None = None  # Media type (media type)
    name: str | None = None  # Media name (media type)
    object: dict[str, object] | None = None  # Embedded object (task, action types)
    title: str | None = None  # Title (scraped_link, artifact, task types)
    type: str  # Attachment type: file, scraped_link, artifact, task, media, action
    url: str | None = None  # URL to the resource (file, scraped_link, artifact, media types)
    variants: list[MediaVariant] | None = None  # Media variants (media type)
    version: int | None = None  # Artifact version number (artifact type)
    width: int | None = None  # Media width (media type)


# API schema for authentication token responses.
class AuthTokens(BaseModel):
    expires_in: int  # Token TTL in seconds
    metadata: dict[str, object] | None = None  # Additional metadata (e.g., onboarding_job_id)
    refresh_token: str  # Refresh token
    token: str  # Access token (JWT)
    token_type: str  # Token type (Bearer)
    user: User  # Authenticated user


# Schema for a billing plan.
class BillingPlan(BaseModel):
    description: str | None = None  # Plan description
    id: str | None = None  # Plan identifier (e.g. paygo)
    name: str | None = None  # Human-readable plan name
    target: str | None = None  # Entity type this plan applies to (developer or org)


# Schema for app billing settings.
class BillingSettingsApp(BaseModel):
    billing_account: str | None = None  # Developer account that owns billing (public ID)
    org_billing_enabled: bool | None = None  # Whether orgs get their own Stripe customers


# Schema for org billing settings.
class BillingSettingsOrg(BaseModel):
    auto_reup_amount_cents: int | None = None
    auto_reup_enabled: bool | None = None  # Whether automatic credit reup is enabled
    auto_reup_threshold_cents: int | None = None
    billing_provider_environment: str | None = None  # Stripe environment (live or test)
    billing_provider_id: str | None = None  # Stripe customer ID
    pending_plan: str | None = None
    plan: str | None = None  # Active billing plan (e.g. enterprise-pilot)
    primary_user: str | None = None  # Org admin user who is the billing contact (public ID)


# An individual tool within a builtin tool catalog entry.
class BuiltinTool(BaseModel):
    description: str | None = None  # Tool description
    name: str  # Tool name


# A builtin tool catalog entry describing an available tool category.
class BuiltinToolCatalogEntry(BaseModel):
    config_schema: dict[str, object] | None = None  # JSON schema for tool configuration
    description: str | None = None  # Tool description
    instruction: str | None = None  # Tool instruction
    key: str  # Unique tool key
    label: str | None = None  # Display label
    providers: list[str] | None = None  # Supported providers
    requires_integration: bool | None = None  # Whether an integration is required
    server_tool_type: str | None = None  # Server tool type identifier
    tools: list[BuiltinTool] | None = None  # List of individual tools


# Schema for Stripe Checkout Session creation result.
class CheckoutSessionResult(BaseModel):
    checkout_url: str  # Stripe Checkout URL to redirect the user to


# Schema for comment creation parameters.
# Used by both Users.Tasks.CreateComment and Teams.Tasks.CreateComment actions.
class CommentCreateParams(BaseModel):
    body: str  # Comment body text


# Result of executing a command on an agent computer.
class ComputerExecResult(BaseModel):
    exit_code: int | None = None  # Process exit code
    output: str | None = None  # Command output


# Schema for a user credential.
# Maps to serialized credential output from developer portal API.
class ContextCredential(BaseModel):
    alt_domains: list[str] | None = None  # Alternative domains
    created_at: str | None = None  # Created timestamp
    description: str | None = None  # Human-readable description
    domain: str  # Domain (e.g., app.schoology.com)
    id: str  # Public ID (ucr_...)
    last_accessed_at: str | None = None  # Last accessed timestamp
    updated_at: str | None = None  # Updated timestamp
    user: str | None = None  # Owning user


# API schema for a context entry.
class ContextEntry(BaseModel):
    after_cursor: str | None = None  # Pagination cursor (after)
    agent_user: str | None = None  # Agent user
    before_cursor: str | None = None  # Pagination cursor (before)
    created_at: str | None = None  # Creation timestamp
    files: list[dict[str, object]] | None = None  # Loaded file objects
    id: str  # Context entry ID
    links: list[dict[str, object]] | None = None  # Loaded link objects
    media: list[dict[str, object]] | None = None  # Loaded media objects
    metadata: dict[str, object] | None = None  # Entry metadata
    org: str | None = None  # Organization
    sandbox: str | None = None  # Sandbox identifier
    team: str | None = None  # Team
    text: str | None = None  # Entry text
    updated_at: str | None = None  # Last update timestamp
    user: str | None = None  # User


# Schema for a context ingestion.
# Maps to serialized context ingestion output from developer portal API.
class ContextIngestion(BaseModel):
    agent: str | None = None  # Agent
    completed_at: str | None = None  # Completed timestamp
    created_at: str | None = None  # Created timestamp
    error: dict[str, object] | None = None  # Error details (if failed)
    id: str  # Public ID (cig_...)
    metadata: dict[str, object] | None = None  # Additional metadata
    source: str | None = None  # Source ID
    started_at: str | None = None  # Started timestamp
    status: str  # Status (pending, running, awaiting_callback, succeeded, failed)
    team: str | None = None  # Owning team ID
    updated_at: str | None = None  # Updated timestamp
    user: str | None = None  # Owning user ID


# Schema for a context integration.
# Maps to serialized integration output from developer portal API.
class ContextIntegration(BaseModel):
    agent: str | None = None  # Owning agent
    auth_type: str  # Auth type: oauth or app_installation
    connected_at: str | None = None  # Connection timestamp
    created_at: str | None = None  # Created timestamp
    expires_at: str | None = None  # Token expiration timestamp
    id: str  # Public ID (int_...)
    installation: str | None = None  # External installation (e.g. GitHub App installation)
    last_refreshed_at: str | None = None  # Last token refresh timestamp
    metadata: dict[str, object] | None = None  # Additional metadata
    org: str | None = None  # Owning org
    provider: str  # Provider name (e.g., google, github)
    scopes: list[str] | None = None  # OAuth scopes
    status: str  # Connection status: connected, disconnected, or token_expired
    team: str | None = None  # Owning team
    updated_at: str | None = None  # Updated timestamp
    user: str | None = None  # Owning user
    workspace_key: str | None = None  # Workspace key


# Schema for a context item.
# Maps to serialized context item output from developer portal API.
class ContextItem(BaseModel):
    agent: str | None = None  # Agent
    content_type: str | None = None  # Content type
    created_at: str | None = None  # Created timestamp
    id: str  # Public ID (cim_...)
    item_group: str | None = None  # Item group if part of a group
    metadata: dict[str, object] | None = None  # Additional metadata
    normalized_content: str | None = None  # Normalized content text
    raw_content: dict[str, object] | None = None  # Raw content data
    source: str | None = None  # Source
    team: str | None = None  # Owning team
    updated_at: str | None = None  # Updated timestamp
    user: str | None = None  # Owning user


# Schema for a context source.
# Maps to serialized context source output from developer portal API.
class ContextSource(BaseModel):
    agent: str | None = None  # Owning agent
    context_installation: str | None = None  # Associated installation
    created_at: str | None = None  # Created timestamp
    id: str  # Public ID (cso_...)
    metadata: dict[str, object] | None = None  # Additional metadata
    org: str | None = None  # Owning organization
    parent_source: str | None = None  # Parent source
    payload: dict[str, object] | None = None  # Type-specific configuration
    sandbox: str | None = None  # Owning sandbox
    state: str  # State: active or paused
    team: str | None = None  # Owning team
    thread: str | None = None  # Associated thread
    type: str  # Source type (e.g., gmail, github_activity)
    updated_at: str | None = None  # Updated timestamp
    user: str | None = None  # Owning user


# API schema for a user credential.
class Credential(BaseModel):
    alt_domains: dict[str, object] | None = None  # Alternative domains
    created_at: str | None = None  # Creation timestamp
    description: str | None = None  # Description
    domain: str | None = None  # Primary domain
    id: str  # Credential ID (ucr_...)
    last_accessed_at: str | None = None  # Last accessed timestamp
    org: str | None = None  # Organization
    sandbox: str | None = None  # Sandbox
    secret_group: str | None = None  # Secret group ID
    updated_at: str | None = None  # Last update timestamp


# API schema for a credential with decrypted secret values.
class CredentialWithSecrets(BaseModel):
    credential: dict[str, object]  # The credential with decrypted values


# Schema for credit balance response.
class CreditBalance(BaseModel):
    available_cents: int  # Available credit balance in cents
    currency: str  # Currency code (e.g. usd)
    has_payment_method: bool  # Whether a saved payment method exists


# API schema for a custom object.
class CustomObject(BaseModel):
    created_at: str | None = None  # Created timestamp
    fields: dict[str, object] | None = None  # Object field values
    id: str  # Public ID (cobj_...)
    org: str | None = None  # Organization
    row_key: str | None = None  # Row key
    sandbox: str | None = None  # Sandbox identifier
    schema_type: str | None = None  # Schema type (lookup_key)
    team: str | None = None  # Owning team
    updated_at: str | None = None  # Updated timestamp
    user: str | None = None  # Owning user
    version: int | None = None  # Aggregate version for OCC


# Schema for a dataset dimension field.
class DatasetDimension(BaseModel):
    label: str  # Human-readable label
    name: str  # Dimension identifier
    type: str  # Data type (string, integer, boolean, datetime, date)


# Schema for a dataset metric field.
class DatasetMetric(BaseModel):
    aggregation: str  # Aggregation function (sum, count, avg, min, max, count_distinct)
    label: str  # Human-readable label
    name: str  # Metric identifier
    type: str  # Output type (integer, float)


# Schema for an analytics dataset definition.
class Dataset(BaseModel):
    dimensions: list[DatasetDimension]  # Available dimensions
    metrics: list[DatasetMetric]  # Available metrics
    name: str  # Dataset identifier
    time_dimension: DatasetDimension | None = None  # Time dimension for time series queries


# Schema for a dataset query result.
class DatasetQueryResult(BaseModel):
    columns: list[dict[str, object]]  # Column definitions with name, type, and label
    meta: dict[str, object]  # Query metadata (total_rows, query_time_ms)
    rows: list[dict[str, object]]  # Result rows as maps of column_name → value


# Schema for delete operations that return a deleted count.
class DeletionConfirmation(BaseModel):
    deleted_count: int  # Number of deleted records


# Schema for developer account billing settings.
class Developer(BaseModel):
    auto_reup_amount_cents: int | None = None
    auto_reup_enabled: bool | None = None  # Whether automatic credit reup is enabled
    auto_reup_threshold_cents: int | None = None
    billing_provider_environment: str | None = None  # Stripe environment (live or test)
    billing_provider_id: str | None = None  # Stripe customer ID
    pending_plan: str | None = None
    plan: str | None = None  # Active billing plan (e.g. paygo)


# Schema for an organization.
# Maps to serialized org output from developer portal API.
class DeveloperOrg(BaseModel):
    created_at: str | None = None  # Created timestamp
    description: str | None = None  # Organization description
    domain: str  # Primary domain
    id: str  # Public ID (org_...)
    industry: str | None = None  # Industry category
    name: str  # Organization name
    sandbox: str | None = None  # Sandbox identifier (nullable)
    slug: str  # URL-safe slug
    status: str | None = None  # Status (active, suspended, trialing)
    updated_at: str | None = None  # Updated timestamp
    website: str | None = None  # Website URL


# Schema for a system access token (developer admin view).
# Maps to serialized system access token output from developer portal API.
class DeveloperSystemAccessToken(BaseModel):
    created_at: str | None = None  # Created timestamp
    id: str  # Public ID (sat_...)
    last_used_at: str | None = None  # Last used timestamp
    name: str | None = None  # Optional label for the token
    revoked_at: str | None = None  # Revoked timestamp
    token: str | None = None  # Raw JWT (only present on creation)


# Schema for a thread in the developer portal.
# Maps to serialized thread output from developer portal API.
class DeveloperThread(BaseModel):
    app_name: str | None = None  # Associated app name
    created_at: str | None = None  # Created timestamp
    id: str  # Public ID (thr_...)
    is_channel: bool | None = None  # Whether this is a channel thread
    is_default: bool | None = None  # Whether this is the default thread
    is_unlisted: bool | None = None  # Whether thread is hidden from listings
    key: str | None = None  # Unique key within owner scope
    org: str | None = None  # Organization (nullable)
    owner: str | None = None  # Owner public
    owner_name: str | None = None  # Owner display name
    owner_type: str | None = None  # Owner type: team, user, agent, or nil
    sandbox: str | None = None  # Sandbox identifier (nullable)
    slug: str | None = None  # URL-friendly slug
    title: str  # Thread title
    updated_at: str | None = None  # Updated timestamp


# Schema for a user (developer admin view).
# Maps to serialized user output from developer portal API.
class DeveloperUser(BaseModel):
    alias: str | None = None  # User alias
    confirmed_at: str | None = None  # Email confirmed timestamp
    created_at: str | None = None  # Created timestamp
    email: str  # Email address
    full_name: str | None = None  # Full name
    id: str  # Public ID (usr_...)
    is_system_user: bool | None = None  # Whether this is a system user
    org: str | None = None  # Organization (nullable)
    org_name: str | None = None  # Organization display name (nullable)
    org_role: str | None = None  # Organization role (admin, member, viewer; nullable)
    password: str | None = None  # Temporary plaintext password returned on reset
    sandbox: str | None = None  # Sandbox identifier (nullable)
    updated_at: str | None = None  # Updated timestamp


# API schema for OAuth device authorization responses.
class DeviceAuthorizationResponse(BaseModel):
    device_code: str  # Device verification code
    expires_in: int  # TTL in seconds
    interval: int  # Polling interval in seconds
    user_code: str  # User-facing verification code
    verification_uri: str  # Base verification URI
    verification_uri_complete: str  # Full verification URI with code


# API schema for OAuth device authorization approval and denial responses.
class DeviceAuthorizationStatusResponse(BaseModel):
    status: str  # Authorization status (approved or denied)


# Schema for a registered domain.
# Maps to serialized domain output from developer portal API.
class Domain(BaseModel):
    created_at: str | None = None  # Created timestamp
    domain: str  # Domain name
    id: str  # Public ID (dad_...)
    updated_at: str | None = None  # Updated timestamp
    verified: bool | None = None  # Whether domain is verified


# Schema for a developer portal domain event.
class DomainEvent(BaseModel):
    agent: str | None = None  # Agent identifier
    created_at: str | None = None  # Created timestamp
    event_name: str  # Event name
    id: str  # Domain event ID
    idempotency_key: str | None = None  # Idempotency key for the event
    payload: dict[str, object]  # Event payload
    team: str | None = None  # Team identifier
    user: str | None = None  # User identifier


# Schema for paginated domain event responses.
class DomainEventPage(BaseModel):
    data: list[DomainEvent]  # Domain events
    has_next: bool  # Whether a next page exists
    has_prev: bool  # Whether a previous page exists
    page: int  # Current page number
    page_size: int  # Page size
    total_entries: int  # Total entries
    total_pages: int  # Total pages


# Schema for an encrypted secret payload.
class EncryptedSecret(BaseModel):
    encrypted_value: str  # Encrypted ciphertext value


# Schema for an eval result.
class EvalResult(BaseModel):
    agent_response: str | None = None  # Agent response
    created_at: str | None = None  # Created timestamp
    duration_ms: int | None = None  # Execution duration
    grader_details: dict[str, object] | None = None  # Grader details
    id: str  # Eval result ID
    run: str  # Parent eval run identifier
    score: float | None = None  # Result score
    status: str  # Result status
    task: str | None = None  # Eval task identifier
    task_input: str | None = None  # Task input summary
    transcript: dict[str, object] | None = None  # Execution transcript
    updated_at: str | None = None  # Updated timestamp


# Schema for eval result list responses.
class EvalResultList(BaseModel):
    data: list[EvalResult]  # Eval results


# Schema for an eval run.
class EvalRun(BaseModel):
    agent: str | None = None  # Agent identifier
    agent_name: str | None = None  # Agent name
    completed_at: str | None = None  # Completion timestamp
    created_at: str | None = None  # Created timestamp
    id: str  # Eval run ID
    results: list[EvalResult] | None = None  # Eval results for this run
    started_at: str | None = None  # Start timestamp
    status: str  # Run status
    suite: str  # Eval suite identifier
    summary: dict[str, object] | None = None  # Aggregate run summary
    updated_at: str | None = None  # Updated timestamp


# Schema for eval run list responses.
class EvalRunList(BaseModel):
    data: list[EvalRun]  # Eval runs


# Schema for an eval task.
class EvalTask(BaseModel):
    created_at: str | None = None  # Created timestamp
    expected_outcome: str  # Expected outcome
    grading_criteria: list[dict[str, object]] | None = None  # Grading criteria
    id: str  # Eval task ID
    input_message: str  # Task input message
    mock_agent_memory: dict[str, object] | None = None  # Mock agent memory
    mock_context_items: list[dict[str, object]] | None = None  # Mock context items
    mock_datetime: str | None = None  # Mock datetime
    mock_participants: list[dict[str, object]] | None = None  # Mock participants
    mock_tools: list[dict[str, object]] | None = None  # Mock tool definitions
    status: str  # Task status
    suite: str  # Parent eval suite identifier
    updated_at: str | None = None  # Updated timestamp


# Schema for an eval suite.
class EvalSuite(BaseModel):
    created_at: str | None = None  # Created timestamp
    description: str | None = None  # Suite description
    id: str  # Eval suite ID
    name: str  # Suite name
    org: str | None = None  # Owner organization identifier
    status: str  # Suite status
    tasks: list[EvalTask] | None = None  # Eval tasks included in the suite
    updated_at: str | None = None  # Updated timestamp
    user: str | None = None  # Owner user identifier


# Schema for eval suite list responses.
class EvalSuiteList(BaseModel):
    data: list[EvalSuite]  # Eval suites


# Schema for eval task list responses.
class EvalTaskList(BaseModel):
    data: list[EvalTask]  # Eval tasks


# Schema for an event catalog entry with full payload schema and sample.
class EventCatalogEntry(BaseModel):
    description: str  # Human-readable description
    name: str  # Event name (e.g., thread.created)
    parent: str | None = None  # Parent envelope name (only present for sub_event entries)
    sample: dict[str, object]  # Sample payload for this event
    schema: dict[str, object]  # JSON Schema describing the event payload
    sub_events: list[str] | None = None
    type: str | None = None


# Schema for an event type available for automation triggers.
# Represents events from the workflow event catalog.
class EventType(BaseModel):
    description: str  # Human-readable description
    name: str  # Event name (e.g., thread.created)


# API schema for file URL refresh responses.
class FileRefreshResult(BaseModel):
    image_source: ImageSource  # Updated image source with fresh URL
    success: bool  # Whether the refresh succeeded


# API schema for an installation.
class Installation(BaseModel):
    agent: str | None = None  # Owning agent
    config: dict[str, object] | None = None  # Configuration
    created_at: str | None = None  # Creation timestamp
    id: str  # Installation ID (cin_...)
    kind: str | None = None  # Installation kind
    shared_integration: str | None = None  # Bound shared integration
    state: str | None = None  # Installation state
    status_payload: dict[str, object] | None = None  # Status payload
    updated_at: str | None = None  # Last update timestamp


# API schema for an installation kind.
class InstallationKind(BaseModel):
    accepts_sources: bool | None = None  # Whether this kind accepts sources
    category: str | None = None  # Category
    config_schema: dict[str, object] | None = None  # JSON schema for configuration
    description: str | None = None  # Description
    kind: str  # Installation kind identifier
    label: str | None = None  # Display label
    provider: str | None = None  # Integration provider
    requires_integration: bool | None = None  # Whether this kind requires an integration


# List response for installation kinds.
class InstallationKindListResponse(BaseModel):
    data: list[InstallationKind]  # List of installation kinds


# List response for installations.
class InstallationListResponse(BaseModel):
    data: list[Installation]  # List of installations


# API schema for an installation source.
class InstallationSource(BaseModel):
    agent: str | None = None  # Owning agent
    context_installation: str | None = None  # Installation ID
    created_at: str | None = None  # Creation timestamp
    id: str  # Source ID (cso_...)
    metadata: dict[str, object] | None = None  # Arbitrary metadata
    parent_source: str | None = None  # Parent source ID
    payload: dict[str, object] | None = None  # Source payload
    state: str | None = None  # Source state
    team: str | None = None  # Team ID
    thread: str | None = None  # Thread ID
    type: str | None = None  # Source type
    updated_at: str | None = None  # Last update timestamp
    user: str | None = None  # User ID


# List response for installation sources.
class InstallationSourceListResponse(BaseModel):
    data: list[InstallationSource]  # List of installation sources


# Schema for integration records with connector state.
class Integration(BaseModel):
    id: str  # Integration ID
    org: str | None = None  # Organization (nullable)
    provider: str  # Provider identifier
    sandbox: str | None = None  # Sandbox identifier (nullable)
    secret_group: str | None = None  # Secret group
    state: dict[str, object]  # Connector state information
    team: str | None = None  # Team (if team-scoped)
    user: str | None = None  # User (if user-scoped)
    workspace_key: str | None = None  # Provider workspace identifier


# Schema for integration action metadata.
class IntegrationAction(BaseModel):
    description: str | None = None  # Action description
    json_schema: dict[str, object]  # JSON Schema for action parameters
    key: str  # Action key (e.g., gmail.list_messages)
    scopes_any_of: dict[str, object] | None = None  # Required scope sets for this action


# Integration fields for auto-creating the underlying integration.
# When creating an agent installation for an `integration/*` kind, callers
# can pass this object to auto-create the underlying Integration record.
# Required fields depend on the kind's auth type:
# - `app_installation` kinds (slack_bot, github_app): requires `installation_id`
# - `oauth` kinds (gmail, outlook, slack): requires `access_token`
class IntegrationCreateParams(BaseModel):
    access_token: str | None = None  # OAuth access token or API key
    installation_id: str | None = None
    metadata: dict[str, object] | None = None  # Provider-specific metadata (e.g. bot_user_id)
    refresh_token: str | None = None  # OAuth refresh token
    workspace_key: str | None = None  # Workspace name or identifier


# Schema for an integration provider entry.
# Represents an available integration provider (OAuth or MCP) that can be
# used with `create integration --provider <provider>`.
class IntegrationProvider(BaseModel):
    auth_type: str  # Auth mechanism: oauth, bearer, or app_installation
    description: str | None = None  # Short description of the provider
    display_name: str  # Human-readable display name
    provider: str  # Provider key (e.g., google, mcp:system:mcp-github)
    type: str  # Provider type: oauth, mcp, or app_installation


# Schema for a key-value storage entry.
# Maps exactly to render_entry/1 output in ApiStorageController.
class KeyValueStorageEntry(BaseModel):
    created_at: str | None = None  # Creation timestamp
    key: str  # Storage key
    updated_at: str | None = None  # Last update timestamp
    user: str  # User
    value: str  # Stored value


# List response for key-value storage entries.
class KeyValueStorageEntryList(BaseModel):
    data: list[KeyValueStorageEntry]  # Storage entries owned by the caller


# API schema for a knowledge search result item.
class KnowledgeSearchResult(BaseModel):
    content: str | None = None  # Normalized content text
    content_type: str | None = None  # Content MIME type
    created_at: str | None = None  # Creation timestamp
    id: str  # Item ID (cim_...)
    metadata: dict[str, object] | None = None  # Additional metadata
    raw_content: dict[str, object] | None = None  # Raw content data
    type: str | None = None  # Source type (requires preloaded :source association)


# Schema for an LLM session call.
# Maps to serialized LLM call output from developer portal API.
class LlmCall(BaseModel):
    call_id: str  # Unique call UUID
    completion_tokens: int  # Number of completion tokens
    created_at: str | None = None  # Created timestamp
    error_message: str | None = None  # Error message if call failed
    id: str  # Public ID (alc_...)
    latency_ms: int  # Latency in milliseconds
    message_count: int | None = None  # Number of messages included in the call metadata
    metadata: dict[str, object] | None = None  # Additional metadata
    model: str | None = None  # LLM model name
    prompt_tokens: int  # Number of prompt tokens
    session_id: str  # Session UUID grouping related calls
    source: str | None = None  # Machine-readable call source key
    status: str | None = None  # Call status (success or error)
    team: str | None = None  # Team if team-scoped
    total_tokens: int  # Total tokens (prompt + completion)
    trajectory: str | None = None  # Trajectory identifier
    user: str | None = None  # User if user-scoped


# Source option metadata for LLM call filtering.
class LlmCallSourceOption(BaseModel):
    label: str  # Human-friendly source label
    source: str  # Machine-readable LLM source key


# Schema for LLM call trajectory contents.
class LlmCallTrajectory(BaseModel):
    download_url: str | None = None  # Signed transcript download URL
    messages: list[dict[str, object]]  # Trajectory messages


# API schema for a media item.
class Media(BaseModel):
    content_type: str | None = None  # Original variant content type
    created_at: str | None = None  # Creation timestamp
    filename: str | None = None  # Original variant filename
    height: int | None = None  # Original variant height
    id: str  # Media ID
    media_type: str | None = None  # Media type
    name: str | None = None  # Media name
    org: str | None = None  # Organization
    sandbox: str | None = None  # Sandbox
    updated_at: str | None = None  # Last update timestamp
    url: str | None = None  # Original variant URL
    variants: list[MediaVariant] | None = None  # Media variants
    width: int | None = None  # Original variant width


# Schema for inline message reactions.
# This is the compact format used in Message.reactions[], which differs from
# the full Reaction schema used in standalone reaction endpoints.
# Maps to format_reactions_for_client/1 output.
class MessageReaction(BaseModel):
    payload: dict[str, object] | None = None  # Reaction payload (e.g., {emoji: '👍'})
    type: str  # Reaction type (e.g., emoji_reaction)
    user: str | None = None  # User who added the reaction


# API schema for a chat message.
class Message(BaseModel):
    actors: list[Actor] | None = None  # Message actors
    agent: str | None = None  # Agent if sent by an agent user
    attachments: list[Attachment] | None = None  # Message attachments
    branched_thread: str | None = None  # Branched thread (if message spawned a thread)
    content: str | None = None  # Message content
    created_at: str | None = None  # Creation timestamp
    has_replies: bool | None = None  # Whether message has replies
    id: str  # Message ID (msg_...)
    idempotency_key: str | None = None  # Client-provided idempotency key
    legacy_agent: str | None = None  # Legacy agent if sent by legacy chat agent
    metadata: dict[str, object] | None = None  # Message metadata
    org: str | None = None  # Organization
    reactions: list[MessageReaction] | None = None  # Message reactions
    rendering_mode: str | None = None  # Rendering mode hint
    replies: list[dict[str, object]] | None = None  # Inline replies (if loaded)
    replies_after_cursor: str | None = None  # Cursor for replies pagination
    replies_before_cursor: str | None = None  # Cursor for replies pagination
    reply_count: int | None = None  # Number of replies
    reply_to: dict[str, object] | None = None  # Parent message object (if loaded)
    sandbox: str | None = None  # Sandbox identifier
    team: str | None = None  # Team
    thread: str | None = None  # Parent thread
    user: str | None = None  # Author user (public ID or expanded object when loaded)


# Schema for message update request parameters.
# Used as the body wrapper when updating a message.
class MessageUpdateParams(BaseModel):
    content: str | None = None  # New message content


# Filter object for matching thread metadata.
class MetadataFilter(BaseModel):
    key: str  # Metadata key to match
    type: str  # Filter type (must be "metadata")
    value: str  # Metadata value to match


# Schema for a single notification setting update entry.
class NotificationSettingUpdate(BaseModel):
    level: str  # Notification level (global, team, thread)
    muted: bool  # Whether notifications are muted
    team: str | None = None  # Team (required for team-level settings)
    thread: str | None = None  # Thread (required for thread-level settings)


# Schema for an OAuth client registration.
class OAuthClient(BaseModel):
    client_id: str  # Public OAuth client ID
    client_name: str  # Display name for the client
    client_secret: str | None = None  # Client secret shown only at creation
    created_at: str | None = None  # Created timestamp
    enabled: bool  # Whether the client is enabled
    id: str  # OAuth client registration ID
    redirect_uris: list[str]  # Allowed redirect URIs
    scopes: list[str]  # Allowed OAuth scopes
    updated_at: str | None = None  # Updated timestamp


# Schema for OAuth client list responses.
class OAuthClientList(BaseModel):
    data: list[OAuthClient]  # OAuth clients


# OAuth error response per RFC 6749
class OAuthError(BaseModel):
    error: str  # Error code (e.g. slow_down, invalid_grant)
    error_description: str | None = None  # Human-readable error description


# Schema for an OAuth provider configuration.
# Maps to serialized OAuth provider output from developer portal API.
class OAuthProvider(BaseModel):
    callback_urls: list[str] | None = None  # Allowed callback URLs
    client_id: str  # OAuth client ID
    created_at: str | None = None  # Created timestamp
    display_name: str | None = None  # Display name
    enabled: bool | None = None  # Whether provider is enabled
    id: str  # Public ID (dop_...)
    provider: str  # Provider type (github, google)
    scopes: list[str] | None = None  # OAuth scopes
    updated_at: str | None = None  # Updated timestamp


# API schema for OAuth token endpoint responses.
class OAuthTokenResponse(BaseModel):
    access_token: str  # OAuth access token
    expires_in: int  # Token TTL in seconds
    refresh_token: str | None = None  # OAuth refresh token
    scope: str | None = None  # Granted scopes (space-separated)
    token_type: str  # Token type (Bearer)
    user: User | None = None  # Authenticated user


# Schema for paginated messages response.
# Used by thread messages list endpoints.
class PaginatedMessages(BaseModel):
    after_cursor: str | None = None  # Cursor for fetching items after this point
    before_cursor: str | None = None  # Cursor for fetching items before this point
    messages: list[Message]  # List of message objects


# Schema for paginated message replies response.
# Used by message replies list endpoints.
# Note: This response is NOT wrapped in a "data" field.
class PaginatedReplies(BaseModel):
    after_cursor: str | None = None  # Cursor for fetching items after this point
    before_cursor: str | None = None  # Cursor for fetching items before this point
    has_more: bool | None = None  # Whether more replies exist beyond the current page
    replies: list[Message]  # List of reply message objects
    total_count: int | None = None  # Total number of replies


# Schema for password update parameters.
class PasswordUpdateParams(BaseModel):
    password: str  # New password
    password_confirmation: str  # New password confirmation


# API schema for a persona.
class Persona(BaseModel):
    activated: bool | None = None  # Whether persona is activated
    agent: str | None = None  # Associated agent (always nil)
    created_at: str | None = None  # Creation timestamp
    id: str  # Persona ID
    is_active: bool | None = None  # Whether persona is active
    is_enabled_for_thread: bool | None = None  # Whether persona is enabled for thread
    metadata: dict[str, object] | None = None  # Persona metadata
    name: str | None = None  # Persona display name
    org: str | None = None  # Organization
    personality: str | None = None  # Persona personality description
    sandbox: str | None = None  # Sandbox
    team: str | None = None  # Owning team
    updated_at: str | None = None  # Last update timestamp
    user: str | None = None  # Owning user


# Schema for persona creation parameters.
class PersonaCreateParams(BaseModel):
    name: str  # Persona display name
    personality: str  # Persona personality description
    profile_picture_style: str | None = None  # Profile picture generation style


# Schema for persona update parameters.
class PersonaUpdateParams(BaseModel):
    metadata: dict[str, object] | None = None  # Additional metadata
    name: str | None = None  # Persona display name
    personality: str | None = None  # Persona personality description


# Schema for picture upload parameters.
# Used for uploading profile pictures via base64 encoded data.
class PictureParams(BaseModel):
    data: str  # Base64 encoded image data
    filename: str  # Original filename
    mime_type: str  # MIME type of the image


# Public org schema for authenticated endpoints.
# Only exposes fields safe for any authenticated user: id, name, domain,
# and logo. Does NOT expose sandbox, status, industry, description, or
# other internal fields that the Developer.Org schema includes.
class PublicOrg(BaseModel):
    domain: str  # Primary domain
    id: str  # Public ID (org_...)
    name: str  # Organization name


# API schema for push notification test results.
class PushNotificationResult(BaseModel):
    results: list[dict[str, object]] | None = None  # Per-device results
    success: bool  # Whether the notification was sent
    total_sent: int | None = None  # Number of notifications sent


# A routine preset with its metadata.
class RoutinePreset(BaseModel):
    config: dict[str, object] | None = None  # Default configuration
    description: str | None = None  # Preset description
    event_type: str | None = None  # Event type
    label: str | None = None  # Display label
    name: str  # Preset name


# Schema for runtime environment variable metadata.
class RuntimeEnvVar(BaseModel):
    description: str | None = None  # Optional description
    key: str  # Environment variable key
    source: str  # Source of the env var (app or org)


# Schema for runtime environment variable metadata list responses.
class RuntimeEnvVarList(BaseModel):
    data: list[RuntimeEnvVar]


# Schema for a sandbox-captured email.
class SandboxEmail(BaseModel):
    bcc: list[dict[str, object]] | None = None  # BCC recipients
    cc: list[dict[str, object]] | None = None  # CC recipients
    created_at: str | None = None  # When the email was captured
    from_address: str  # Sender email address
    from_name: str | None = None  # Sender display name
    headers: dict[str, object] | None = None  # Custom email headers
    html_body: str | None = None  # HTML body
    id: str  # Public ID (sem_...)
    reply_to: dict[str, object] | None = None  # Reply-to address
    subject: str | None = None  # Email subject
    text_body: str | None = None  # Plain text body
    to: list[dict[str, object]]  # Recipients [{name, address}]


# API schema for a scrape result.
class Scrape(BaseModel):
    created_at: str | None = None  # Creation timestamp
    description: str | None = None  # Page description
    id: str  # Scrape ID (scp_...)
    image_height: int | None = None  # Image height in pixels
    image_url: str | None = None  # Image URL
    image_width: int | None = None  # Image width in pixels
    last_scraped_at: str | None = None  # Last scraped timestamp
    metadata: dict[str, object] | None = None  # Scrape metadata
    status: str | None = None  # Scrape status
    title: str | None = None  # Page title
    updated_at: str | None = None  # Last update timestamp
    url: str | None = None  # Scraped URL
    version: int | None = None  # Scrape version


# API schema for a secret (user, team, or user-team).
class Secret(BaseModel):
    created_at: str | None = None  # Creation timestamp
    description: str | None = None  # Secret description
    id: str  # Secret ID
    last_accessed_at: str | None = None  # Last accessed timestamp
    name: str | None = None  # Secret name
    org: str | None = None  # Organization
    sandbox: str | None = None  # Sandbox
    secret_group: str | None = None  # Secret group
    team: str | None = None  # Team
    updated_at: str | None = None  # Last update timestamp


# API schema for a decrypted secret value response.
class SecretValue(BaseModel):
    name: str  # Secret name
    value: str  # Decrypted secret value


# API schema for the status/ping health check response.
class StatusPing(BaseModel):
    success: bool  # Whether the ping succeeded
    token: dict[str, object]  # Token status details
    user: User | None = None  # Authenticated user (if token is valid)


# API schema for a storage file.
class StorageFile(BaseModel):
    content_type: str | None = None  # MIME content type
    created_at: str | None = None  # Creation timestamp
    filename: str | None = None  # Original filename
    id: str  # File ID
    image_source: ImageSource | None = None  # Image source metadata
    org: str | None = None  # Organization
    sandbox: str | None = None  # Sandbox
    size: int | None = None  # File size in bytes
    updated_at: str | None = None  # Last update timestamp
    url: str | None = None  # Signed download URL


# API schema for a task.
class Task(BaseModel):
    closed_at: str | None = None  # When the task was closed
    comments_count: int | None = None  # Number of comments
    created_at: str | None = None  # Creation timestamp
    created_by: str | None = None  # Legacy creator
    created_by_actor: dict[str, object] | None = None  # Creator actor details
    created_by_persona: str | None = None  # Creator persona
    created_by_type: str | None = None  # Creator type (user, agent)
    created_by_user: str | None = None  # Creator user
    description: str | None = None  # Task description
    due_date: str | None = None  # Due date
    id: str  # Task ID (tsk_...)
    links: dict[str, object] | None = None  # Related links
    metadata: dict[str, object] | None = None  # Additional metadata
    name: str  # Task name
    org: str | None = None  # Organization
    owner: str | None = None  # Legacy owner
    owner_actor: dict[str, object] | None = None  # Owner actor details
    owner_persona: str | None = None  # Owner persona
    owner_user: str | None = None  # Owner user
    priority: int | None = None  # Priority level (0-4)
    sandbox: str | None = None  # Sandbox identifier
    status: str  # Task status
    team: str | None = None  # Team
    updated_at: str | None = None  # Last update timestamp


# Schema for a task activity entry.
# Maps exactly to the activity entries produced by TaskActivitySentenceGenerator.
class TaskActivityEntry(BaseModel):
    event_id: str | None = None  # Event ID
    event_type: str | None = None  # Type of event
    sentence: str | None = None  # Human-readable description of the activity
    timestamp: str | None = None  # When the event occurred


# API schema for a task comment.
class TaskComment(BaseModel):
    author: str | None = None  # Legacy author
    author_actor: dict[str, object] | None = None  # Author actor details
    author_persona: str | None = None  # Author persona
    author_user: str | None = None  # Author user
    body: str  # Comment body text
    created_at: str | None = None  # Creation timestamp
    id: str  # Comment ID
    org: str | None = None  # Organization
    sandbox: str | None = None  # Sandbox identifier
    task: str | None = None  # Task
    team: str | None = None  # Team
    updated_at: str | None = None  # Last update timestamp


# Schema for task creation parameters.
# Used by both Users.Tasks.Create and Teams.Tasks.Create actions.
class TaskCreateParams(BaseModel):
    description: str | None = None  # Task description
    due_date: str | None = None  # Due date
    links: dict[str, object] | None = None  # Related links
    metadata: dict[str, object] | None = None  # Additional metadata
    name: str  # Task name
    owner_persona: str | None = None  # Owner persona if assigned to agent
    owner_user: str | None = None  # Owner user if assigned to user
    priority: int | None = None  # Priority level (0-4)
    status: str | None = None  # Task status (open, in_progress, done)
    task: str | None = None  # Custom task ID (optional, auto-generated if not provided)


# Schema for task update parameters.
# Used by both Users.Tasks.Update and Teams.Tasks.Update actions.
# All fields are optional since updates only modify provided fields.
class TaskUpdateParams(BaseModel):
    description: str | None = None  # Task description
    due_date: str | None = None  # Due date
    links: dict[str, object] | None = None  # Related links
    metadata: dict[str, object] | None = None  # Additional metadata
    name: str | None = None  # Task name
    owner_persona: str | None = None  # Owner persona if assigned to agent
    owner_user: str | None = None  # Owner user if assigned to user
    priority: int | None = None  # Priority level (0-4)
    status: str | None = None  # Task status (open, in_progress, done)


# Filter object for matching personas by template ID.
class TemplateFilter(BaseModel):
    id: str  # Persona template ID to match
    type: str  # Filter type (must be "template")


# API schema for an AI trajectory.
class Trajectory(BaseModel):
    created_at: str | None = None  # Creation timestamp
    file: str | None = None  # Storage file
    id: str  # Trajectory ID (trj_...)
    messages: dict[str, object] | None = None  # Trajectory messages
    org: str | None = None  # Organization
    sandbox: str | None = None  # Sandbox
    team: str | None = None  # Team
    updated_at: str | None = None  # Last update timestamp


# Schema for config validation result.
class ValidationResult(BaseModel):
    errors: list[str] | None = None  # List of validation errors
    valid: bool  # Whether the config is valid
    warnings: list[str] | None = None  # Optional warnings emitted during validation


# Schema for a developer webhook.
# Maps to serialized webhook output from developer portal API.
class Webhook(BaseModel):
    context_installation: str | None = None  # Bound context installation
    context_sources: list[str] | None = None  # Bound context sources
    created_at: str | None = None  # Created timestamp
    enabled: bool  # Whether the webhook is enabled
    id: str  # Public ID (whk_...)
    lookup_key: str | None = None  # Lookup key for generic webhooks
    metadata: dict[str, object] | None = None  # Additional metadata
    provider: str | None = None
    updated_at: str | None = None  # Updated timestamp
    webhook_url: str  # URL to send webhooks to


# Schema for a webhook event.
# Maps to serialized webhook event output from developer portal API.
class WebhookEvent(BaseModel):
    created_at: str | None = None  # Created timestamp
    error: str | None = None  # Error message if failed
    event_type: str | None = None  # Event type from the provider
    headers: dict[str, object] | None = None  # Request headers
    id: str  # Public ID (whe_...)
    payload: dict[str, object] | None = None  # Event payload
    processed_at: str | None = None  # When the event was processed
    status: str  # Processing status (pending, processed, failed)


# API schema for a working memory entry.
class WorkingMemoryEntry(BaseModel):
    agent: str | None = None  # Owning agent
    created_at: str | None = None  # Creation timestamp
    expires_at: str | None = None  # Expiration timestamp
    id: str  # Memory entry ID (amm_...)
    key: str | None = None  # Memory key
    updated_at: str | None = None  # Last update timestamp
    value: str | None = None  # Memory value


# Paginated list response for working memory entries.
class WorkingMemoryEntryListResponse(BaseModel):
    data: list[WorkingMemoryEntry]  # List of working memory entries
    has_next: bool | None = None  # Whether a next page exists
    has_prev: bool | None = None  # Whether a previous page exists
    page: int | None = None  # Current page number
    page_size: int | None = None  # Results per page
    total_entries: int | None = None  # Total number of entries
    total_pages: int | None = None  # Total number of pages
