# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: b8bc1f9d598d


from pydantic import BaseModel, Field

from .users import User


class OAuthTokenResponse(BaseModel):
    """
    A successful OAuth 2.0 token response. Issued by the token endpoint after a completed authorization or device-flow grant.
    """

    access_token: str = Field(
        ...,
        description="Bearer token used to authenticate API requests. Include this value in the `Authorization: Bearer <token>` header.",
    )
    expires_in: int = Field(..., description="Number of seconds until the access token expires.")
    refresh_token: str | None = Field(
        default=None,
        description="Token that can be exchanged for a new access token once the current one expires. `null` if the grant type does not issue refresh tokens.",
    )
    scope: str | None = Field(
        default=None,
        description="Space-separated list of scopes granted to the access token. `null` if scope was not included in the grant request.",
    )
    token_type: str = Field(..., description='Token type. Always `"Bearer"`.')
    user: User | None = Field(
        default=None,
        description="The authenticated user associated with this token. `null` when the token is not tied to a specific user (e.g. client-credentials grants).",
    )
