# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: b5cd0443882a

from typing import Any

from pydantic import BaseModel, Field

from .common import Deployment
from .users import User


class StatusPing(BaseModel):
    """
    Health check response confirming the API is reachable and indicating whether the caller's token is valid.
    """

    deployment: Deployment | None = Field(default=None, description="Deployment metadata.")
    success: bool = Field(
        ...,
        description="`true` when the platform is reachable and the request was processed successfully.",
    )
    token: dict[str, Any] = Field(
        ..., description="Details about the authentication token used in this request."
    )
    user: User | None = Field(
        default=None,
        description="The authenticated user associated with the token. `null` when the token is invalid or absent.",
    )
