# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 287fea7c998c


from pydantic import BaseModel


# API schema for a system access token.
class SystemAccessToken(BaseModel):
    created_at: str | None = None  # Creation timestamp
    id: str  # Token ID (sat_...)
    last_used_at: str | None = None  # Last used timestamp
    name: str | None = None  # Token name
    revoked_at: str | None = None  # Revocation timestamp
