# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: ac4e8211e449

from datetime import datetime

from pydantic import BaseModel

from .agents import Agent
from .common import Message
from .users import User


# Schema for thread settings response.
# Used by thread settings show/update endpoints.
class ThreadSettings(BaseModel):
    agent_enabled: bool | None = None  # Whether the agent is enabled for this thread


# API schema for a chat thread.
class Thread(BaseModel):
    agent_user: str | None = None  # Owning agent user
    created_at: datetime | None = None  # Creation timestamp
    creator: User | None = None  # Creator user object
    description: str | None = None  # Thread description
    id: str  # Thread ID (thr_...)
    is_channel: bool | None = None  # Whether this is a channel
    is_default: bool | None = None  # Whether this is the default thread
    is_transient: bool | None = None  # Whether this thread is transient
    is_unlisted: bool | None = None  # Whether this thread is unlisted
    key: str | None = None  # Thread key
    last_activity: datetime | None = None  # Last activity timestamp
    metadata: dict[str, object] | None = None  # Thread metadata
    org: str | None = None  # Organization
    parent_message: Message | None = None  # Parent message object
    participant: list[str] | None = None  # Participant users
    participants: list[User] | None = None  # Participant user objects
    participating_actor: list[str] | None = None  # Actors participating in thread
    participating_agents: list[Agent] | None = None  # Agents participating in thread
    role: str | None = None  # User's role in the thread
    sandbox: str | None = None  # Sandbox identifier
    settings: ThreadSettings | None = None  # Thread settings
    slug: str | None = None  # Thread slug
    sub_threads: list[dict[str, object]] | None = None  # Sub-threads
    team: str | None = None  # Owning team
    title: str | None = None  # Thread title
    ttl: int | None = None  # Time-to-live in seconds
    unread_count: int | None = None  # Unread message count
    updated_at: datetime | None = None  # Last update timestamp
    user: str | None = None  # Owning user


# API schema for a thread member.
class ThreadMember(BaseModel):
    membership_type: str | None = None  # Membership type (owner or member)
    thread: str | None = None  # Thread
    user: User | None = None  # User details (when loaded)


# Schema for thread read status response.
class ThreadReadStatus(BaseModel):
    last_read_message: str | None = None  # Last read message
    thread: str  # Thread
    unread_count: int  # Number of unread messages
