# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: e584b56fa939

from __future__ import annotations

from ...runtime.http_client import HttpClient
from ...types.agents import AgentTool, AgentToolListResponse
from ...types.common import BuiltinToolCatalogEntry


class AgentToolResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(self, **params) -> AgentToolListResponse:
        return await self._http.request("/api/v1/agent_tools", query=params)

    async def catalog(self) -> list[BuiltinToolCatalogEntry]:
        return await self._http.request("/api/v1/agent_tools/catalog")

    async def delete(self, tool: str) -> None:
        await self._http.request(f"/api/v1/agent_tools/{tool}", method="DELETE")

    async def get(self, tool: str) -> AgentTool:
        return await self._http.request(f"/api/v1/agent_tools/{tool}")

    async def update(self, tool: str, input: dict) -> AgentTool:
        return await self._http.request(f"/api/v1/agent_tools/{tool}", method="PATCH", body=input)

    async def activate(self, tool: str) -> AgentTool:
        return await self._http.request(f"/api/v1/agent_tools/{tool}/activate", method="POST")

    async def deactivate(self, tool: str) -> AgentTool:
        return await self._http.request(f"/api/v1/agent_tools/{tool}/deactivate", method="POST")
