# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 8d5691fe4943

from __future__ import annotations

from datetime import datetime
from typing import Required, TypedDict

from pydantic import BaseModel

from ...runtime.http_client import HttpClient
from ...types.agents import (
    Agent,
    AgentComputer,
    AgentComputerListResponse,
    AgentExport,
    AgentListResponse,
    AgentRoutine,
    AgentSchedule,
    AgentTool,
    AgentToolListResponse,
)
from ...types.common import (
    Installation,
    InstallationKindListResponse,
    InstallationListResponse,
    WorkingMemoryEntryListResponse,
)
from ...types.threads import Thread


class AgentAgentComputerCreateInput(TypedDict, total=False):
    config: dict[str, object] | None  # Computer configuration
    lookup_key: str | None  # Unique lookup key
    metadata: dict[str, object] | None  # Arbitrary metadata
    name: Required[str]  # Computer name
    region: str | None  # Region to provision in (default: iad)


class AgentAgentInstallationCreateInputIntegration(TypedDict, total=False):
    access_token: str | None  # OAuth access token or API key
    installation_id: str | None
    metadata: dict[str, object] | None  # Provider-specific metadata (e.g. bot_user_id)
    refresh_token: str | None  # OAuth refresh token
    workspace_key: str | None  # Workspace name or identifier


class AgentAgentInstallationCreateInput(TypedDict, total=False):
    config: dict[str, object] | None  # Optional configuration
    integration: AgentAgentInstallationCreateInputIntegration | None
    kind: Required[str]  # Installation kind (gmail, outlook, github, scrape/site)
    shared_integration: str | None  # Shared org/app integration ID to bind to this installation


class AgentAgentToolCreateInput(TypedDict, total=False):
    builtin_tool_config: dict[str, object] | None  # Built-in tool config
    builtin_tool_key: str | None  # Built-in tool key (for builtin kind)
    config: str | None  # Config ID (for custom kind)
    description: str | None  # Tool description (for custom kind)
    handler_type: str | None  # Handler type: script or workflow_graph (for custom kind)
    kind: Required[str]  # Tool kind: builtin or custom
    lookup_key: str | None  # Unique lookup key
    metadata: dict[str, object] | None  # Arbitrary metadata
    name: str | None  # Tool name (for custom kind)
    parameters: dict[str, object] | None  # JSON schema for parameters (for custom kind)
    status: str | None  # Tool status: draft or active (default: draft)


class AgentCreateInputAclAddItem(TypedDict, total=False):
    actions: Required[list[str]]  # List of allowed actions (e.g. read, write)
    principal: str | None
    principal_type: Required[str]  # Principal type: user, team, org, org_role, agent, or everyone


class AgentCreateInputAclGrantsItem(TypedDict, total=False):
    actions: Required[list[str]]  # List of allowed actions (e.g. read, write)
    principal: str | None
    principal_type: Required[str]  # Principal type: user, team, org, org_role, agent, or everyone


class AgentCreateInputAclRemoveItem(TypedDict, total=False):
    principal: str | None  # Principal identifier to remove (omit for everyone)
    principal_type: Required[str]  # Principal type to remove


class AgentCreateInputAcl(TypedDict, total=False):
    add: list[AgentCreateInputAclAddItem] | None
    grants: list[AgentCreateInputAclGrantsItem] | None
    remove: list[AgentCreateInputAclRemoveItem] | None


class AgentCreateInputProfilePicture(TypedDict):
    data: str  # Base64-encoded image data
    filename: str  # Original filename
    mime_type: str  # MIME type of the image


class AgentCreateInput(TypedDict, total=False):
    acl: AgentCreateInputAcl | None  # Access control list
    email: str | None  # Agent email
    identity: str | None  # Identity prompt describing who the agent is
    lookup_key: str | None  # Unique lookup key
    metadata: dict[str, object] | None  # Arbitrary metadata
    model: str | None  # Default AI model for this agent
    name: str | None  # Agent name
    org: str | None  # Organization ID
    phone_number: str | None  # Agent phone number
    profile_picture: AgentCreateInputProfilePicture | None  # Base64-encoded profile picture
    team: str | None  # Team ID
    template: str | None  # Template ID to provision agent from
    user: str | None  # User ID


class AgentUpdateInputAclAddItem(TypedDict, total=False):
    actions: Required[list[str]]  # List of allowed actions (e.g. read, write)
    principal: str | None
    principal_type: Required[str]  # Principal type: user, team, org, org_role, agent, or everyone


class AgentUpdateInputAclGrantsItem(TypedDict, total=False):
    actions: Required[list[str]]  # List of allowed actions (e.g. read, write)
    principal: str | None
    principal_type: Required[str]  # Principal type: user, team, org, org_role, agent, or everyone


class AgentUpdateInputAclRemoveItem(TypedDict, total=False):
    principal: str | None  # Principal identifier to remove (omit for everyone)
    principal_type: Required[str]  # Principal type to remove


class AgentUpdateInputAcl(TypedDict, total=False):
    add: list[AgentUpdateInputAclAddItem] | None
    grants: list[AgentUpdateInputAclGrantsItem] | None
    remove: list[AgentUpdateInputAclRemoveItem] | None


class AgentUpdateInputProfilePicture(TypedDict):
    data: str  # Base64-encoded image data
    filename: str  # Original filename
    mime_type: str  # MIME type of the image


class AgentUpdateInput(TypedDict, total=False):
    acl: AgentUpdateInputAcl | None  # Access control list
    email: str | None  # Agent email
    identity: str | None  # Identity prompt describing who the agent is
    lookup_key: str | None  # Unique lookup key
    metadata: dict[str, object] | None  # Arbitrary metadata
    model: str | None  # Default AI model for this agent
    name: str | None  # Agent name
    org: str | None  # Organization ID
    phone_number: str | None  # Agent phone number
    profile_picture: AgentUpdateInputProfilePicture | None  # Base64-encoded profile picture
    team: str | None  # Team ID
    user: str | None  # User ID


class AgentAgentRoutinesInputAclAddItem(TypedDict, total=False):
    actions: Required[list[str]]  # List of allowed actions (e.g. read, write)
    principal: str | None
    principal_type: Required[str]  # Principal type: user, team, org, org_role, agent, or everyone


class AgentAgentRoutinesInputAclGrantsItem(TypedDict, total=False):
    actions: Required[list[str]]  # List of allowed actions (e.g. read, write)
    principal: str | None
    principal_type: Required[str]  # Principal type: user, team, org, org_role, agent, or everyone


class AgentAgentRoutinesInputAclRemoveItem(TypedDict, total=False):
    principal: str | None  # Principal identifier to remove (omit for everyone)
    principal_type: Required[str]  # Principal type to remove


class AgentAgentRoutinesInputAcl(TypedDict, total=False):
    add: list[AgentAgentRoutinesInputAclAddItem] | None
    grants: list[AgentAgentRoutinesInputAclGrantsItem] | None
    remove: list[AgentAgentRoutinesInputAclRemoveItem] | None


class AgentAgentRoutinesInputPresetConfigLlm(TypedDict, total=False):
    model: str | None  # Model identifier. When set, overrides the agent's default_model.


class AgentAgentRoutinesInputPresetConfig(TypedDict, total=False):
    instructions: str | None
    llm: AgentAgentRoutinesInputPresetConfigLlm | None
    session_mode: str | None
    session_scope: str | None
    structured_message_template_ids: list[str] | None


class AgentAgentRoutinesInputStepsItemPresetConfigLlm(TypedDict, total=False):
    model: str | None  # Model identifier. When set, overrides the agent's default_model.


class AgentAgentRoutinesInputStepsItemPresetConfig(TypedDict, total=False):
    instructions: str | None
    llm: AgentAgentRoutinesInputStepsItemPresetConfigLlm | None
    session_mode: str | None
    session_scope: str | None
    structured_message_template_ids: list[str] | None


class AgentAgentRoutinesInputStepsItem(TypedDict, total=False):
    config: str | None
    handler_type: Required[str]  # Handler type for this step: preset, script, or workflow_graph
    inputs: dict[str, object] | None
    name: str | None  # Optional step label. Must be unique within the chain if set.
    on_error: str | None  # Error policy: halt (default), continue, or retry.
    output_key: str | None
    preset_config: AgentAgentRoutinesInputStepsItemPresetConfig | None
    preset_name: str | None  # Preset name (for handler_type: preset)
    script: str | None  # Inline script source (for handler_type: script)


class AgentAgentRoutinesInput(TypedDict, total=False):
    acl: AgentAgentRoutinesInputAcl | None  # Access control list
    config: str | None  # Config ID (for workflow_graph handler)
    description: str | None  # Description
    event_config: dict[str, object] | None
    event_type: str | None  # Event type (deprecated, use event_config)
    handler_type: Required[str]  # Handler type: workflow_graph, script, preset, or chain
    lookup_key: str | None  # Unique lookup key
    metadata: dict[str, object] | None  # Arbitrary metadata
    name: Required[str]  # Routine name
    preset_config: AgentAgentRoutinesInputPresetConfig | None  # Preset config
    preset_name: str | None  # Preset name (for preset handler)
    schedule: str | None  # Cron expression for scheduled routines
    script: str | None  # Script content (for script handler)
    status: str | None  # Initial status: draft or active (default: draft)
    steps: list[AgentAgentRoutinesInputStepsItem] | None
    trigger_context: str | None  # Trigger context: chat_session or event (default: event)


class AgentSearchInput(TypedDict, total=False):
    max_results: int | None  # Max results to return
    mode: str | None  # Search mode: hybrid, vector, or fulltext
    query: Required[str]  # Search query
    recency_days: int | None  # Limit results to last N days
    source_types: list[str] | None  # Filter by source types


class AgentThreadsInputThread(TypedDict, total=False):
    description: str | None  # Thread description
    is_unlisted: bool | None  # Whether thread is unlisted
    key: str | None  # Unique thread key
    metadata: dict[str, object] | None  # Arbitrary metadata
    org: str | None  # Organization ID
    settings: dict[str, object] | None  # Thread settings
    title: str | None  # Thread title


class AgentThreadsInput(TypedDict, total=False):
    skip_welcome_message: bool | None  # Skip automatic welcome message
    thread: Required[AgentThreadsInputThread]  # Thread attributes


class ScheduleListResponseDataItem(BaseModel):
    agent: str | None = None  # Owning agent ID
    app: str | None = None  # Application ID
    created_at: datetime | None = None  # Creation timestamp
    cron_expression: str | None = None  # Cron expression (recurring only)
    id: str  # Schedule ID (asc_...)
    instructions: str | None = None  # Task instructions
    last_run_at: datetime | None = None  # Last execution time
    max_runs: int | None = None  # Maximum runs (recurring only)
    metadata: dict[str, object] | None = None  # Arbitrary metadata
    next_run_at: datetime | None = None  # Next scheduled execution
    run_count: int | None = None  # Number of times executed
    schedule_type: str | None = None  # Schedule type (once or recurring)
    scheduled_at: datetime | None = None  # One-time execution time
    status: str | None = None  # Schedule status
    thread: str | None = None  # Thread ID (if thread-bound)
    timezone: str | None = None  # Schedule timezone
    updated_at: datetime | None = None  # Last update timestamp


class ScheduleListResponse(BaseModel):
    data: list[ScheduleListResponseDataItem] | None = None  # Schedule entries


class AgentSearchResponseDataItem(BaseModel):
    content: str | None = None  # Normalized content text
    content_type: str | None = None  # Content MIME type
    created_at: datetime | None = None  # Creation timestamp
    id: str  # Item ID (cim_...)
    metadata: dict[str, object] | None = None  # Additional metadata
    raw_content: dict[str, object] | None = None  # Raw content data
    type: str | None = None  # Source type (requires preloaded :source association)


class AgentSearchResponse(BaseModel):
    data: list[AgentSearchResponseDataItem]  # Matching knowledge items


class AgentAgentComputerResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(self, agent: str) -> AgentComputerListResponse:
        return await self._http.request(f"/api/v1/agents/{agent}/agent_computers")

    async def create(self, agent: str, input: AgentAgentComputerCreateInput) -> AgentComputer:
        return await self._http.request(
            f"/api/v1/agents/{agent}/agent_computers",
            method="POST",
            body=input,
        )


class AgentAgentInstallationResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(self, agent: str) -> InstallationListResponse:
        return await self._http.request(f"/api/v1/agents/{agent}/agent_installations")

    async def create(self, agent: str, input: AgentAgentInstallationCreateInput) -> Installation:
        return await self._http.request(
            f"/api/v1/agents/{agent}/agent_installations",
            method="POST",
            body=input,
        )

    async def kinds(self, agent: str) -> InstallationKindListResponse:
        return await self._http.request(f"/api/v1/agents/{agent}/agent_installations/kinds")


class AgentAgentToolResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(self, agent: str, *, kind: str | None = None) -> AgentToolListResponse:
        query: dict[str, object] = {}
        if kind is not None:
            query["kind"] = kind
        return await self._http.request(f"/api/v1/agents/{agent}/agent_tools", query=query)

    async def create(self, agent: str, input: AgentAgentToolCreateInput) -> AgentTool:
        return await self._http.request(
            f"/api/v1/agents/{agent}/agent_tools",
            method="POST",
            body=input,
        )


class ScheduleResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(self, agent: str, *, status: str | None = None) -> ScheduleListResponse:
        query: dict[str, object] = {}
        if status is not None:
            query["status"] = status
        return await self._http.request(f"/api/v1/agents/{agent}/schedules", query=query)

    async def get(self, agent: str, schedule: str) -> AgentSchedule:
        return await self._http.request(f"/api/v1/agents/{agent}/schedules/{schedule}")


class AgentResource:
    def __init__(self, http: HttpClient):
        self._http = http
        self.agent_computers = AgentAgentComputerResource(http)
        self.agent_installations = AgentAgentInstallationResource(http)
        self.agent_tools = AgentAgentToolResource(http)
        self.schedules = ScheduleResource(http)

    async def list(
        self,
        *,
        page: int | None = None,
        page_size: int | None = None,
        search: str | None = None,
        user: str | None = None,
    ) -> AgentListResponse:
        query: dict[str, object] = {}
        if page is not None:
            query["page"] = page
        if page_size is not None:
            query["pageSize"] = page_size
        if search is not None:
            query["search"] = search
        if user is not None:
            query["user"] = user
        return await self._http.request("/api/v1/agents", query=query)

    async def create(self, input: AgentCreateInput) -> Agent:
        return await self._http.request("/api/v1/agents", method="POST", body=input)

    async def delete(self, agent: str) -> None:
        await self._http.request(f"/api/v1/agents/{agent}", method="DELETE")

    async def get(self, agent: str) -> Agent:
        return await self._http.request(f"/api/v1/agents/{agent}")

    async def update(self, agent: str, input: AgentUpdateInput) -> Agent:
        return await self._http.request(f"/api/v1/agents/{agent}", method="PATCH", body=input)

    async def agent_routines(self, agent: str, input: AgentAgentRoutinesInput) -> AgentRoutine:
        return await self._http.request(
            f"/api/v1/agents/{agent}/agent_routines",
            method="POST",
            body=input,
        )

    async def agent_working_memory(
        self,
        agent: str,
        *,
        page: int | None = None,
        page_size: int | None = None,
        search: str | None = None,
    ) -> WorkingMemoryEntryListResponse:
        query: dict[str, object] = {}
        if page is not None:
            query["page"] = page
        if page_size is not None:
            query["pageSize"] = page_size
        if search is not None:
            query["search"] = search
        return await self._http.request(f"/api/v1/agents/{agent}/agent_working_memory", query=query)

    async def export(self, agent: str) -> AgentExport:
        """
        Export agent as AgentTemplate
        Reconstructs an AgentTemplate config from a deployed agent and its sub-resources
        (tools, routines, skills, installations). Returns the template plus all dependent
        config files (scripts, workflows, skills, schemas) with their raw content for a
        fully self-contained export.
        """
        return await self._http.request(f"/api/v1/agents/{agent}/export")

    async def search(self, agent: str, input: AgentSearchInput) -> AgentSearchResponse:
        return await self._http.request(f"/api/v1/agents/{agent}/search", method="POST", body=input)

    async def threads(self, agent: str, input: AgentThreadsInput) -> Thread:
        return await self._http.request(
            f"/api/v1/agents/{agent}/threads",
            method="POST",
            body=input,
        )
