# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 12e45a765fbf

from __future__ import annotations

from ...runtime.http_client import HttpClient
from ...types.common import AgentHealthAction


class AgentHealthActionResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def get(self, health_action: str) -> AgentHealthAction:
        return await self._http.request(f"/api/v1/agent_health_actions/{health_action}")

    async def verify(self, health_action: str) -> AgentHealthAction:
        return await self._http.request(
            f"/api/v1/agent_health_actions/{health_action}/verify",
            method="POST",
        )
