# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 3e91531f101a

from __future__ import annotations

import builtins

from ...runtime.http_client import HttpClient, SyncHttpClient
from ...types.common import AgentRoutineRunListResponse


class AsyncAgentRoutineRunResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(
        self,
        *,
        agent: builtins.list[str] | None = None,
        status: str | None = None,
        limit: int | None = None,
        before_cursor: str | None = None,
        after_cursor: str | None = None,
    ) -> AgentRoutineRunListResponse:
        """
        List agent routine runs
        Returns a paginated list of agent routine runs across all routines visible to
        the authenticated app scope. Results are ordered by creation time descending
        (most recent first).
        Use the `agent` parameter to filter runs to one or more specific agents. Use
        `status` to narrow results to runs in a particular state. Pagination is
        bidirectional: supply `after_cursor` to page forward through newer runs or
        `before_cursor` to page backward through older runs.
        This endpoint requires an app scope. Requests without a valid app credential
        return 403.

        Args:
            agent: Filter by one or more agent IDs (`agi_...`) or `lookup_key` values. Repeat the parameter (e.g. `?agent[]=agi_a&agent[]=agi_b`) to OR multiple agents. Omit to return runs for all agents.
            status: Filter by run status. One of `"pending"`, `"running"`, `"completed"`, `"failed"`, `"skipped"`, or `"cancelled"`. Omit to return runs in any status.
            limit: Maximum number of runs to return. Defaults to 50; maximum is 100.
            before_cursor: Opaque cursor from a previous response's `before_cursor` field. Returns the page of runs older than that cursor position.
            after_cursor: Opaque cursor from a previous response's `after_cursor` field. Returns the page of runs newer than that cursor position.

        Returns:
            Paginated list of agent routine runs.
        """
        query: dict[str, object] = {}
        if agent is not None:
            query["agent"] = agent
        if status is not None:
            query["status"] = status
        if limit is not None:
            query["limit"] = limit
        if before_cursor is not None:
            query["before_cursor"] = before_cursor
        if after_cursor is not None:
            query["after_cursor"] = after_cursor
        return await self._http.request(
            "/api/v1/agent_routine_runs",
            query=query,
            response_type=AgentRoutineRunListResponse,
        )


class AgentRoutineRunResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def list(
        self,
        *,
        agent: builtins.list[str] | None = None,
        status: str | None = None,
        limit: int | None = None,
        before_cursor: str | None = None,
        after_cursor: str | None = None,
    ) -> AgentRoutineRunListResponse:
        """
        List agent routine runs
        Returns a paginated list of agent routine runs across all routines visible to
        the authenticated app scope. Results are ordered by creation time descending
        (most recent first).
        Use the `agent` parameter to filter runs to one or more specific agents. Use
        `status` to narrow results to runs in a particular state. Pagination is
        bidirectional: supply `after_cursor` to page forward through newer runs or
        `before_cursor` to page backward through older runs.
        This endpoint requires an app scope. Requests without a valid app credential
        return 403.

        Args:
            agent: Filter by one or more agent IDs (`agi_...`) or `lookup_key` values. Repeat the parameter (e.g. `?agent[]=agi_a&agent[]=agi_b`) to OR multiple agents. Omit to return runs for all agents.
            status: Filter by run status. One of `"pending"`, `"running"`, `"completed"`, `"failed"`, `"skipped"`, or `"cancelled"`. Omit to return runs in any status.
            limit: Maximum number of runs to return. Defaults to 50; maximum is 100.
            before_cursor: Opaque cursor from a previous response's `before_cursor` field. Returns the page of runs older than that cursor position.
            after_cursor: Opaque cursor from a previous response's `after_cursor` field. Returns the page of runs newer than that cursor position.

        Returns:
            Paginated list of agent routine runs.
        """
        query: dict[str, object] = {}
        if agent is not None:
            query["agent"] = agent
        if status is not None:
            query["status"] = status
        if limit is not None:
            query["limit"] = limit
        if before_cursor is not None:
            query["before_cursor"] = before_cursor
        if after_cursor is not None:
            query["after_cursor"] = after_cursor
        return self._http.request(
            "/api/v1/agent_routine_runs",
            query=query,
            response_type=AgentRoutineRunListResponse,
        )
