# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 8801f42e28cb

from __future__ import annotations

from ...runtime.http_client import HttpClient
from ...types.artifacts import Artifact


class ArtifactResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def delete(self, artifact: str) -> None:
        await self._http.request(f"/api/v1/artifacts/{artifact}", method="DELETE")

    async def get(self, artifact: str) -> Artifact:
        return await self._http.request(f"/api/v1/artifacts/{artifact}")

    async def replace(self, artifact: str, input: dict) -> Artifact:
        return await self._http.request(f"/api/v1/artifacts/{artifact}", method="PUT", body=input)

    async def archive(self, artifact: str) -> None:
        await self._http.request(f"/api/v1/artifacts/{artifact}/archive", method="POST")

    async def content(self, artifact: str, **params) -> dict[str, str]:
        return await self._http.request_raw(f"/api/v1/artifacts/{artifact}/content", query=params)
