# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: b17ebd7df67f

from __future__ import annotations

from typing import Any, TypedDict

from ...runtime.http_client import HttpClient, SyncHttpClient
from ...types.automations import AutomationRun


class AutomationInvokeInput(TypedDict, total=False):
    "Invoke an automation"

    idempotency_key: str | None
    "Unique key to deduplicate concurrent or retried invocations. A second request with the same key returns the existing run instead of creating a new one."
    payload: dict[str, Any] | None
    "Arbitrary input data passed to the automation. Validated against the automation's `input_schema` when one is configured; the request is rejected with 422 if validation fails."


class AsyncAutomationResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def invoke(self, automation: str, input: AutomationInvokeInput) -> AutomationRun:
        """
        Invoke an automation
        Triggers a single run of an automation that has `type: "invoked"`. Returns
        the resulting automation run object, which you can use to poll or display
        run status.
        Both server-to-server (secret key) and user (publishable key + JWT) auth
        are supported. The automation's `invoke_auth` setting controls which auth
        modes are accepted; requests using an unsupported mode are rejected with
        403. For server-to-server callers the run executes under the identity
        configured in the automation's `run_as_user` or `run_as_agent` fields. For
        authenticated user callers the invoking user's identity is used
        automatically.
        If you supply an `idempotency_key`, a second request with the same key
        returns the existing run rather than creating a new one.

        Args:
            automation: Automation ID (`auto_...`) or `lookup_key` of the automation to invoke.
            input: Request body.
            input.idempotency_key: Unique key to deduplicate concurrent or retried invocations. A second request with the same key returns the existing run instead of creating a new one.
            input.payload: Arbitrary input data passed to the automation. Validated against the automation's `input_schema` when one is configured; the request is rejected with 422 if validation fails.

        Returns:
            The automation run created by this invocation.
        """
        return await self._http.request(
            f"/api/v1/automations/{automation}/invoke",
            method="POST",
            body=input,
            response_type=AutomationRun,
        )


class AutomationResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def invoke(self, automation: str, input: AutomationInvokeInput) -> AutomationRun:
        """
        Invoke an automation
        Triggers a single run of an automation that has `type: "invoked"`. Returns
        the resulting automation run object, which you can use to poll or display
        run status.
        Both server-to-server (secret key) and user (publishable key + JWT) auth
        are supported. The automation's `invoke_auth` setting controls which auth
        modes are accepted; requests using an unsupported mode are rejected with
        403. For server-to-server callers the run executes under the identity
        configured in the automation's `run_as_user` or `run_as_agent` fields. For
        authenticated user callers the invoking user's identity is used
        automatically.
        If you supply an `idempotency_key`, a second request with the same key
        returns the existing run rather than creating a new one.

        Args:
            automation: Automation ID (`auto_...`) or `lookup_key` of the automation to invoke.
            input: Request body.
            input.idempotency_key: Unique key to deduplicate concurrent or retried invocations. A second request with the same key returns the existing run instead of creating a new one.
            input.payload: Arbitrary input data passed to the automation. Validated against the automation's `input_schema` when one is configured; the request is rejected with 422 if validation fails.

        Returns:
            The automation run created by this invocation.
        """
        return self._http.request(
            f"/api/v1/automations/{automation}/invoke",
            method="POST",
            body=input,
            response_type=AutomationRun,
        )
