# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 82a9bcbdd6c6

from __future__ import annotations

from typing import Any, Required, TypedDict

from ...runtime.http_client import HttpClient, SyncHttpClient
from ...types.common import BugReport


class BugReportCreateInput(TypedDict, total=False):
    "Submit a bug report"

    client: Required[str]
    'Identifier of the submitting client. One of `"agent_network_web"`, `"cli"`, or `"developer_portal"`.'
    client_version: Required[str]
    "Build SHA or package version of the client."
    context: dict[str, Any] | None
    "Optional client-shaped context blob; 5 KB serialized. Stored verbatim and surfaced for triage clients commonly include url, user_agent, thread_id, message_id, etc."
    description: Required[str]
    "Freeform report text. 1 10,000 chars after trim."


class AsyncBugReportResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def create(self, input: BugReportCreateInput) -> BugReport:
        """
        Submit a bug report
        Creates a bug report or freeform feedback entry on behalf of the authenticated user.
        The `description` is stored in full; the `context` blob is stored verbatim and surfaced
        during triage. Callers should include relevant session identifiers (URL, thread ID, etc.)
        in `context` to speed up reproduction.
        This endpoint requires authentication. Submissions are rate-limited to 10 reports per
        user per hour; exceeding that limit returns 429. The `client` value must be one of the
        recognised string identifiers listed below an unrecognised value returns 400.

        Args:
            input: Request body.
            input.client: Identifier of the submitting client. One of `"agent_network_web"`, `"cli"`, or `"developer_portal"`.
            input.client_version: Build SHA or package version of the client.
            input.context: Optional client-shaped context blob; 5 KB serialized. Stored verbatim and surfaced for triage clients commonly include url, user_agent, thread_id, message_id, etc.
            input.description: Freeform report text. 1 10,000 chars after trim.

        Returns:
            The created bug report record.
        """
        return await self._http.request(
            "/api/v1/bug_reports",
            method="POST",
            body=input,
            response_type=BugReport,
        )


class BugReportResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def create(self, input: BugReportCreateInput) -> BugReport:
        """
        Submit a bug report
        Creates a bug report or freeform feedback entry on behalf of the authenticated user.
        The `description` is stored in full; the `context` blob is stored verbatim and surfaced
        during triage. Callers should include relevant session identifiers (URL, thread ID, etc.)
        in `context` to speed up reproduction.
        This endpoint requires authentication. Submissions are rate-limited to 10 reports per
        user per hour; exceeding that limit returns 429. The `client` value must be one of the
        recognised string identifiers listed below an unrecognised value returns 400.

        Args:
            input: Request body.
            input.client: Identifier of the submitting client. One of `"agent_network_web"`, `"cli"`, or `"developer_portal"`.
            input.client_version: Build SHA or package version of the client.
            input.context: Optional client-shaped context blob; 5 KB serialized. Stored verbatim and surfaced for triage clients commonly include url, user_agent, thread_id, message_id, etc.
            input.description: Freeform report text. 1 10,000 chars after trim.

        Returns:
            The created bug report record.
        """
        return self._http.request(
            "/api/v1/bug_reports",
            method="POST",
            body=input,
            response_type=BugReport,
        )
