# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: c5a3abd0b2ab

from __future__ import annotations

import builtins
from datetime import datetime
from typing import Any, Required, TypedDict

from pydantic import BaseModel, Field

from ...runtime.http_client import HttpClient, SyncHttpClient
from ...types.common import CustomObject, CustomObjectListResponse


class CustomObjectCreateInput(TypedDict, total=False):
    "Create a custom object"

    agent: str | None
    "Agent user ID to set as the object owner. Used when neither `team` nor `user` is supplied."
    fields: Required[dict[str, Any]]
    "Key-value map of field values for the new object. Must conform to the schema's field definitions."
    org: str | None
    "Organization ID (`org_...`) to associate with the object. Typically required for system-owned objects."
    system: bool | None
    "When `true`, creates a system-owned object with no team, user, or agent owner. Requires elevated API credentials; returns 403 if the caller lacks permission."
    team: str | None
    "Team ID (`team_...`) to set as the object owner. When supplied, takes priority over `user` and `agent`."
    type: Required[str]
    "Schema type identifier (`lookup_key`) that defines the object's shape and validation rules."
    upsert: bool | None
    "When `true` and the schema declares a `row_key`, updates the existing object at that key for the same owner instead of returning 409 Conflict. Returns HTTP 200 on update and 201 on create."
    user: str | None
    "User ID (`user_...`) to set as the object owner. Used when neither `team` nor a higher-priority owner is set."


class CustomObjectReplaceInput(TypedDict, total=False):
    "Update a custom object"

    field_ops: dict[str, Any] | None
    "Granular array operations to apply per field (e.g. append, prepend, remove). A field must not appear in both `fields` and `field_ops`."
    fields: Required[dict[str, Any]]
    "Key-value map of field values to merge into the object. Only the supplied keys are affected."
    type: str | None
    "Schema type identifier (`lookup_key`) of the object. Optional; used for routing context only."


class CustomObjectDeleteResponse(BaseModel):
    """
    Successful response
    """

    deleted: bool = Field(..., description="Always `true` when the deletion succeeds.")
    id: str = Field(..., description="ID of the deleted custom object (`cobj_...`).")


class CustomObjectReplaceResponseData(BaseModel):
    created_at: datetime | None = Field(
        default=None, description="When the custom object was created (ISO 8601)."
    )
    fields: dict[str, Any] | None = Field(
        default=None,
        description="Map of field names to their current values as defined by the object's schema type.",
    )
    id: str = Field(..., description="Unique identifier for the custom object (`cobj_...`).")
    org: str | None = Field(
        default=None, description="ID of the organization this object belongs to (`org_...`)."
    )
    row_key: str | None = Field(
        default=None,
        description="An optional stable key used to identify this object by a caller-controlled string rather than its generated ID. `null` if not set.",
    )
    sandbox: str | None = Field(
        default=None,
        description="ID of the sandbox environment this object is scoped to (`dsb_...`). `null` for production objects.",
    )
    schema_type: str | None = Field(
        default=None,
        description="The lookup key of the schema type that defines this object's field structure. `null` if the schema type has not been set.",
    )
    team: str | None = Field(
        default=None,
        description="ID of the team that owns this object (`tem_...`). `null` if the object is not team-scoped.",
    )
    updated_at: datetime | None = Field(
        default=None,
        description="When the custom object was last modified (ISO 8601). `null` if the object has never been updated after creation.",
    )
    user: str | None = Field(
        default=None,
        description="ID of the user that owns this object (`usr_...`). `null` if the object is not user-scoped.",
    )
    version: int | None = Field(
        default=None,
        description="Optimistic concurrency version of the object. Increments with each successful update; pass this value in write operations to detect conflicting changes.",
    )


class CustomObjectReplaceResponse(BaseModel):
    """
    Successful response
    """

    data: CustomObjectReplaceResponseData = Field(
        ..., description="The custom object after the update has been applied."
    )
    meta: dict[str, Any] | None = Field(
        default=None, description="Version metadata for the updated object."
    )


class AsyncCustomObjectResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(
        self,
        type: str,
        *,
        row_key: str | None = None,
        sort_key: builtins.list[str] | None = None,
        team: builtins.list[str] | None = None,
        user: builtins.list[str] | None = None,
        agent: builtins.list[str] | None = None,
        org: builtins.list[str] | None = None,
        query: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
    ) -> CustomObjectListResponse:
        """
        List custom objects
        Returns a paginated list of custom objects of the given schema type that are
        visible to the authenticated viewer, ordered by creation time descending.
        Results span all ownership types (team-owned, user-owned, agent-owned, and
        system-owned) that the viewer has access to.
        Use the `row_key` param to perform an exact-match partition lookup. You may
        additionally supply `sort_key` to narrow within that partition `sort_key`
        requires `row_key` and the request returns 400 if `sort_key` is provided
        alone. Owner filters (`team`, `user`, `agent`, `org`) are additive: each
        accepts an array of IDs and returns objects matching any of the supplied
        values.
        When `query` is supplied, results are ranked by full-text relevance
        (descending `ts_rank`) rather than creation time.

        Args:
            type: Schema type identifier (`lookup_key`) to filter by. Only objects of this type are returned.
            row_key: Exact `row_key` value to match. When supplied, only objects with this partition key are returned.
            sort_key: One or more `sort_key` values to match within the `row_key` partition. Requires `row_key` to be set.
            team: One or more team IDs (`team_...`) to filter by owning team. Returns objects owned by any of the supplied teams.
            user: One or more user IDs (`user_...`) to filter by owning user. Returns objects owned by any of the supplied users.
            agent: One or more agent IDs to filter by owning agent. Returns objects owned by any of the supplied agents.
            org: One or more organization IDs (`org_...`) to filter by. Typically used by admins to query system-owned objects in a specific org.
            query: Full-text search string matched against the schema's configured search fields. When supplied, results are ordered by relevance score descending instead of creation time descending.
            page: Page number to retrieve (1-indexed). Defaults to `1`.
            page_size: Number of objects per page. Defaults to `25`; maximum is `100`.

        Returns:
            Paginated list of custom objects matching the supplied filters.
        """
        query: dict[str, object] = {}
        query["type"] = type
        if row_key is not None:
            query["row_key"] = row_key
        if sort_key is not None:
            query["sort_key"] = sort_key
        if team is not None:
            query["team"] = team
        if user is not None:
            query["user"] = user
        if agent is not None:
            query["agent"] = agent
        if org is not None:
            query["org"] = org
        if query is not None:
            query["query"] = query
        if page is not None:
            query["page"] = page
        if page_size is not None:
            query["page_size"] = page_size
        return await self._http.request(
            "/api/v1/custom_objects",
            query=query,
            response_type=CustomObjectListResponse,
        )

    async def create(self, input: CustomObjectCreateInput) -> CustomObject:
        """
        Create a custom object
        Creates a new custom object of the given schema type and returns the
        persisted object. The caller must be authenticated and authorized to create
        objects of the specified type.
        Owner resolution follows a priority order: if `team` is supplied the object
        is team-owned; if `user` is supplied it is owned by that user; if `agent` is
        supplied it is agent-owned; otherwise the object is owned by the authenticated
        user. Pass `system: true` explicitly to force system ownership this requires
        elevated API credentials and returns 403 if the caller lacks permission.
        If the schema declares a `row_key` (and optionally a `sort_key`), you may
        pass `upsert: true` to update an existing object at that key instead of
        receiving a 409 Conflict. The response status is `200` on an update and
        `201` on a new create.

        Args:
            input: Request body.
            input.agent: Agent user ID to set as the object owner. Used when neither `team` nor `user` is supplied.
            input.fields: Key-value map of field values for the new object. Must conform to the schema's field definitions.
            input.org: Organization ID (`org_...`) to associate with the object. Typically required for system-owned objects.
            input.system: When `true`, creates a system-owned object with no team, user, or agent owner. Requires elevated API credentials; returns 403 if the caller lacks permission.
            input.team: Team ID (`team_...`) to set as the object owner. When supplied, takes priority over `user` and `agent`.
            input.type: Schema type identifier (`lookup_key`) that defines the object's shape and validation rules.
            input.upsert: When `true` and the schema declares a `row_key`, updates the existing object at that key for the same owner instead of returning 409 Conflict. Returns HTTP 200 on update and 201 on create.
            input.user: User ID (`user_...`) to set as the object owner. Used when neither `team` nor a higher-priority owner is set.

        Returns:
            The created (or upserted) custom object.
        """
        return await self._http.request(
            "/api/v1/custom_objects",
            method="POST",
            body=input,
            response_type=CustomObject,
        )

    async def delete(self, object: str) -> CustomObjectDeleteResponse:
        """
        Delete a custom object
        Permanently deletes the custom object identified by `object`. The caller
        must be authenticated and have permission to delete the object.
        On success, returns a confirmation payload containing the deleted object's
        ID so callers can confirm the deletion without a follow-up fetch.
        Attempting to delete an object that does not exist or has already been
        deleted returns 404.

        Args:
            object: Custom object ID (`cobj_...`) of the object to delete.

        Returns:
            Successful response
        """
        return await self._http.request(
            f"/api/v1/custom_objects/{object}",
            method="DELETE",
            response_type=CustomObjectDeleteResponse,
        )

    async def get(self, object: str, *, type: str | None = None) -> CustomObject:
        """
        Retrieve a custom object
        Returns a single custom object identified by its ID. The authenticated viewer
        must have visibility access to the object.
        Returns 404 if the object does not exist, has been deleted, or is not
        visible to the viewer.

        Args:
            object: Custom object ID (`cobj_...`) to retrieve.
            type: Schema type identifier (`lookup_key`) of the object. Optional; used for routing context only.

        Returns:
            The requested custom object.
        """
        query: dict[str, object] = {}
        if type is not None:
            query["type"] = type
        return await self._http.request(
            f"/api/v1/custom_objects/{object}",
            query=query,
            response_type=CustomObject,
        )

    async def replace(
        self, object: str, input: CustomObjectReplaceInput
    ) -> CustomObjectReplaceResponse:
        """
        Update a custom object
        Updates the fields of an existing custom object and returns the updated
        object along with its new version number. The authenticated viewer must have
        permission to modify the object.
        You may supply `fields` (a full or partial key-value map to merge into the
        object), `field_ops` (granular array operations per field), or both but
        the same field name must not appear in both, which returns 422. Returns 404
        if the object does not exist or has been deleted.

        Args:
            object: Custom object ID (`cobj_...`) to update.
            input: Request body.
            input.field_ops: Granular array operations to apply per field (e.g. append, prepend, remove). A field must not appear in both `fields` and `field_ops`.
            input.fields: Key-value map of field values to merge into the object. Only the supplied keys are affected.
            input.type: Schema type identifier (`lookup_key`) of the object. Optional; used for routing context only.

        Returns:
            Successful response
        """
        return await self._http.request(
            f"/api/v1/custom_objects/{object}",
            method="PUT",
            body=input,
            response_type=CustomObjectReplaceResponse,
        )


class CustomObjectResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def list(
        self,
        type: str,
        *,
        row_key: str | None = None,
        sort_key: builtins.list[str] | None = None,
        team: builtins.list[str] | None = None,
        user: builtins.list[str] | None = None,
        agent: builtins.list[str] | None = None,
        org: builtins.list[str] | None = None,
        query: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
    ) -> CustomObjectListResponse:
        """
        List custom objects
        Returns a paginated list of custom objects of the given schema type that are
        visible to the authenticated viewer, ordered by creation time descending.
        Results span all ownership types (team-owned, user-owned, agent-owned, and
        system-owned) that the viewer has access to.
        Use the `row_key` param to perform an exact-match partition lookup. You may
        additionally supply `sort_key` to narrow within that partition `sort_key`
        requires `row_key` and the request returns 400 if `sort_key` is provided
        alone. Owner filters (`team`, `user`, `agent`, `org`) are additive: each
        accepts an array of IDs and returns objects matching any of the supplied
        values.
        When `query` is supplied, results are ranked by full-text relevance
        (descending `ts_rank`) rather than creation time.

        Args:
            type: Schema type identifier (`lookup_key`) to filter by. Only objects of this type are returned.
            row_key: Exact `row_key` value to match. When supplied, only objects with this partition key are returned.
            sort_key: One or more `sort_key` values to match within the `row_key` partition. Requires `row_key` to be set.
            team: One or more team IDs (`team_...`) to filter by owning team. Returns objects owned by any of the supplied teams.
            user: One or more user IDs (`user_...`) to filter by owning user. Returns objects owned by any of the supplied users.
            agent: One or more agent IDs to filter by owning agent. Returns objects owned by any of the supplied agents.
            org: One or more organization IDs (`org_...`) to filter by. Typically used by admins to query system-owned objects in a specific org.
            query: Full-text search string matched against the schema's configured search fields. When supplied, results are ordered by relevance score descending instead of creation time descending.
            page: Page number to retrieve (1-indexed). Defaults to `1`.
            page_size: Number of objects per page. Defaults to `25`; maximum is `100`.

        Returns:
            Paginated list of custom objects matching the supplied filters.
        """
        query: dict[str, object] = {}
        query["type"] = type
        if row_key is not None:
            query["row_key"] = row_key
        if sort_key is not None:
            query["sort_key"] = sort_key
        if team is not None:
            query["team"] = team
        if user is not None:
            query["user"] = user
        if agent is not None:
            query["agent"] = agent
        if org is not None:
            query["org"] = org
        if query is not None:
            query["query"] = query
        if page is not None:
            query["page"] = page
        if page_size is not None:
            query["page_size"] = page_size
        return self._http.request(
            "/api/v1/custom_objects",
            query=query,
            response_type=CustomObjectListResponse,
        )

    def create(self, input: CustomObjectCreateInput) -> CustomObject:
        """
        Create a custom object
        Creates a new custom object of the given schema type and returns the
        persisted object. The caller must be authenticated and authorized to create
        objects of the specified type.
        Owner resolution follows a priority order: if `team` is supplied the object
        is team-owned; if `user` is supplied it is owned by that user; if `agent` is
        supplied it is agent-owned; otherwise the object is owned by the authenticated
        user. Pass `system: true` explicitly to force system ownership this requires
        elevated API credentials and returns 403 if the caller lacks permission.
        If the schema declares a `row_key` (and optionally a `sort_key`), you may
        pass `upsert: true` to update an existing object at that key instead of
        receiving a 409 Conflict. The response status is `200` on an update and
        `201` on a new create.

        Args:
            input: Request body.
            input.agent: Agent user ID to set as the object owner. Used when neither `team` nor `user` is supplied.
            input.fields: Key-value map of field values for the new object. Must conform to the schema's field definitions.
            input.org: Organization ID (`org_...`) to associate with the object. Typically required for system-owned objects.
            input.system: When `true`, creates a system-owned object with no team, user, or agent owner. Requires elevated API credentials; returns 403 if the caller lacks permission.
            input.team: Team ID (`team_...`) to set as the object owner. When supplied, takes priority over `user` and `agent`.
            input.type: Schema type identifier (`lookup_key`) that defines the object's shape and validation rules.
            input.upsert: When `true` and the schema declares a `row_key`, updates the existing object at that key for the same owner instead of returning 409 Conflict. Returns HTTP 200 on update and 201 on create.
            input.user: User ID (`user_...`) to set as the object owner. Used when neither `team` nor a higher-priority owner is set.

        Returns:
            The created (or upserted) custom object.
        """
        return self._http.request(
            "/api/v1/custom_objects",
            method="POST",
            body=input,
            response_type=CustomObject,
        )

    def delete(self, object: str) -> CustomObjectDeleteResponse:
        """
        Delete a custom object
        Permanently deletes the custom object identified by `object`. The caller
        must be authenticated and have permission to delete the object.
        On success, returns a confirmation payload containing the deleted object's
        ID so callers can confirm the deletion without a follow-up fetch.
        Attempting to delete an object that does not exist or has already been
        deleted returns 404.

        Args:
            object: Custom object ID (`cobj_...`) of the object to delete.

        Returns:
            Successful response
        """
        return self._http.request(
            f"/api/v1/custom_objects/{object}",
            method="DELETE",
            response_type=CustomObjectDeleteResponse,
        )

    def get(self, object: str, *, type: str | None = None) -> CustomObject:
        """
        Retrieve a custom object
        Returns a single custom object identified by its ID. The authenticated viewer
        must have visibility access to the object.
        Returns 404 if the object does not exist, has been deleted, or is not
        visible to the viewer.

        Args:
            object: Custom object ID (`cobj_...`) to retrieve.
            type: Schema type identifier (`lookup_key`) of the object. Optional; used for routing context only.

        Returns:
            The requested custom object.
        """
        query: dict[str, object] = {}
        if type is not None:
            query["type"] = type
        return self._http.request(
            f"/api/v1/custom_objects/{object}",
            query=query,
            response_type=CustomObject,
        )

    def replace(self, object: str, input: CustomObjectReplaceInput) -> CustomObjectReplaceResponse:
        """
        Update a custom object
        Updates the fields of an existing custom object and returns the updated
        object along with its new version number. The authenticated viewer must have
        permission to modify the object.
        You may supply `fields` (a full or partial key-value map to merge into the
        object), `field_ops` (granular array operations per field), or both but
        the same field name must not appear in both, which returns 422. Returns 404
        if the object does not exist or has been deleted.

        Args:
            object: Custom object ID (`cobj_...`) to update.
            input: Request body.
            input.field_ops: Granular array operations to apply per field (e.g. append, prepend, remove). A field must not appear in both `fields` and `field_ops`.
            input.fields: Key-value map of field values to merge into the object. Only the supplied keys are affected.
            input.type: Schema type identifier (`lookup_key`) of the object. Optional; used for routing context only.

        Returns:
            Successful response
        """
        return self._http.request(
            f"/api/v1/custom_objects/{object}",
            method="PUT",
            body=input,
            response_type=CustomObjectReplaceResponse,
        )
