# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 3fac1fdb8135

from __future__ import annotations

from ...runtime.http_client import HttpClient
from ...types.common import CustomObject


class CustomObjectResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def delete(self, object: str) -> None:
        await self._http.request(f"/api/v1/custom_objects/{object}", method="DELETE")

    async def get(self, object: str, **params) -> CustomObject:
        return await self._http.request(f"/api/v1/custom_objects/{object}", query=params)

    async def replace(self, object: str, input: dict) -> dict[str, object]:
        return await self._http.request(
            f"/api/v1/custom_objects/{object}",
            method="PUT",
            body=input,
        )
