# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: ee8786d0c9ca

from __future__ import annotations

from typing import Literal, Required, TypedDict

from ...runtime.http_client import HttpClient, SyncHttpClient
from ...types.common import (
    EventSubscription,
    EventSubscriptionClaim,
    EventSubscriptionHead,
    EventSubscriptionPage,
    EventSubscriptionQueue,
)


class EventSubscriptionCreateInput(TypedDict, total=False):
    "Create a domain-event subscription"

    event_names: Required[list[str]]
    "Exact event names to receive."
    max_pending_events: int | None
    "Queue cap. Defaults to 100; maximum 1000."
    name: Required[str]
    "Customer-defined subscription name."
    retention_seconds: int | None
    "Delivery retention in seconds. Defaults to 86400 (24 hours); between 7200 and 2592000. Applies to future deliveries only."
    status: Literal["active", "paused"] | None
    "Initial status. Defaults to active."
    visibility_timeout_seconds: int | None
    "Default claim lease in seconds. Defaults to 300."


class EventSubscriptionUpdateInput(TypedDict, total=False):
    "Update a domain-event subscription"

    event_names: list[str] | None
    max_pending_events: int | None
    name: str | None
    retention_seconds: int | None
    "Delivery retention in seconds. Defaults to 86400 (24 hours); between 7200 and 2592000. Applies to future deliveries only."
    status: Literal["active", "paused"] | None
    visibility_timeout_seconds: int | None


class EventSubscriptionClaimInput(TypedDict, total=False):
    "Claim events from a subscription"

    consumer_id: str | None
    "Consumer identity between 1 and 128 bytes, recorded on the lease for attribution."
    max_events: int | None
    "Opts into batch mode: leases up to this many lease-available deliveries (between 1 and 20) in sequence order, skipping leased entries instead of blocking on the head. Omit to keep strict head-of-line semantics."
    request_id: str | None
    "Idempotency key between 1 and 128 bytes. Use a value unique per claim attempt (e.g. a UUID) the key is scoped to the subscription, so a reused value takes over whatever leases it last stamped. Retrying a claim with the same request_id while its leases are unexpired returns the same deliveries (regardless of max_events) with fresh receipt handles and refreshed leases."
    visibility_timeout_seconds: int | None
    "Lease duration override between 15 and 3600 seconds."
    wait_seconds: int | None
    "Long-poll bound between 0 and 20 seconds. When the queue is empty, the request waits up to this long for a delivery before returning an empty data array. 0 (or omitting) returns immediately."


class AsyncEventSubscriptionResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(
        self, *, page: int | None = None, per_page: int | None = None
    ) -> EventSubscriptionPage:
        """
        List domain-event subscriptions
        Lists the subscriptions visible to the caller, with current queue counters.

        Args:
            page: Page number, starting at 1.
            per_page: Subscriptions per page, from 1 through 100.

        Returns:
            Subscriptions visible to this caller.
        """
        query: dict[str, object] = {}
        if page is not None:
            query["page"] = page
        if per_page is not None:
            query["per_page"] = per_page
        return await self._http.request(
            "/api/v1/event_subscriptions",
            query=query,
            response_type=EventSubscriptionPage,
        )

    async def create(self, input: EventSubscriptionCreateInput) -> EventSubscription:
        """
        Create a domain-event subscription
        Creates a durable subscription that receives exportable domain events matching its exact event names. Matching events fan out into a per-subscription queue bounded by max_pending_events and retention_seconds; consume with claim and acknowledge.

        Args:
            input: Request body.
            input.event_names: Exact event names to receive.
            input.max_pending_events: Queue cap. Defaults to 100; maximum 1000.
            input.name: Customer-defined subscription name.
            input.retention_seconds: Delivery retention in seconds. Defaults to 86400 (24 hours); between 7200 and 2592000. Applies to future deliveries only.
            input.status: Initial status. Defaults to active.
            input.visibility_timeout_seconds: Default claim lease in seconds. Defaults to 300.

        Returns:
            The new volatile subscription.
        """
        return await self._http.request(
            "/api/v1/event_subscriptions",
            method="POST",
            body=input,
            response_type=EventSubscription,
        )

    async def delete(self, subscription: str) -> None:
        """
        Delete a domain-event subscription
        Deletes the subscription and every delivery still in its queue.

        Args:
            subscription: Subscription ID (`esub_...`).

        Returns:
            No content
        """
        await self._http.request(f"/api/v1/event_subscriptions/{subscription}", method="DELETE")

    async def get(self, subscription: str) -> EventSubscription:
        """
        Get a domain-event subscription
        Returns one subscription and its current queue counters.

        Args:
            subscription: Subscription ID (`esub_...`).

        Returns:
            Successful response
        """
        return await self._http.request(
            f"/api/v1/event_subscriptions/{subscription}",
            response_type=EventSubscription,
        )

    async def update(
        self, subscription: str, input: EventSubscriptionUpdateInput
    ) -> EventSubscription:
        """
        Update a domain-event subscription
        Updates matching, status, or queue limits for future fanout. Already queued deliveries remain unless a lower cap trims the oldest entries; retention changes apply to future deliveries only.

        Args:
            subscription: Subscription ID (`esub_...`).
            input: Request body.
            input.retention_seconds: Delivery retention in seconds. Defaults to 86400 (24 hours); between 7200 and 2592000. Applies to future deliveries only.

        Returns:
            Successful response
        """
        return await self._http.request(
            f"/api/v1/event_subscriptions/{subscription}",
            method="PATCH",
            body=input,
            response_type=EventSubscription,
        )

    async def claim(
        self, subscription: str, input: EventSubscriptionClaimInput
    ) -> EventSubscriptionClaim:
        """
        Claim events from a subscription
        Atomically leases the oldest unacknowledged delivery. Returns an empty data array when the queue is empty or its head already has an active lease. Passing max_events opts into batch mode, where leased entries are skipped instead of blocking; wait_seconds bounds a long poll on an empty queue.

        Args:
            subscription: Subscription ID (`esub_...`).
            input: Request body.
            input.consumer_id: Consumer identity between 1 and 128 bytes, recorded on the lease for attribution.
            input.max_events: Opts into batch mode: leases up to this many lease-available deliveries (between 1 and 20) in sequence order, skipping leased entries instead of blocking on the head. Omit to keep strict head-of-line semantics.
            input.request_id: Idempotency key between 1 and 128 bytes. Use a value unique per claim attempt (e.g. a UUID) the key is scoped to the subscription, so a reused value takes over whatever leases it last stamped. Retrying a claim with the same request_id while its leases are unexpired returns the same deliveries (regardless of max_events) with fresh receipt handles and refreshed leases.
            input.visibility_timeout_seconds: Lease duration override between 15 and 3600 seconds.
            input.wait_seconds: Long-poll bound between 0 and 20 seconds. When the queue is empty, the request waits up to this long for a delivery before returning an empty data array. 0 (or omitting) returns immediately.

        Returns:
            Successful response
        """
        return await self._http.request(
            f"/api/v1/event_subscriptions/{subscription}/claim",
            method="POST",
            body=input,
            response_type=EventSubscriptionClaim,
        )

    async def head(self, subscription: str) -> EventSubscriptionHead:
        """
        Peek at the head of a subscription queue
        Returns the oldest unacknowledged delivery without reserving it. This diagnostic read cannot be used as a safe substitute for claim.

        Args:
            subscription: Subscription ID (`esub_...`).

        Returns:
            Successful response
        """
        return await self._http.request(
            f"/api/v1/event_subscriptions/{subscription}/head",
            response_type=EventSubscriptionHead,
        )

    async def queue(
        self,
        subscription: str,
        *,
        limit: int | None = None,
        before_cursor: str | None = None,
        after_cursor: str | None = None,
    ) -> EventSubscriptionQueue:
        """
        Read a subscription queue
        Returns a non-reserving, oldest-first view of unacknowledged deliveries, including the queue's loss indicators (queue_epoch, dropped_events_total, dropped_through_position). Use claim to obtain a receipt handle before acknowledging.

        Args:
            subscription: Subscription ID (`esub_...`).
            limit: Maximum entries to return, from 1 through 100.
            before_cursor: Opaque cursor for the preceding page.
            after_cursor: Opaque cursor for the following page.

        Returns:
            Successful response
        """
        query: dict[str, object] = {}
        if limit is not None:
            query["limit"] = limit
        if before_cursor is not None:
            query["before_cursor"] = before_cursor
        if after_cursor is not None:
            query["after_cursor"] = after_cursor
        return await self._http.request(
            f"/api/v1/event_subscriptions/{subscription}/queue",
            query=query,
            response_type=EventSubscriptionQueue,
        )


class EventSubscriptionResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def list(
        self, *, page: int | None = None, per_page: int | None = None
    ) -> EventSubscriptionPage:
        """
        List domain-event subscriptions
        Lists the subscriptions visible to the caller, with current queue counters.

        Args:
            page: Page number, starting at 1.
            per_page: Subscriptions per page, from 1 through 100.

        Returns:
            Subscriptions visible to this caller.
        """
        query: dict[str, object] = {}
        if page is not None:
            query["page"] = page
        if per_page is not None:
            query["per_page"] = per_page
        return self._http.request(
            "/api/v1/event_subscriptions",
            query=query,
            response_type=EventSubscriptionPage,
        )

    def create(self, input: EventSubscriptionCreateInput) -> EventSubscription:
        """
        Create a domain-event subscription
        Creates a durable subscription that receives exportable domain events matching its exact event names. Matching events fan out into a per-subscription queue bounded by max_pending_events and retention_seconds; consume with claim and acknowledge.

        Args:
            input: Request body.
            input.event_names: Exact event names to receive.
            input.max_pending_events: Queue cap. Defaults to 100; maximum 1000.
            input.name: Customer-defined subscription name.
            input.retention_seconds: Delivery retention in seconds. Defaults to 86400 (24 hours); between 7200 and 2592000. Applies to future deliveries only.
            input.status: Initial status. Defaults to active.
            input.visibility_timeout_seconds: Default claim lease in seconds. Defaults to 300.

        Returns:
            The new volatile subscription.
        """
        return self._http.request(
            "/api/v1/event_subscriptions",
            method="POST",
            body=input,
            response_type=EventSubscription,
        )

    def delete(self, subscription: str) -> None:
        """
        Delete a domain-event subscription
        Deletes the subscription and every delivery still in its queue.

        Args:
            subscription: Subscription ID (`esub_...`).

        Returns:
            No content
        """
        self._http.request(f"/api/v1/event_subscriptions/{subscription}", method="DELETE")

    def get(self, subscription: str) -> EventSubscription:
        """
        Get a domain-event subscription
        Returns one subscription and its current queue counters.

        Args:
            subscription: Subscription ID (`esub_...`).

        Returns:
            Successful response
        """
        return self._http.request(
            f"/api/v1/event_subscriptions/{subscription}",
            response_type=EventSubscription,
        )

    def update(self, subscription: str, input: EventSubscriptionUpdateInput) -> EventSubscription:
        """
        Update a domain-event subscription
        Updates matching, status, or queue limits for future fanout. Already queued deliveries remain unless a lower cap trims the oldest entries; retention changes apply to future deliveries only.

        Args:
            subscription: Subscription ID (`esub_...`).
            input: Request body.
            input.retention_seconds: Delivery retention in seconds. Defaults to 86400 (24 hours); between 7200 and 2592000. Applies to future deliveries only.

        Returns:
            Successful response
        """
        return self._http.request(
            f"/api/v1/event_subscriptions/{subscription}",
            method="PATCH",
            body=input,
            response_type=EventSubscription,
        )

    def claim(
        self, subscription: str, input: EventSubscriptionClaimInput
    ) -> EventSubscriptionClaim:
        """
        Claim events from a subscription
        Atomically leases the oldest unacknowledged delivery. Returns an empty data array when the queue is empty or its head already has an active lease. Passing max_events opts into batch mode, where leased entries are skipped instead of blocking; wait_seconds bounds a long poll on an empty queue.

        Args:
            subscription: Subscription ID (`esub_...`).
            input: Request body.
            input.consumer_id: Consumer identity between 1 and 128 bytes, recorded on the lease for attribution.
            input.max_events: Opts into batch mode: leases up to this many lease-available deliveries (between 1 and 20) in sequence order, skipping leased entries instead of blocking on the head. Omit to keep strict head-of-line semantics.
            input.request_id: Idempotency key between 1 and 128 bytes. Use a value unique per claim attempt (e.g. a UUID) the key is scoped to the subscription, so a reused value takes over whatever leases it last stamped. Retrying a claim with the same request_id while its leases are unexpired returns the same deliveries (regardless of max_events) with fresh receipt handles and refreshed leases.
            input.visibility_timeout_seconds: Lease duration override between 15 and 3600 seconds.
            input.wait_seconds: Long-poll bound between 0 and 20 seconds. When the queue is empty, the request waits up to this long for a delivery before returning an empty data array. 0 (or omitting) returns immediately.

        Returns:
            Successful response
        """
        return self._http.request(
            f"/api/v1/event_subscriptions/{subscription}/claim",
            method="POST",
            body=input,
            response_type=EventSubscriptionClaim,
        )

    def head(self, subscription: str) -> EventSubscriptionHead:
        """
        Peek at the head of a subscription queue
        Returns the oldest unacknowledged delivery without reserving it. This diagnostic read cannot be used as a safe substitute for claim.

        Args:
            subscription: Subscription ID (`esub_...`).

        Returns:
            Successful response
        """
        return self._http.request(
            f"/api/v1/event_subscriptions/{subscription}/head",
            response_type=EventSubscriptionHead,
        )

    def queue(
        self,
        subscription: str,
        *,
        limit: int | None = None,
        before_cursor: str | None = None,
        after_cursor: str | None = None,
    ) -> EventSubscriptionQueue:
        """
        Read a subscription queue
        Returns a non-reserving, oldest-first view of unacknowledged deliveries, including the queue's loss indicators (queue_epoch, dropped_events_total, dropped_through_position). Use claim to obtain a receipt handle before acknowledging.

        Args:
            subscription: Subscription ID (`esub_...`).
            limit: Maximum entries to return, from 1 through 100.
            before_cursor: Opaque cursor for the preceding page.
            after_cursor: Opaque cursor for the following page.

        Returns:
            Successful response
        """
        query: dict[str, object] = {}
        if limit is not None:
            query["limit"] = limit
        if before_cursor is not None:
            query["before_cursor"] = before_cursor
        if after_cursor is not None:
            query["after_cursor"] = after_cursor
        return self._http.request(
            f"/api/v1/event_subscriptions/{subscription}/queue",
            query=query,
            response_type=EventSubscriptionQueue,
        )
