# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 0737f7cbe88e

from __future__ import annotations

from typing import Literal, Required, TypedDict

from ...runtime.http_client import HttpClient, SyncHttpClient
from ...types.extractions import Extraction


class ExtractionCreateInput(TypedDict, total=False):
    "Start an extraction"

    agent: str | None
    "Owning agent (`agt_...`) scopes the extraction and its outputs."
    destination_kind: Required[Literal["config", "storage"]]
    "Where outputs are written."
    destination_path: str | None
    "Destination virtual_path prefix. Required for `destination_kind=config`, where it must name at least one path segment (`.` and `..` segments are dropped)."
    file: str | None
    "Source file id (`fil_...`) for document extraction. Runs synchronously, so the source must be at most 10MB; larger files are rejected."
    max_pages: int | None
    "Crawl cap for `mode=site` must be at least 1 (defaults to 100; `link` is always 1)."
    mode: Literal["link", "site"] | None
    "Required with `url`. Document extraction is selected by `file` instead and takes no `mode` (its `kind` is `document`)."
    org: str | None
    "Owning organization (`org_...`). Defaults to the viewer's org."
    url: str | None
    "Source URL for link/site extraction."


class AsyncExtractionResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def create(self, input: ExtractionCreateInput) -> Extraction:
        """
        Start an extraction
        Records a text-extraction job for a document (`file`) or a URL (`url` + `mode`).
        The job is owner-scoped and tagged with the caller-supplied `destination`
        namespace, **without** committing knowledge to an agent (no embeddings, no
        agent attach).
        Exactly one of `file` or (`url` + `mode`) is required.
        Document extraction (`file`) runs synchronously: the response already
        reflects the final state (`done` with its output, or an error if extraction
        couldn't complete), status `201`. URL extraction (`url` + `mode`) submits an
        async crawl and returns immediately with state `running`, status `202`
        poll `GET /extractions/:extraction` for its terminal state.

        Args:
            input: Request body.
            input.agent: Owning agent (`agt_...`) scopes the extraction and its outputs.
            input.destination_kind: Where outputs are written.
            input.destination_path: Destination virtual_path prefix. Required for `destination_kind=config`, where it must name at least one path segment (`.` and `..` segments are dropped).
            input.file: Source file id (`fil_...`) for document extraction. Runs synchronously, so the source must be at most 10MB; larger files are rejected.
            input.max_pages: Crawl cap for `mode=site` must be at least 1 (defaults to 100; `link` is always 1).
            input.mode: Required with `url`. Document extraction is selected by `file` instead and takes no `mode` (its `kind` is `document`).
            input.org: Owning organization (`org_...`). Defaults to the viewer's org.
            input.url: Source URL for link/site extraction.

        Returns:
            The extraction job. Document extraction returns `201` with `state: "done"`; link/site extraction returns `202` with `state: "running"`.
        """
        return await self._http.request(
            "/api/v1/extractions",
            method="POST",
            body=input,
            response_type=Extraction,
        )

    async def get(self, extraction: str) -> Extraction:
        """
        Retrieve an extraction
        Returns a single extraction job and its current state. Poll this endpoint after
        starting an async (link/site) extraction until `state` is `done` or `failed`.
        An extraction that exists but is not visible to the current viewer returns `404`
        rather than `403`, so the resource's existence is not revealed.

        Args:
            extraction: Extraction ID (`ext_...`).

        Returns:
            The extraction job.
        """
        return await self._http.request(
            f"/api/v1/extractions/{extraction}",
            response_type=Extraction,
        )


class ExtractionResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def create(self, input: ExtractionCreateInput) -> Extraction:
        """
        Start an extraction
        Records a text-extraction job for a document (`file`) or a URL (`url` + `mode`).
        The job is owner-scoped and tagged with the caller-supplied `destination`
        namespace, **without** committing knowledge to an agent (no embeddings, no
        agent attach).
        Exactly one of `file` or (`url` + `mode`) is required.
        Document extraction (`file`) runs synchronously: the response already
        reflects the final state (`done` with its output, or an error if extraction
        couldn't complete), status `201`. URL extraction (`url` + `mode`) submits an
        async crawl and returns immediately with state `running`, status `202`
        poll `GET /extractions/:extraction` for its terminal state.

        Args:
            input: Request body.
            input.agent: Owning agent (`agt_...`) scopes the extraction and its outputs.
            input.destination_kind: Where outputs are written.
            input.destination_path: Destination virtual_path prefix. Required for `destination_kind=config`, where it must name at least one path segment (`.` and `..` segments are dropped).
            input.file: Source file id (`fil_...`) for document extraction. Runs synchronously, so the source must be at most 10MB; larger files are rejected.
            input.max_pages: Crawl cap for `mode=site` must be at least 1 (defaults to 100; `link` is always 1).
            input.mode: Required with `url`. Document extraction is selected by `file` instead and takes no `mode` (its `kind` is `document`).
            input.org: Owning organization (`org_...`). Defaults to the viewer's org.
            input.url: Source URL for link/site extraction.

        Returns:
            The extraction job. Document extraction returns `201` with `state: "done"`; link/site extraction returns `202` with `state: "running"`.
        """
        return self._http.request(
            "/api/v1/extractions",
            method="POST",
            body=input,
            response_type=Extraction,
        )

    def get(self, extraction: str) -> Extraction:
        """
        Retrieve an extraction
        Returns a single extraction job and its current state. Poll this endpoint after
        starting an async (link/site) extraction until `state` is `done` or `failed`.
        An extraction that exists but is not visible to the current viewer returns `404`
        rather than `403`, so the resource's existence is not revealed.

        Args:
            extraction: Extraction ID (`ext_...`).

        Returns:
            The extraction job.
        """
        return self._http.request(f"/api/v1/extractions/{extraction}", response_type=Extraction)
