# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 9081589966b0

from __future__ import annotations

from typing import Required, TypedDict

from ...runtime.http_client import HttpClient, SyncHttpClient
from ...types.common import StorageFile


class FileCreateInput(TypedDict, total=False):
    agent: str | None  # Agent ID — derives org_id from the agent
    content_type: Required[str]  # MIME type
    data: Required[str]  # Base64-encoded file content
    filename: Required[str]  # Filename
    org: str | None  # Organization ID
    team: str | None  # Owning team ID
    user: str | None  # Owning user ID


class AsyncFileResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def create(self, input: FileCreateInput) -> StorageFile:
        return await self._http.request("/api/v1/files", method="POST", body=input)

    async def avatar(self, file: str, token: str) -> dict[str, str]:
        query: dict[str, object] = {}
        query["token"] = token
        return await self._http.request_raw(f"/api/v1/files/{file}/avatar", query=query)


class FileResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def create(self, input: FileCreateInput) -> StorageFile:
        return self._http.request("/api/v1/files", method="POST", body=input)

    def avatar(self, file: str, token: str) -> dict[str, str]:
        query: dict[str, object] = {}
        query["token"] = token
        return self._http.request_raw(f"/api/v1/files/{file}/avatar", query=query)
