# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 83dbcfed81d9

from __future__ import annotations

from ...runtime.http_client import HttpClient


class InstallationSourceResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def delete(self, source: str) -> None:
        await self._http.request(f"/api/v1/installation_sources/{source}", method="DELETE")
