# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 1d9e7b93f5dd

from __future__ import annotations

from datetime import datetime
from typing import Literal, Required, TypedDict

from pydantic import BaseModel

from ...runtime.http_client import HttpClient
from ...types.common import ContextIngestion, KnowledgeSource, KnowledgeSourceKindListResponse


class KnowledgeSourceCreateInput(TypedDict, total=False):
    agent: str | None  # Agent ID (owner)
    metadata: dict[str, object] | None  # Additional metadata
    org: str | None  # Org ID — required for system-owned sources without a team/user/agent
    parent_source: str | None  # Parent source ID
    payload: dict[str, object] | None  # Type-specific configuration
    state: str | None  # State: active or paused (default: active)
    team: str | None  # Team ID (owner)
    thread: str | None  # Thread ID
    type: Required[str]
    user: str | None  # User ID (owner)


class KnowledgeSourceUpdateInput(TypedDict, total=False):
    metadata: dict[str, object] | None  # Additional metadata
    payload: dict[str, object] | None  # Type-specific configuration
    state: str | None  # State: active or paused


class KnowledgeSourceIngestInputContent(TypedDict, total=False):
    content_type: str | None  # MIME type
    data: Required[str]  # Content bytes (see `data_encoding`)
    data_encoding: str | None  # Encoding of `data`: "raw" (default) or "base64"
    filename: str | None  # Original filename


class KnowledgeSourceIngestInput(TypedDict, total=False):
    content: KnowledgeSourceIngestInputContent | None
    file: str | None
    metadata: dict[str, object] | None  # Per-document metadata
    pull: bool | None
    title: str | None  # Display title for the document


class KnowledgeSourceListResponseDataItem(BaseModel):
    agent: str | None = None  # Owning agent
    context_installation: str | None = None  # Associated installation
    created_at: datetime | None = None  # Created timestamp
    id: str  # Public ID (cso_...)
    metadata: dict[str, object] | None = None  # Additional metadata
    org: str | None = None  # Owning organization
    parent_source: str | None = None  # Parent source
    payload: dict[str, object] | None = None  # Type-specific configuration
    sandbox: str | None = None  # Owning sandbox
    state: str  # State: active or paused
    team: str | None = None  # Owning team
    thread: str | None = None  # Associated thread
    type: str  # Source type (e.g., gmail, github_activity)
    updated_at: datetime | None = None  # Updated timestamp
    user: str | None = None  # Owning user


class KnowledgeSourceListResponse(BaseModel):
    data: list[KnowledgeSourceListResponseDataItem]  # The sources
    has_next: bool  # Has next page
    has_prev: bool  # Has previous page
    page: int  # Current page
    page_size: int  # Results per page
    total_entries: int  # Total entries
    total_pages: int  # Total pages


class KnowledgeSourceKindResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def list(self) -> KnowledgeSourceKindListResponse:
        return await self._http.request("/api/v1/knowledge_sources/kinds")


class KnowledgeSourceResource:
    def __init__(self, http: HttpClient):
        self._http = http
        self.kinds = KnowledgeSourceKindResource(http)

    async def list(
        self,
        *,
        page: int | None = None,
        page_size: int | None = None,
        search: str | None = None,
        type: str | None = None,
        installation: str | None = None,
        agent: str | None = None,
        org: str | None = None,
        owner_scope: Literal["any", "individual", "system"] | None = None,
    ) -> KnowledgeSourceListResponse:
        query: dict[str, object] = {}
        if page is not None:
            query["page"] = page
        if page_size is not None:
            query["pageSize"] = page_size
        if search is not None:
            query["search"] = search
        if type is not None:
            query["type"] = type
        if installation is not None:
            query["installation"] = installation
        if agent is not None:
            query["agent"] = agent
        if org is not None:
            query["org"] = org
        if owner_scope is not None:
            query["ownerScope"] = owner_scope
        return await self._http.request("/api/v1/knowledge_sources", query=query)

    async def create(self, input: KnowledgeSourceCreateInput) -> KnowledgeSource:
        return await self._http.request("/api/v1/knowledge_sources", method="POST", body=input)

    async def delete(self, source: str) -> None:
        await self._http.request(f"/api/v1/knowledge_sources/{source}", method="DELETE")

    async def get(self, source: str) -> KnowledgeSource:
        return await self._http.request(f"/api/v1/knowledge_sources/{source}")

    async def update(self, source: str, input: KnowledgeSourceUpdateInput) -> KnowledgeSource:
        return await self._http.request(
            f"/api/v1/knowledge_sources/{source}",
            method="PATCH",
            body=input,
        )

    async def ingest(self, source: str, input: KnowledgeSourceIngestInput) -> ContextIngestion:
        return await self._http.request(
            f"/api/v1/knowledge_sources/{source}/ingest",
            method="POST",
            body=input,
        )
