# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 989841475bf8

from __future__ import annotations

from ...runtime.http_client import HttpClient, SyncHttpClient


class AsyncPrivateServiceDefinitionResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def get(self, app_id: str, private_service_id: str) -> str:
        """
        Download an enrolled private service definition
        Returns the canonical callable definition authorized by an enrollment token.

        Returns:
            Raw content
        """
        return await self._http.request(
            f"/api/v1/private_service_definitions/{app_id}/{private_service_id}",
        )


class PrivateServiceDefinitionResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def get(self, app_id: str, private_service_id: str) -> str:
        """
        Download an enrolled private service definition
        Returns the canonical callable definition authorized by an enrollment token.

        Returns:
            Raw content
        """
        return self._http.request(
            f"/api/v1/private_service_definitions/{app_id}/{private_service_id}",
        )
