# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 1e4635f05ba7

from __future__ import annotations

from ...runtime.http_client import HttpClient, SyncHttpClient


class AsyncSshKeyResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def delete(self, ssh_key: str) -> None:
        """
        Revoke an SSH public key
        Revokes an owned key immediately. The key remains visible as audit metadata.

        Args:
            ssh_key: Registered SSH key ID (`ssk_...`).

        Returns:
            No content
        """
        await self._http.request(f"/api/v1/ssh_keys/{ssh_key}", method="DELETE")


class SshKeyResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def delete(self, ssh_key: str) -> None:
        """
        Revoke an SSH public key
        Revokes an owned key immediately. The key remains visible as audit metadata.

        Args:
            ssh_key: Registered SSH key ID (`ssk_...`).

        Returns:
            No content
        """
        self._http.request(f"/api/v1/ssh_keys/{ssh_key}", method="DELETE")
