# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 92f0176cabc8

from __future__ import annotations

from ...runtime.http_client import HttpClient, SyncHttpClient
from ...types.status import StatusPing


class AsyncStatuResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def ping(self) -> StatusPing:
        """
        Check API token status
        Returns the validity and metadata of the bearer token supplied in the request.
        Use this endpoint to verify that an API key or session token is present, active,
        and unexpired before making authenticated calls.
        No authentication is required to call this endpoint it accepts any request,
        including those with no token at all. When a token is absent the `token.status`
        field is `"missing"` and `token.active` is `false`. When a token is present but
        invalid (expired, malformed, or referencing an unknown user) `token.active` is
        `false` and `token.status` describes the failure reason. When the token is valid,
        `token.active` is `true`, `token.status` is `"active"`, and `user` is populated
        with the authenticated user's profile.

        Returns:
            Token validity details and, when the token is active, the authenticated user's profile.
        """
        return await self._http.request("/api/v1/status/ping", response_type=StatusPing)


class StatuResource:
    def __init__(self, http: SyncHttpClient):
        self._http = http

    def ping(self) -> StatusPing:
        """
        Check API token status
        Returns the validity and metadata of the bearer token supplied in the request.
        Use this endpoint to verify that an API key or session token is present, active,
        and unexpired before making authenticated calls.
        No authentication is required to call this endpoint it accepts any request,
        including those with no token at all. When a token is absent the `token.status`
        field is `"missing"` and `token.active` is `false`. When a token is present but
        invalid (expired, malformed, or referencing an unknown user) `token.active` is
        `false` and `token.status` describes the failure reason. When the token is valid,
        `token.active` is `true`, `token.status` is `"active"`, and `user` is populated
        with the authenticated user's profile.

        Returns:
            Token validity details and, when the token is active, the authenticated user's profile.
        """
        return self._http.request("/api/v1/status/ping", response_type=StatusPing)
