# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: ce84bb76d7b8

from __future__ import annotations

from datetime import datetime
from typing import TypedDict

from pydantic import BaseModel

from ...runtime.http_client import HttpClient
from ...types.common import Message, PaginatedReplies


class ReactionCreateInput(TypedDict):
    emoji: str  # Emoji to add as reaction


class ThreadMessageReplaceInput(TypedDict, total=False):
    content: str | None  # New message content


class ReactionCreateResponseData(BaseModel):
    created_at: datetime | None = None  # Creation timestamp
    feedback_type: str | None = None  # Type of feedback (e.g., emoji_reaction)
    id: str  # Reaction ID (umf_...)
    message: str | None = None  # Message the reaction is on
    payload: dict[str, object] | None = None  # Reaction payload (e.g., {emoji: ...})
    updated_at: datetime | None = None  # Last update timestamp
    user: str | None = None  # User who added the reaction


class ReactionCreateResponse(BaseModel):
    data: ReactionCreateResponseData  # The created reaction


class ReactionResource:
    def __init__(self, http: HttpClient):
        self._http = http

    async def remove(self, message: str) -> None:
        await self._http.request(f"/api/v1/thread_messages/{message}/reactions", method="DELETE")

    async def create(self, message: str, input: ReactionCreateInput) -> ReactionCreateResponse:
        return await self._http.request(
            f"/api/v1/thread_messages/{message}/reactions",
            method="POST",
            body=input,
        )


class ThreadMessageResource:
    def __init__(self, http: HttpClient):
        self._http = http
        self.reactions = ReactionResource(http)

    async def delete(self, message: str) -> None:
        await self._http.request(f"/api/v1/thread_messages/{message}", method="DELETE")

    async def replace(self, message: str, input: ThreadMessageReplaceInput) -> Message:
        return await self._http.request(
            f"/api/v1/thread_messages/{message}",
            method="PUT",
            body=input,
        )

    async def replies(
        self,
        message: str,
        *,
        before_cursor: str | None = None,
        after_cursor: str | None = None,
        limit: int | None = None,
        tree: bool | None = None,
    ) -> PaginatedReplies:
        query: dict[str, object] = {}
        if before_cursor is not None:
            query["beforeCursor"] = before_cursor
        if after_cursor is not None:
            query["afterCursor"] = after_cursor
        if limit is not None:
            query["limit"] = limit
        if tree is not None:
            query["tree"] = tree
        return await self._http.request(f"/api/v1/thread_messages/{message}/replies", query=query)
