# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 7f4dd15e5559

import pytest

from archastro.platform import AsyncPlatformClient, PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def _async_client() -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _async_error_client(code: int) -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def test_threads_delete_success():
    client = _client()
    try:
        result = client.v1.threads.delete("test-value")
        assert result is None
    finally:
        client.close()


def test_threads_delete_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.delete("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_delete_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.delete("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_delete_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.delete("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_delete_success():
    client = _async_client()
    try:
        result = await client.v1.threads.delete("test-value")
        assert result is None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_delete_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.delete("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_delete_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.delete("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_delete_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.delete("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_get_success():
    client = _client()
    try:
        result = client.v1.threads.get("test-value")
        assert result is not None
    finally:
        client.close()


def test_threads_get_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.get("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_get_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.get("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_get_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.get("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_get_success():
    client = _async_client()
    try:
        result = await client.v1.threads.get("test-value")
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_get_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.get("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_get_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.get("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_get_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.get("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_replace_success():
    client = _client()
    try:
        result = client.v1.threads.replace("test-value", {})
        assert result is not None
    finally:
        client.close()


def test_threads_replace_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.replace("test-value", {})
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_replace_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.replace("test-value", {})
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_replace_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.replace("test-value", {})
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_threads_replace_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.replace("test-value", {})
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_replace_success():
    client = _async_client()
    try:
        result = await client.v1.threads.replace("test-value", {})
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_replace_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.replace("test-value", {})
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_replace_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.replace("test-value", {})
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_replace_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.replace("test-value", {})
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_replace_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.replace("test-value", {})
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_threads_agents_success():
    client = _client()
    try:
        result = client.v1.threads.agents("test-value")
        assert result is not None
        assert "data" in result
        assert isinstance(result["data"], list)
    finally:
        client.close()


def test_threads_agents_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.agents("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_agents_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.agents("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_agents_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.agents("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_agents_success():
    client = _async_client()
    try:
        result = await client.v1.threads.agents("test-value")
        assert result is not None
        assert "data" in result
        assert isinstance(result["data"], list)
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_agents_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.agents("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_agents_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.agents("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_agents_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.agents("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_artifacts_success():
    client = _client()
    try:
        result = client.v1.threads.artifacts("test-value")
        assert result is not None
        assert "data" in result
        assert isinstance(result["data"], list)
    finally:
        client.close()


def test_threads_artifacts_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.artifacts("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_artifacts_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.artifacts("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_artifacts_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.artifacts("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_artifacts_success():
    client = _async_client()
    try:
        result = await client.v1.threads.artifacts("test-value")
        assert result is not None
        assert "data" in result
        assert isinstance(result["data"], list)
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_artifacts_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.artifacts("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_artifacts_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.artifacts("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_artifacts_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.artifacts("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_mark_read_success():
    client = _client()
    try:
        result = client.v1.threads.mark_read("test-value", {})
        assert result is None
    finally:
        client.close()


def test_threads_mark_read_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.mark_read("test-value", {})
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_mark_read_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.mark_read("test-value", {})
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_threads_mark_read_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.mark_read("test-value", {})
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_mark_read_success():
    client = _async_client()
    try:
        result = await client.v1.threads.mark_read("test-value", {})
        assert result is None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_mark_read_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.mark_read("test-value", {})
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_mark_read_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.mark_read("test-value", {})
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_mark_read_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.mark_read("test-value", {})
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_threads_messages_success():
    client = _client()
    try:
        result = client.v1.threads.messages("test-value")
        assert result is not None
    finally:
        client.close()


def test_threads_messages_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.messages("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_messages_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.messages("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_messages_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.messages("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_messages_success():
    client = _async_client()
    try:
        result = await client.v1.threads.messages("test-value")
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_messages_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.messages("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_messages_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.messages("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_messages_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.messages("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_picture_success():
    client = _client()
    try:
        result = client.v1.threads.picture(
            "test-value",
            {
                "picture": {
                    "data": "test-value",
                    "filename": "test-value",
                    "mime_type": "application/json",
                }
            },
        )
        assert result is not None
    finally:
        client.close()


def test_threads_picture_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.picture(
                "test-value",
                {
                    "picture": {
                        "data": "test-value",
                        "filename": "test-value",
                        "mime_type": "application/json",
                    }
                },
            )
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_picture_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.picture(
                "test-value",
                {
                    "picture": {
                        "data": "test-value",
                        "filename": "test-value",
                        "mime_type": "application/json",
                    }
                },
            )
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_picture_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.picture(
                "test-value",
                {
                    "picture": {
                        "data": "test-value",
                        "filename": "test-value",
                        "mime_type": "application/json",
                    }
                },
            )
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_threads_picture_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.picture(
                "test-value",
                {
                    "picture": {
                        "data": "test-value",
                        "filename": "test-value",
                        "mime_type": "application/json",
                    }
                },
            )
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_picture_success():
    client = _async_client()
    try:
        result = await client.v1.threads.picture(
            "test-value",
            {
                "picture": {
                    "data": "test-value",
                    "filename": "test-value",
                    "mime_type": "application/json",
                }
            },
        )
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_picture_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.picture(
                "test-value",
                {
                    "picture": {
                        "data": "test-value",
                        "filename": "test-value",
                        "mime_type": "application/json",
                    }
                },
            )
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_picture_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.picture(
                "test-value",
                {
                    "picture": {
                        "data": "test-value",
                        "filename": "test-value",
                        "mime_type": "application/json",
                    }
                },
            )
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_picture_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.picture(
                "test-value",
                {
                    "picture": {
                        "data": "test-value",
                        "filename": "test-value",
                        "mime_type": "application/json",
                    }
                },
            )
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_picture_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.picture(
                "test-value",
                {
                    "picture": {
                        "data": "test-value",
                        "filename": "test-value",
                        "mime_type": "application/json",
                    }
                },
            )
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_threads_read_status_success():
    client = _client()
    try:
        result = client.v1.threads.read_status("test-value")
        assert result is not None
    finally:
        client.close()


def test_threads_read_status_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.read_status("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_read_status_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.read_status("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_read_status_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.read_status("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_read_status_success():
    client = _async_client()
    try:
        result = await client.v1.threads.read_status("test-value")
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_read_status_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.read_status("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_read_status_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.read_status("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_read_status_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.read_status("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_search_success():
    client = _client()
    try:
        result = client.v1.threads.search("test-value", q="test-value")
        assert result is not None
        assert "data" in result
        assert isinstance(result["data"], list)
    finally:
        client.close()


def test_threads_search_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.search("test-value", q="test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_search_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.search("test-value", q="test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_search_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.search("test-value", q="test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_search_success():
    client = _async_client()
    try:
        result = await client.v1.threads.search("test-value", q="test-value")
        assert result is not None
        assert "data" in result
        assert isinstance(result["data"], list)
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_search_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.search("test-value", q="test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_search_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.search("test-value", q="test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_search_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.search("test-value", q="test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_members_remove_success():
    client = _client()
    try:
        result = client.v1.threads.members.remove("test-value")
        assert result is None
    finally:
        client.close()


def test_threads_members_remove_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.remove("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_members_remove_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.remove("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_threads_members_remove_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.remove("test-value")
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_remove_success():
    client = _async_client()
    try:
        result = await client.v1.threads.members.remove("test-value")
        assert result is None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_members_remove_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.remove("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_remove_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.remove("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_remove_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.remove("test-value")
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_threads_members_list_success():
    client = _client()
    try:
        result = client.v1.threads.members.list("test-value")
        assert result is not None
        assert "data" in result
        assert isinstance(result["data"], list)
    finally:
        client.close()


def test_threads_members_list_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.list("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_members_list_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.list("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_members_list_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.list("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_list_success():
    client = _async_client()
    try:
        result = await client.v1.threads.members.list("test-value")
        assert result is not None
        assert "data" in result
        assert isinstance(result["data"], list)
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_members_list_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.list("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_list_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.list("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_list_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.list("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_members_create_success():
    client = _client()
    try:
        result = client.v1.threads.members.create("test-value", {"type": "test"})
        assert result is not None
    finally:
        client.close()


def test_threads_members_create_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.create("test-value", {"type": "test"})
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_members_create_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.create("test-value", {"type": "test"})
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_threads_members_create_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.members.create("test-value", {"type": "test"})
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_create_success():
    client = _async_client()
    try:
        result = await client.v1.threads.members.create("test-value", {"type": "test"})
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_members_create_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.create("test-value", {"type": "test"})
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_create_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.create("test-value", {"type": "test"})
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_members_create_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.members.create("test-value", {"type": "test"})
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_threads_settings_list_success():
    client = _client()
    try:
        result = client.v1.threads.settings.list("test-value")
        assert result is not None
    finally:
        client.close()


def test_threads_settings_list_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.settings.list("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_settings_list_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.settings.list("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_settings_list_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.settings.list("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_settings_list_success():
    client = _async_client()
    try:
        result = await client.v1.threads.settings.list("test-value")
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_settings_list_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.settings.list("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_settings_list_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.settings.list("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_settings_list_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.settings.list("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_threads_settings_replace_success():
    client = _client()
    try:
        result = client.v1.threads.settings.replace("test-value", {"settings": {}})
        assert result is not None
    finally:
        client.close()


def test_threads_settings_replace_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.settings.replace("test-value", {"settings": {}})
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_threads_settings_replace_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.settings.replace("test-value", {"settings": {}})
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_threads_settings_replace_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.settings.replace("test-value", {"settings": {}})
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_threads_settings_replace_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.threads.settings.replace("test-value", {"settings": {}})
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_threads_settings_replace_success():
    client = _async_client()
    try:
        result = await client.v1.threads.settings.replace("test-value", {"settings": {}})
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_threads_settings_replace_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.settings.replace("test-value", {"settings": {}})
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_settings_replace_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.settings.replace("test-value", {"settings": {}})
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_settings_replace_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.settings.replace("test-value", {"settings": {}})
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_threads_settings_replace_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.threads.settings.replace("test-value", {"settings": {}})
        assert exc_info.value.status == 422
    finally:
        await ec.close()
