# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: fd8c631f9a47

import pytest

from archastro.platform import PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


async def test_ai_chat_completions_success():
    client = _client()
    result = await client.v1.ai.chat.completions(
        {"messages": [{"role": "user"}], "opts": {"model": "test-model"}}
    )
    assert result is not None


async def test_ai_chat_completions_error_400():
    ec = _error_client(400)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.chat.completions(
            {"messages": [{"role": "user"}], "opts": {"model": "test-model"}}
        )
    assert exc_info.value.status == 400


async def test_ai_chat_completions_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.chat.completions(
            {"messages": [{"role": "user"}], "opts": {"model": "test-model"}}
        )
    assert exc_info.value.status == 401


async def test_ai_chat_completions_error_402():
    ec = _error_client(402)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.chat.completions(
            {"messages": [{"role": "user"}], "opts": {"model": "test-model"}}
        )
    assert exc_info.value.status == 402


async def test_ai_chat_completions_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.chat.completions(
            {"messages": [{"role": "user"}], "opts": {"model": "test-model"}}
        )
    assert exc_info.value.status == 422


async def test_ai_chat_models_success():
    client = _client()
    result = await client.v1.ai.chat.models()
    assert result is not None
    assert "data" in result
    assert isinstance(result["data"], list)


async def test_ai_chat_models_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.chat.models()
    assert exc_info.value.status == 401


async def test_ai_image_edits_success():
    client = _client()
    result = await client.v1.ai.image.edits(
        {
            "images": [{"image_data": "test-value", "image_type": "test-value"}],
            "prompt": "test-value",
        }
    )
    assert result is not None


async def test_ai_image_edits_error_400():
    ec = _error_client(400)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.image.edits(
            {
                "images": [{"image_data": "test-value", "image_type": "test-value"}],
                "prompt": "test-value",
            }
        )
    assert exc_info.value.status == 400


async def test_ai_image_edits_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.image.edits(
            {
                "images": [{"image_data": "test-value", "image_type": "test-value"}],
                "prompt": "test-value",
            }
        )
    assert exc_info.value.status == 401


async def test_ai_image_edits_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.image.edits(
            {
                "images": [{"image_data": "test-value", "image_type": "test-value"}],
                "prompt": "test-value",
            }
        )
    assert exc_info.value.status == 422


async def test_ai_image_generations_success():
    client = _client()
    result = await client.v1.ai.image.generations({"prompt": "test-value"})
    assert result is not None


async def test_ai_image_generations_error_400():
    ec = _error_client(400)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.image.generations({"prompt": "test-value"})
    assert exc_info.value.status == 400


async def test_ai_image_generations_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.image.generations({"prompt": "test-value"})
    assert exc_info.value.status == 401


async def test_ai_image_generations_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.image.generations({"prompt": "test-value"})
    assert exc_info.value.status == 422


async def test_ai_image_models_success():
    client = _client()
    result = await client.v1.ai.image.models()
    assert result is not None
    assert "data" in result
    assert isinstance(result["data"], list)


async def test_ai_image_models_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.ai.image.models()
    assert exc_info.value.status == 401
