# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 6da29d5680da

import pytest
from pydantic import BaseModel

from archastro.platform import AsyncPlatformClient, PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def _async_client() -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _async_error_client(code: int) -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def test_private_services_list_success():
    client = _client()
    try:
        result = client.v1.private_services.list()
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "PrivateServicePage"
    finally:
        client.close()


def test_private_services_list_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.list()
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_private_services_list_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.list()
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_private_services_list_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.list()
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_private_services_list_error_503():
    ec = _error_client(503)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.list()
        assert exc_info.value.status == 503
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_private_services_list_success():
    client = _async_client()
    try:
        result = await client.v1.private_services.list()
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "PrivateServicePage"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_private_services_list_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.list()
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_list_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.list()
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_list_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.list()
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_list_error_503():
    ec = _async_error_client(503)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.list()
        assert exc_info.value.status == 503
    finally:
        await ec.close()


def test_private_services_create_success():
    client = _client()
    try:
        result = client.v1.private_services.create(
            {
                "functions": [
                    {"description": "test description", "input_schema": {}, "name": "test-name"}
                ]
            }
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "PrivateService"
    finally:
        client.close()


def test_private_services_create_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_private_services_create_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_private_services_create_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_private_services_create_error_409():
    ec = _error_client(409)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 409
    finally:
        ec.close()


def test_private_services_create_error_503():
    ec = _error_client(503)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 503
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_private_services_create_success():
    client = _async_client()
    try:
        result = await client.v1.private_services.create(
            {
                "functions": [
                    {"description": "test description", "input_schema": {}, "name": "test-name"}
                ]
            }
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "PrivateService"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_private_services_create_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_create_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_create_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_create_error_409():
    ec = _async_error_client(409)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 409
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_create_error_503():
    ec = _async_error_client(503)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.create(
                {
                    "functions": [
                        {"description": "test description", "input_schema": {}, "name": "test-name"}
                    ]
                }
            )
        assert exc_info.value.status == 503
    finally:
        await ec.close()


def test_private_services_get_success():
    client = _client()
    try:
        result = client.v1.private_services.get("test-id")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "PrivateService"
    finally:
        client.close()


def test_private_services_get_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.get("test-id")
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_private_services_get_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.get("test-id")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_private_services_get_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.get("test-id")
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_private_services_get_error_503():
    ec = _error_client(503)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.private_services.get("test-id")
        assert exc_info.value.status == 503
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_private_services_get_success():
    client = _async_client()
    try:
        result = await client.v1.private_services.get("test-id")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "PrivateService"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_private_services_get_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.get("test-id")
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_get_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.get("test-id")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_get_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.get("test-id")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_private_services_get_error_503():
    ec = _async_error_client(503)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.private_services.get("test-id")
        assert exc_info.value.status == 503
    finally:
        await ec.close()
