# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 7c4afc87755c

import pytest

from archastro.platform import PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


async def test_notifications_list_success():
    client = _client()
    result = await client.v1.notifications.list()
    assert result is not None
    assert "data" in result
    assert isinstance(result["data"], list)


async def test_notifications_list_error_400():
    ec = _error_client(400)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.list()
    assert exc_info.value.status == 400


async def test_notifications_list_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.list()
    assert exc_info.value.status == 401


async def test_notifications_list_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.list()
    assert exc_info.value.status == 403


async def test_notifications_read_all_success():
    client = _client()
    result = await client.v1.notifications.read_all()
    assert result is None


async def test_notifications_read_all_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.read_all()
    assert exc_info.value.status == 401


async def test_notifications_read_all_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.read_all()
    assert exc_info.value.status == 403


async def test_notifications_send_success():
    client = _client()
    result = await client.v1.notifications.send({"type": "test", "user": "test-value"})
    assert result is not None


async def test_notifications_send_error_400():
    ec = _error_client(400)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.send({"type": "test", "user": "test-value"})
    assert exc_info.value.status == 400


async def test_notifications_send_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.send({"type": "test", "user": "test-value"})
    assert exc_info.value.status == 401


async def test_notifications_send_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.send({"type": "test", "user": "test-value"})
    assert exc_info.value.status == 403


async def test_notifications_send_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.send({"type": "test", "user": "test-value"})
    assert exc_info.value.status == 404


async def test_notifications_send_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.send({"type": "test", "user": "test-value"})
    assert exc_info.value.status == 422


async def test_notifications_unread_count_success():
    client = _client()
    result = await client.v1.notifications.unread_count()
    assert result is not None


async def test_notifications_unread_count_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.unread_count()
    assert exc_info.value.status == 401


async def test_notifications_unread_count_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.unread_count()
    assert exc_info.value.status == 403


async def test_notifications_archive_success():
    client = _client()
    result = await client.v1.notifications.archive("test-value")
    assert result is None


async def test_notifications_archive_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.archive("test-value")
    assert exc_info.value.status == 401


async def test_notifications_archive_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.archive("test-value")
    assert exc_info.value.status == 403


async def test_notifications_archive_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.archive("test-value")
    assert exc_info.value.status == 404


async def test_notifications_read_success():
    client = _client()
    result = await client.v1.notifications.read("test-value")
    assert result is None


async def test_notifications_read_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.read("test-value")
    assert exc_info.value.status == 401


async def test_notifications_read_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.read("test-value")
    assert exc_info.value.status == 403


async def test_notifications_read_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.read("test-value")
    assert exc_info.value.status == 404


async def test_notifications_unarchive_success():
    client = _client()
    result = await client.v1.notifications.unarchive("test-value")
    assert result is None


async def test_notifications_unarchive_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.unarchive("test-value")
    assert exc_info.value.status == 401


async def test_notifications_unarchive_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.unarchive("test-value")
    assert exc_info.value.status == 403


async def test_notifications_unarchive_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.notifications.unarchive("test-value")
    assert exc_info.value.status == 404
