# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: e710914f22f2

import pytest
from pydantic import BaseModel

from archastro.platform import AsyncPlatformClient, PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def _async_client() -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _async_error_client(code: int) -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def test_slack_channel_bindings_list_success():
    client = _client()
    try:
        result = client.v1.slack_channel_bindings.list()
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBindingListResponse"
    finally:
        client.close()


def test_slack_channel_bindings_list_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.list()
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_slack_channel_bindings_list_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.list()
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_slack_channel_bindings_list_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.list()
        assert exc_info.value.status == 403
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_list_success():
    client = _async_client()
    try:
        result = await client.v1.slack_channel_bindings.list()
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBindingListResponse"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_list_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.list()
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_list_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.list()
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_list_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.list()
        assert exc_info.value.status == 403
    finally:
        await ec.close()


def test_slack_channel_bindings_create_success():
    client = _client()
    try:
        result = client.v1.slack_channel_bindings.create(
            {
                "agent_user_ids": ["test-value"],
                "channel_id": "test-id",
                "slack_team_id": "test-id",
                "team_id": "test-id",
            }
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBinding"
    finally:
        client.close()


def test_slack_channel_bindings_create_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_slack_channel_bindings_create_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_slack_channel_bindings_create_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_slack_channel_bindings_create_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_slack_channel_bindings_create_error_409():
    ec = _error_client(409)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 409
    finally:
        ec.close()


def test_slack_channel_bindings_create_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_create_success():
    client = _async_client()
    try:
        result = await client.v1.slack_channel_bindings.create(
            {
                "agent_user_ids": ["test-value"],
                "channel_id": "test-id",
                "slack_team_id": "test-id",
                "team_id": "test-id",
            }
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBinding"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_create_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_create_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_create_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_create_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_create_error_409():
    ec = _async_error_client(409)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 409
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_create_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.create(
                {
                    "agent_user_ids": ["test-value"],
                    "channel_id": "test-id",
                    "slack_team_id": "test-id",
                    "team_id": "test-id",
                }
            )
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_slack_channel_bindings_provision_success():
    client = _client()
    try:
        result = client.v1.slack_channel_bindings.provision(
            {
                "customer_key": "test-key",
                "customer_label": "test-value",
                "slack_team_id": "test-id",
                "template_config_id": "test-id",
            }
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBinding"
    finally:
        client.close()


def test_slack_channel_bindings_provision_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_slack_channel_bindings_provision_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_slack_channel_bindings_provision_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_slack_channel_bindings_provision_error_409():
    ec = _error_client(409)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 409
    finally:
        ec.close()


def test_slack_channel_bindings_provision_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 422
    finally:
        ec.close()


def test_slack_channel_bindings_provision_error_500():
    ec = _error_client(500)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 500
    finally:
        ec.close()


def test_slack_channel_bindings_provision_error_502():
    ec = _error_client(502)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 502
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_provision_success():
    client = _async_client()
    try:
        result = await client.v1.slack_channel_bindings.provision(
            {
                "customer_key": "test-key",
                "customer_label": "test-value",
                "slack_team_id": "test-id",
                "template_config_id": "test-id",
            }
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBinding"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_provision_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_provision_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_provision_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_provision_error_409():
    ec = _async_error_client(409)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 409
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_provision_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 422
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_provision_error_500():
    ec = _async_error_client(500)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 500
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_provision_error_502():
    ec = _async_error_client(502)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.provision(
                {
                    "customer_key": "test-key",
                    "customer_label": "test-value",
                    "slack_team_id": "test-id",
                    "template_config_id": "test-id",
                }
            )
        assert exc_info.value.status == 502
    finally:
        await ec.close()


def test_slack_channel_bindings_delete_success():
    client = _client()
    try:
        result = client.v1.slack_channel_bindings.delete("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBindingDeleteResponse"
    finally:
        client.close()


def test_slack_channel_bindings_delete_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_slack_channel_bindings_delete_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_slack_channel_bindings_delete_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_slack_channel_bindings_delete_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_slack_channel_bindings_delete_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_delete_success():
    client = _async_client()
    try:
        result = await client.v1.slack_channel_bindings.delete("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBindingDeleteResponse"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_delete_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_delete_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_delete_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_delete_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_delete_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.delete("test-value")
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_slack_channel_bindings_get_success():
    client = _client()
    try:
        result = client.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBinding"
    finally:
        client.close()


def test_slack_channel_bindings_get_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_slack_channel_bindings_get_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_slack_channel_bindings_get_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_slack_channel_bindings_get_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_slack_channel_bindings_get_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_get_success():
    client = _async_client()
    try:
        result = await client.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBinding"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_get_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_get_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_get_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_get_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_get_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.get("test-value", slack_team_id="test-id")
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_slack_channel_bindings_deposit_thread_success():
    client = _client()
    try:
        result = client.v1.slack_channel_bindings.deposit_thread(
            "test-value", {"slack_team_id": "test-id"}
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBinding"
    finally:
        client.close()


def test_slack_channel_bindings_deposit_thread_error_400():
    ec = _error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.deposit_thread("test-value", {"slack_team_id": "test-id"})
        assert exc_info.value.status == 400
    finally:
        ec.close()


def test_slack_channel_bindings_deposit_thread_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.deposit_thread("test-value", {"slack_team_id": "test-id"})
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_slack_channel_bindings_deposit_thread_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.deposit_thread("test-value", {"slack_team_id": "test-id"})
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_slack_channel_bindings_deposit_thread_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.deposit_thread("test-value", {"slack_team_id": "test-id"})
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_slack_channel_bindings_deposit_thread_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.slack_channel_bindings.deposit_thread("test-value", {"slack_team_id": "test-id"})
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_deposit_thread_success():
    client = _async_client()
    try:
        result = await client.v1.slack_channel_bindings.deposit_thread(
            "test-value", {"slack_team_id": "test-id"}
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "SlackChannelBinding"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_deposit_thread_error_400():
    ec = _async_error_client(400)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.deposit_thread(
                "test-value", {"slack_team_id": "test-id"}
            )
        assert exc_info.value.status == 400
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_deposit_thread_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.deposit_thread(
                "test-value", {"slack_team_id": "test-id"}
            )
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_deposit_thread_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.deposit_thread(
                "test-value", {"slack_team_id": "test-id"}
            )
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_deposit_thread_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.deposit_thread(
                "test-value", {"slack_team_id": "test-id"}
            )
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_slack_channel_bindings_deposit_thread_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.slack_channel_bindings.deposit_thread(
                "test-value", {"slack_team_id": "test-id"}
            )
        assert exc_info.value.status == 422
    finally:
        await ec.close()
