# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: e51b2cc82b09

import pytest

from archastro.platform import PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


async def test_agent_skills_list_success():
    client = _client()
    result = await client.v1.agent_skills.list()
    assert result is not None


async def test_agent_skills_list_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.list()
    assert exc_info.value.status == 401


async def test_agent_skills_list_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.list()
    assert exc_info.value.status == 403


async def test_agent_skills_list_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.list()
    assert exc_info.value.status == 404


async def test_agent_skills_create_success():
    client = _client()
    result = await client.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
    assert result is not None


async def test_agent_skills_create_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
    assert exc_info.value.status == 401


async def test_agent_skills_create_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
    assert exc_info.value.status == 403


async def test_agent_skills_create_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
    assert exc_info.value.status == 404


async def test_agent_skills_create_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
    assert exc_info.value.status == 422


async def test_agent_skills_delete_success():
    client = _client()
    result = await client.v1.agent_skills.delete("test-value")
    assert result is None


async def test_agent_skills_delete_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.delete("test-value")
    assert exc_info.value.status == 401


async def test_agent_skills_delete_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.delete("test-value")
    assert exc_info.value.status == 403


async def test_agent_skills_delete_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.delete("test-value")
    assert exc_info.value.status == 404


async def test_agent_skills_get_success():
    client = _client()
    result = await client.v1.agent_skills.get("test-value")
    assert result is not None


async def test_agent_skills_get_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.get("test-value")
    assert exc_info.value.status == 401


async def test_agent_skills_get_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.get("test-value")
    assert exc_info.value.status == 403


async def test_agent_skills_get_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.get("test-value")
    assert exc_info.value.status == 404


async def test_agent_skills_update_success():
    client = _client()
    result = await client.v1.agent_skills.update("test-value", {})
    assert result is not None


async def test_agent_skills_update_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.update("test-value", {})
    assert exc_info.value.status == 401


async def test_agent_skills_update_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.update("test-value", {})
    assert exc_info.value.status == 403


async def test_agent_skills_update_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.update("test-value", {})
    assert exc_info.value.status == 404


async def test_agent_skills_update_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.update("test-value", {})
    assert exc_info.value.status == 422


async def test_agent_skills_activate_success():
    client = _client()
    result = await client.v1.agent_skills.activate("test-value")
    assert result is not None


async def test_agent_skills_activate_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.activate("test-value")
    assert exc_info.value.status == 401


async def test_agent_skills_activate_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.activate("test-value")
    assert exc_info.value.status == 403


async def test_agent_skills_activate_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.activate("test-value")
    assert exc_info.value.status == 404


async def test_agent_skills_deactivate_success():
    client = _client()
    result = await client.v1.agent_skills.deactivate("test-value")
    assert result is not None


async def test_agent_skills_deactivate_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.deactivate("test-value")
    assert exc_info.value.status == 401


async def test_agent_skills_deactivate_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.deactivate("test-value")
    assert exc_info.value.status == 403


async def test_agent_skills_deactivate_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_skills.deactivate("test-value")
    assert exc_info.value.status == 404
