# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: a848df03e938

import pytest

from archastro.platform import AsyncPlatformClient, PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def _async_client() -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _async_error_client(code: int) -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def test_agent_skills_list_success():
    client = _client()
    try:
        result = client.v1.agent_skills.list()
        assert result is not None
    finally:
        client.close()


def test_agent_skills_list_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.list()
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_skills_list_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.list()
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_skills_list_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.list()
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_list_success():
    client = _async_client()
    try:
        result = await client.v1.agent_skills.list()
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_skills_list_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.list()
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_list_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.list()
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_list_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.list()
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_agent_skills_create_success():
    client = _client()
    try:
        result = client.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert result is not None
    finally:
        client.close()


def test_agent_skills_create_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_skills_create_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_skills_create_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_agent_skills_create_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_create_success():
    client = _async_client()
    try:
        result = await client.v1.agent_skills.create(
            {"agent": "test-value", "config": "test-value"}
        )
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_skills_create_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_create_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_create_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_create_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.create({"agent": "test-value", "config": "test-value"})
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_agent_skills_delete_success():
    client = _client()
    try:
        result = client.v1.agent_skills.delete("test-value")
        assert result is None
    finally:
        client.close()


def test_agent_skills_delete_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.delete("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_skills_delete_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.delete("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_skills_delete_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.delete("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_delete_success():
    client = _async_client()
    try:
        result = await client.v1.agent_skills.delete("test-value")
        assert result is None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_skills_delete_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.delete("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_delete_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.delete("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_delete_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.delete("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_agent_skills_get_success():
    client = _client()
    try:
        result = client.v1.agent_skills.get("test-value")
        assert result is not None
    finally:
        client.close()


def test_agent_skills_get_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.get("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_skills_get_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.get("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_skills_get_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.get("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_get_success():
    client = _async_client()
    try:
        result = await client.v1.agent_skills.get("test-value")
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_skills_get_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.get("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_get_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.get("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_get_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.get("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_agent_skills_update_success():
    client = _client()
    try:
        result = client.v1.agent_skills.update("test-value", {})
        assert result is not None
    finally:
        client.close()


def test_agent_skills_update_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.update("test-value", {})
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_skills_update_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.update("test-value", {})
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_skills_update_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.update("test-value", {})
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_agent_skills_update_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.update("test-value", {})
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_update_success():
    client = _async_client()
    try:
        result = await client.v1.agent_skills.update("test-value", {})
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_skills_update_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.update("test-value", {})
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_update_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.update("test-value", {})
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_update_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.update("test-value", {})
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_update_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.update("test-value", {})
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_agent_skills_activate_success():
    client = _client()
    try:
        result = client.v1.agent_skills.activate("test-value")
        assert result is not None
    finally:
        client.close()


def test_agent_skills_activate_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.activate("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_skills_activate_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.activate("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_skills_activate_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.activate("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_activate_success():
    client = _async_client()
    try:
        result = await client.v1.agent_skills.activate("test-value")
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_skills_activate_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.activate("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_activate_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.activate("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_activate_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.activate("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_agent_skills_deactivate_success():
    client = _client()
    try:
        result = client.v1.agent_skills.deactivate("test-value")
        assert result is not None
    finally:
        client.close()


def test_agent_skills_deactivate_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.deactivate("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_skills_deactivate_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.deactivate("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_skills_deactivate_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_skills.deactivate("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_deactivate_success():
    client = _async_client()
    try:
        result = await client.v1.agent_skills.deactivate("test-value")
        assert result is not None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_skills_deactivate_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.deactivate("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_deactivate_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.deactivate("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_skills_deactivate_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_skills.deactivate("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()
