# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 784abd7ce938

import pytest
from pydantic import BaseModel

from archastro.platform import AsyncPlatformClient, PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def _async_client() -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _async_error_client(code: int) -> AsyncPlatformClient:
    return AsyncPlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


def test_agent_installations_list_success():
    client = _client()
    try:
        result = client.v1.agent_installations.list()
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "InstallationListResponse"
    finally:
        client.close()


def test_agent_installations_list_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.list()
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_installations_list_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.list()
        assert exc_info.value.status == 403
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_list_success():
    client = _async_client()
    try:
        result = await client.v1.agent_installations.list()
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "InstallationListResponse"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_installations_list_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.list()
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_list_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.list()
        assert exc_info.value.status == 403
    finally:
        await ec.close()


def test_agent_installations_delete_success():
    client = _client()
    try:
        result = client.v1.agent_installations.delete("test-value")
        assert result is None
    finally:
        client.close()


def test_agent_installations_delete_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.delete("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_installations_delete_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.delete("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_installations_delete_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.delete("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_delete_success():
    client = _async_client()
    try:
        result = await client.v1.agent_installations.delete("test-value")
        assert result is None
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_installations_delete_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.delete("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_delete_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.delete("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_delete_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.delete("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_agent_installations_get_success():
    client = _client()
    try:
        result = client.v1.agent_installations.get("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "Installation"
    finally:
        client.close()


def test_agent_installations_get_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.get("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_installations_get_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.get("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_installations_get_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.get("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_get_success():
    client = _async_client()
    try:
        result = await client.v1.agent_installations.get("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "Installation"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_installations_get_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.get("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_get_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.get("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_get_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.get("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_agent_installations_activate_success():
    client = _client()
    try:
        result = client.v1.agent_installations.activate("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "Installation"
    finally:
        client.close()


def test_agent_installations_activate_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.activate("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_installations_activate_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.activate("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_installations_activate_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.activate("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_agent_installations_activate_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.activate("test-value")
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_activate_success():
    client = _async_client()
    try:
        result = await client.v1.agent_installations.activate("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "Installation"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_installations_activate_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.activate("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_activate_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.activate("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_activate_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.activate("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_activate_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.activate("test-value")
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_agent_installations_pause_success():
    client = _client()
    try:
        result = client.v1.agent_installations.pause("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "Installation"
    finally:
        client.close()


def test_agent_installations_pause_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.pause("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_installations_pause_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.pause("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_installations_pause_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.pause("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_agent_installations_pause_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.pause("test-value")
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_pause_success():
    client = _async_client()
    try:
        result = await client.v1.agent_installations.pause("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "Installation"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_installations_pause_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.pause("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_pause_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.pause("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_pause_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.pause("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_pause_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.pause("test-value")
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_agent_installations_suspend_success():
    client = _client()
    try:
        result = client.v1.agent_installations.suspend("test-value", {})
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "Installation"
    finally:
        client.close()


def test_agent_installations_suspend_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.suspend("test-value", {})
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_installations_suspend_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.suspend("test-value", {})
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_installations_suspend_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.suspend("test-value", {})
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_agent_installations_suspend_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.suspend("test-value", {})
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_suspend_success():
    client = _async_client()
    try:
        result = await client.v1.agent_installations.suspend("test-value", {})
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "Installation"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_installations_suspend_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.suspend("test-value", {})
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_suspend_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.suspend("test-value", {})
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_suspend_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.suspend("test-value", {})
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_suspend_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.suspend("test-value", {})
        assert exc_info.value.status == 422
    finally:
        await ec.close()


def test_agent_installations_installation_sources_list_success():
    client = _client()
    try:
        result = client.v1.agent_installations.installation_sources.list("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "InstallationSourceListResponse"
    finally:
        client.close()


def test_agent_installations_installation_sources_list_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.installation_sources.list("test-value")
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_installations_installation_sources_list_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.installation_sources.list("test-value")
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_installations_installation_sources_list_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.installation_sources.list("test-value")
        assert exc_info.value.status == 404
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_list_success():
    client = _async_client()
    try:
        result = await client.v1.agent_installations.installation_sources.list("test-value")
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "InstallationSourceListResponse"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_list_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.installation_sources.list("test-value")
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_list_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.installation_sources.list("test-value")
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_list_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.installation_sources.list("test-value")
        assert exc_info.value.status == 404
    finally:
        await ec.close()


def test_agent_installations_installation_sources_create_success():
    client = _client()
    try:
        result = client.v1.agent_installations.installation_sources.create(
            "test-value", {"payload": {}, "type": "test"}
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "InstallationSource"
    finally:
        client.close()


def test_agent_installations_installation_sources_create_error_401():
    ec = _error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.installation_sources.create(
                "test-value", {"payload": {}, "type": "test"}
            )
        assert exc_info.value.status == 401
    finally:
        ec.close()


def test_agent_installations_installation_sources_create_error_403():
    ec = _error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.installation_sources.create(
                "test-value", {"payload": {}, "type": "test"}
            )
        assert exc_info.value.status == 403
    finally:
        ec.close()


def test_agent_installations_installation_sources_create_error_404():
    ec = _error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.installation_sources.create(
                "test-value", {"payload": {}, "type": "test"}
            )
        assert exc_info.value.status == 404
    finally:
        ec.close()


def test_agent_installations_installation_sources_create_error_422():
    ec = _error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            ec.v1.agent_installations.installation_sources.create(
                "test-value", {"payload": {}, "type": "test"}
            )
        assert exc_info.value.status == 422
    finally:
        ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_create_success():
    client = _async_client()
    try:
        result = await client.v1.agent_installations.installation_sources.create(
            "test-value", {"payload": {}, "type": "test"}
        )
        assert isinstance(result, BaseModel)
        assert type(result).__name__ == "InstallationSource"
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_create_error_401():
    ec = _async_error_client(401)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.installation_sources.create(
                "test-value", {"payload": {}, "type": "test"}
            )
        assert exc_info.value.status == 401
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_create_error_403():
    ec = _async_error_client(403)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.installation_sources.create(
                "test-value", {"payload": {}, "type": "test"}
            )
        assert exc_info.value.status == 403
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_create_error_404():
    ec = _async_error_client(404)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.installation_sources.create(
                "test-value", {"payload": {}, "type": "test"}
            )
        assert exc_info.value.status == 404
    finally:
        await ec.close()


@pytest.mark.asyncio
async def test_async_agent_installations_installation_sources_create_error_422():
    ec = _async_error_client(422)
    try:
        with pytest.raises(ApiError) as exc_info:
            await ec.v1.agent_installations.installation_sources.create(
                "test-value", {"payload": {}, "type": "test"}
            )
        assert exc_info.value.status == 422
    finally:
        await ec.close()
