# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 3ec14aeaa53e

import pytest

from archastro.platform import PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


async def test_agent_installations_list_success():
    client = _client()
    result = await client.v1.agent_installations.list()
    assert result is not None


async def test_agent_installations_list_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.list()
    assert exc_info.value.status == 401


async def test_agent_installations_list_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.list()
    assert exc_info.value.status == 403


async def test_agent_installations_delete_success():
    client = _client()
    result = await client.v1.agent_installations.delete("test-value")
    assert result is None


async def test_agent_installations_delete_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.delete("test-value")
    assert exc_info.value.status == 401


async def test_agent_installations_delete_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.delete("test-value")
    assert exc_info.value.status == 403


async def test_agent_installations_delete_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.delete("test-value")
    assert exc_info.value.status == 404


async def test_agent_installations_get_success():
    client = _client()
    result = await client.v1.agent_installations.get("test-value")
    assert result is not None


async def test_agent_installations_get_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.get("test-value")
    assert exc_info.value.status == 401


async def test_agent_installations_get_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.get("test-value")
    assert exc_info.value.status == 403


async def test_agent_installations_get_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.get("test-value")
    assert exc_info.value.status == 404


async def test_agent_installations_activate_success():
    client = _client()
    result = await client.v1.agent_installations.activate(
        "test-value", {"installation": "test-value"}
    )
    assert result is not None


async def test_agent_installations_activate_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.activate("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 401


async def test_agent_installations_activate_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.activate("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 403


async def test_agent_installations_activate_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.activate("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 404


async def test_agent_installations_activate_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.activate("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 422


async def test_agent_installations_pause_success():
    client = _client()
    result = await client.v1.agent_installations.pause("test-value", {"installation": "test-value"})
    assert result is not None


async def test_agent_installations_pause_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.pause("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 401


async def test_agent_installations_pause_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.pause("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 403


async def test_agent_installations_pause_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.pause("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 404


async def test_agent_installations_pause_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.pause("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 422


async def test_agent_installations_suspend_success():
    client = _client()
    result = await client.v1.agent_installations.suspend(
        "test-value", {"installation": "test-value"}
    )
    assert result is not None


async def test_agent_installations_suspend_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.suspend("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 401


async def test_agent_installations_suspend_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.suspend("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 403


async def test_agent_installations_suspend_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.suspend("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 404


async def test_agent_installations_suspend_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.suspend("test-value", {"installation": "test-value"})
    assert exc_info.value.status == 422


async def test_agent_installations_installation_sources_list_success():
    client = _client()
    result = await client.v1.agent_installations.installation_sources.list("test-value")
    assert result is not None


async def test_agent_installations_installation_sources_list_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.installation_sources.list("test-value")
    assert exc_info.value.status == 401


async def test_agent_installations_installation_sources_list_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.installation_sources.list("test-value")
    assert exc_info.value.status == 403


async def test_agent_installations_installation_sources_list_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.installation_sources.list("test-value")
    assert exc_info.value.status == 404


async def test_agent_installations_installation_sources_create_success():
    client = _client()
    result = await client.v1.agent_installations.installation_sources.create(
        "test-value", {"installation": "test-value", "payload": {}, "type": "test"}
    )
    assert result is not None


async def test_agent_installations_installation_sources_create_error_401():
    ec = _error_client(401)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.installation_sources.create(
            "test-value", {"installation": "test-value", "payload": {}, "type": "test"}
        )
    assert exc_info.value.status == 401


async def test_agent_installations_installation_sources_create_error_403():
    ec = _error_client(403)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.installation_sources.create(
            "test-value", {"installation": "test-value", "payload": {}, "type": "test"}
        )
    assert exc_info.value.status == 403


async def test_agent_installations_installation_sources_create_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.installation_sources.create(
            "test-value", {"installation": "test-value", "payload": {}, "type": "test"}
        )
    assert exc_info.value.status == 404


async def test_agent_installations_installation_sources_create_error_422():
    ec = _error_client(422)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.agent_installations.installation_sources.create(
            "test-value", {"installation": "test-value", "payload": {}, "type": "test"}
        )
    assert exc_info.value.status == 422
