# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 1c99d068dfe2

import pytest

from archastro.platform import PlatformClient
from archastro.platform.runtime.http_client import ApiError

PRISM_URL = "http://127.0.0.1:4040"


def _client() -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key"},
        access_token="test-token",
    )


def _error_client(code: int) -> PlatformClient:
    return PlatformClient(
        base_url=PRISM_URL,
        default_headers={"x-archastro-api-key": "pk_test-key", "Prefer": f"code={code}"},
        access_token="test-token",
    )


async def test_files_avatar_success():
    client = _client()
    result = await client.v1.files.avatar("test-value", token="test-token")
    assert result["content"] is not None
    assert result["mime_type"]


async def test_files_avatar_error_404():
    ec = _error_client(404)
    with pytest.raises(ApiError) as exc_info:
        await ec.v1.files.avatar("test-value", token="test-token")
    assert exc_info.value.status == 404
