# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 778ff3bdf540

from collections.abc import Callable
from datetime import datetime
from typing import TYPE_CHECKING, Required, TypedDict

if TYPE_CHECKING:
    from archastro.phx_channel.socket import Socket


# Fork a sub-thread from an existing message
class ApiChatForkThreadInput(TypedDict, total=False):
    message_id: Required[str]
    title: str


# Mark a thread as read up to a given message
class ApiChatMarkThreadReadInput(TypedDict):
    message_id: str


# Load additional messages with cursor-based pagination
class ApiChatLoadMoreMessagesInput(TypedDict, total=False):
    after_cursor: str
    before_cursor: str
    include_metadata: bool
    limit: int


# Post a new message with optional uploads and reply-to
class ApiChatPostMessageInput(TypedDict, total=False):
    content: Required[str]
    idempotency_key: str
    reply_to: str
    uploads: list[dict[str, object]]


# Post a simple text message
class ApiChatPostSimpleMessageInput(TypedDict, total=False):
    content: str
    idempotency_key: str
    reply_to: str


# Edit an existing message's content
class ApiChatEditMessageInput(TypedDict):
    content: str
    message_id: str


# Delete a message
class ApiChatDeleteMessageInput(TypedDict):
    message_id: str


# Add an emoji reaction to a message
class ApiChatAddReactionInput(TypedDict):
    emoji: str
    message_id: str


# Remove an emoji reaction from a message
class ApiChatRemoveReactionInput(TypedDict):
    emoji: str
    message_id: str


class MessageAddedPayloadMessageActorsItemProfilePicture(TypedDict, total=False):
    file: str | None  # Storage file
    height: int | None  # Image height in pixels
    media: str | None  # Media
    mime_type: str | None  # Image MIME type
    refresh_url: str | None  # URL to refresh signed URL
    url: str | None  # Image URL
    width: int | None  # Image width in pixels


class MessageAddedPayloadMessageActorsItem(TypedDict, total=False):
    alias: str | None  # Actor alias/handle
    id: str | None  # Actor ID (format: user-xxx or agent-xxx)
    name: str | None  # Actor display name
    profile_picture: MessageAddedPayloadMessageActorsItemProfilePicture | None  # Profile picture


class MessageAddedPayloadMessageAttachmentsItemImageSource(TypedDict, total=False):
    file: str | None  # Storage file
    height: int | None  # Image height in pixels
    media: str | None  # Media
    mime_type: str | None  # Image MIME type
    refresh_url: str | None  # URL to refresh signed URL
    url: str | None  # Image URL
    width: int | None  # Image width in pixels


class MessageAddedPayloadMessageAttachmentsItemVariantsItemImageSource(TypedDict, total=False):
    file: str | None  # Storage file
    height: int | None  # Image height in pixels
    media: str | None  # Media
    mime_type: str | None  # Image MIME type
    refresh_url: str | None  # URL to refresh signed URL
    url: str | None  # Image URL
    width: int | None  # Image width in pixels


class MessageAddedPayloadMessageAttachmentsItemVariantsItem(TypedDict, total=False):
    content_type: str | None  # File content type
    created_at: datetime | None  # Creation timestamp
    file: str | None  # Storage file
    filename: str | None  # Original filename
    height: int | None  # Height in pixels
    id: Required[str]  # Variant ID
    image_source: MessageAddedPayloadMessageAttachmentsItemVariantsItemImageSource | None
    updated_at: datetime | None  # Last update timestamp
    url: str | None  # Signed download URL
    variant_key: str | None  # Variant key (original, thumbnail, etc)
    width: int | None  # Width in pixels


class MessageAddedPayloadMessageAttachmentsItem(TypedDict, total=False):
    content_type: str | None  # MIME content type (file, artifact, media types)
    description: str | None  # Description (scraped_link, artifact, task types)
    filename: str | None  # File name (file, artifact, media types)
    height: int | None  # Media height (media type)
    id: Required[str]  # Attachment ID
    image_height: int | None  # Preview image height (scraped_link type)
    image_source: MessageAddedPayloadMessageAttachmentsItemImageSource | None
    image_url: str | None  # Preview image URL (scraped_link type)
    image_width: int | None  # Preview image width (scraped_link type)
    media_type: str | None  # Media type (media type)
    name: str | None  # Media name (media type)
    object: dict[str, object] | None  # Embedded object (task, action types)
    title: str | None  # Title (scraped_link, artifact, task types)
    type: Required[str]  # Attachment type: file, scraped_link, artifact, task, media, action
    url: str | None  # URL to the resource (file, scraped_link, artifact, media types)
    variants: list[MessageAddedPayloadMessageAttachmentsItemVariantsItem] | None
    version: int | None  # Artifact version number (artifact type)
    width: int | None  # Media width (media type)


class MessageAddedPayloadMessageReactionsItem(TypedDict, total=False):
    payload: dict[str, object] | None  # Reaction payload (e.g., {emoji: '👍'})
    type: Required[str]  # Reaction type (e.g., emoji_reaction)
    user: str | None  # User who added the reaction


class MessageAddedPayloadMessage(TypedDict, total=False):
    actors: list[MessageAddedPayloadMessageActorsItem] | None  # Message actors
    agent: str | None  # Agent if sent by an agent user
    attachments: list[MessageAddedPayloadMessageAttachmentsItem] | None  # Message attachments
    branched_thread: str | None  # Branched thread (if message spawned a thread)
    content: str | None  # Message content
    created_at: datetime | None  # Creation timestamp
    has_replies: bool | None  # Whether message has replies
    id: Required[str]  # Message ID (msg_...)
    idempotency_key: str | None  # Client-provided idempotency key
    legacy_agent: str | None  # Legacy agent if sent by legacy chat agent
    metadata: dict[str, object] | None  # Message metadata
    org: str | None  # Organization
    reactions: list[MessageAddedPayloadMessageReactionsItem] | None  # Message reactions
    rendering_mode: str | None  # Rendering mode hint
    replies: list[dict[str, object]] | None  # Inline replies (if loaded)
    replies_after_cursor: str | None  # Cursor for replies pagination
    replies_before_cursor: str | None  # Cursor for replies pagination
    reply_count: int | None  # Number of replies
    reply_to: dict[str, object] | None  # Parent message object (if loaded)
    sandbox: str | None  # Sandbox identifier
    team: str | None  # Team
    thread: str | None  # Parent thread
    user: str | None  # Author user (public ID or expanded object when loaded)


# Broadcast when a new message is added to a thread
class MessageAddedPayload(TypedDict, total=False):
    after_cursor: str | None
    before_cursor: str | None
    message: MessageAddedPayloadMessage | None  # API schema for a chat message.
    thread_id: str | None


class MessageUpdatedPayloadMessageActorsItemProfilePicture(TypedDict, total=False):
    file: str | None  # Storage file
    height: int | None  # Image height in pixels
    media: str | None  # Media
    mime_type: str | None  # Image MIME type
    refresh_url: str | None  # URL to refresh signed URL
    url: str | None  # Image URL
    width: int | None  # Image width in pixels


class MessageUpdatedPayloadMessageActorsItem(TypedDict, total=False):
    alias: str | None  # Actor alias/handle
    id: str | None  # Actor ID (format: user-xxx or agent-xxx)
    name: str | None  # Actor display name
    profile_picture: MessageUpdatedPayloadMessageActorsItemProfilePicture | None


class MessageUpdatedPayloadMessageAttachmentsItemImageSource(TypedDict, total=False):
    file: str | None  # Storage file
    height: int | None  # Image height in pixels
    media: str | None  # Media
    mime_type: str | None  # Image MIME type
    refresh_url: str | None  # URL to refresh signed URL
    url: str | None  # Image URL
    width: int | None  # Image width in pixels


class MessageUpdatedPayloadMessageAttachmentsItemVariantsItemImageSource(TypedDict, total=False):
    file: str | None  # Storage file
    height: int | None  # Image height in pixels
    media: str | None  # Media
    mime_type: str | None  # Image MIME type
    refresh_url: str | None  # URL to refresh signed URL
    url: str | None  # Image URL
    width: int | None  # Image width in pixels


class MessageUpdatedPayloadMessageAttachmentsItemVariantsItem(TypedDict, total=False):
    content_type: str | None  # File content type
    created_at: datetime | None  # Creation timestamp
    file: str | None  # Storage file
    filename: str | None  # Original filename
    height: int | None  # Height in pixels
    id: Required[str]  # Variant ID
    image_source: MessageUpdatedPayloadMessageAttachmentsItemVariantsItemImageSource | None
    updated_at: datetime | None  # Last update timestamp
    url: str | None  # Signed download URL
    variant_key: str | None  # Variant key (original, thumbnail, etc)
    width: int | None  # Width in pixels


class MessageUpdatedPayloadMessageAttachmentsItem(TypedDict, total=False):
    content_type: str | None  # MIME content type (file, artifact, media types)
    description: str | None  # Description (scraped_link, artifact, task types)
    filename: str | None  # File name (file, artifact, media types)
    height: int | None  # Media height (media type)
    id: Required[str]  # Attachment ID
    image_height: int | None  # Preview image height (scraped_link type)
    image_source: MessageUpdatedPayloadMessageAttachmentsItemImageSource | None
    image_url: str | None  # Preview image URL (scraped_link type)
    image_width: int | None  # Preview image width (scraped_link type)
    media_type: str | None  # Media type (media type)
    name: str | None  # Media name (media type)
    object: dict[str, object] | None  # Embedded object (task, action types)
    title: str | None  # Title (scraped_link, artifact, task types)
    type: Required[str]  # Attachment type: file, scraped_link, artifact, task, media, action
    url: str | None  # URL to the resource (file, scraped_link, artifact, media types)
    variants: list[MessageUpdatedPayloadMessageAttachmentsItemVariantsItem] | None
    version: int | None  # Artifact version number (artifact type)
    width: int | None  # Media width (media type)


class MessageUpdatedPayloadMessageReactionsItem(TypedDict, total=False):
    payload: dict[str, object] | None  # Reaction payload (e.g., {emoji: '👍'})
    type: Required[str]  # Reaction type (e.g., emoji_reaction)
    user: str | None  # User who added the reaction


class MessageUpdatedPayloadMessage(TypedDict, total=False):
    actors: list[MessageUpdatedPayloadMessageActorsItem] | None  # Message actors
    agent: str | None  # Agent if sent by an agent user
    attachments: list[MessageUpdatedPayloadMessageAttachmentsItem] | None  # Message attachments
    branched_thread: str | None  # Branched thread (if message spawned a thread)
    content: str | None  # Message content
    created_at: datetime | None  # Creation timestamp
    has_replies: bool | None  # Whether message has replies
    id: Required[str]  # Message ID (msg_...)
    idempotency_key: str | None  # Client-provided idempotency key
    legacy_agent: str | None  # Legacy agent if sent by legacy chat agent
    metadata: dict[str, object] | None  # Message metadata
    org: str | None  # Organization
    reactions: list[MessageUpdatedPayloadMessageReactionsItem] | None  # Message reactions
    rendering_mode: str | None  # Rendering mode hint
    replies: list[dict[str, object]] | None  # Inline replies (if loaded)
    replies_after_cursor: str | None  # Cursor for replies pagination
    replies_before_cursor: str | None  # Cursor for replies pagination
    reply_count: int | None  # Number of replies
    reply_to: dict[str, object] | None  # Parent message object (if loaded)
    sandbox: str | None  # Sandbox identifier
    team: str | None  # Team
    thread: str | None  # Parent thread
    user: str | None  # Author user (public ID or expanded object when loaded)


# Broadcast when a message is updated or removed
class MessageUpdatedPayload(TypedDict, total=False):
    message: MessageUpdatedPayloadMessage | None  # API schema for a chat message.
    thread_id: str | None


# Broadcast thread-level events (agent updates, read state, unread counts)
class ThreadEventPayload(TypedDict, total=False):
    payload: dict[str, object] | None
    thread_id: str | None
    type: str | None


# Broadcast system-wide events
class SystemEventPayload(TypedDict, total=False):
    event: dict[str, object] | None


# Channel for real-time chat messaging.
# Supports team-scoped and user-scoped threads with keyed, transient, and direct
# thread access patterns.
class ApiChatChannel:
    def __init__(self, channel, join_response=None):
        self._channel = channel
        self.join_response = join_response

    # Join a team-scoped thread by ID
    @staticmethod
    def topic_team_thread(team_id: str, thread_id: str) -> str:
        return f"api:chat:team:{team_id}:thread:{thread_id}"

    # Join a team-scoped thread by ID
    @classmethod
    async def join_team_thread(
        cls,
        socket: "Socket",
        team_id: str,
        thread_id: str,
        *,
        after_cursor: str | None = None,
        before_cursor: str | None = None,
        include_metadata: bool | None = None,
        limit: int | None = None,
    ) -> "ApiChatChannel":
        topic = cls.topic_team_thread(team_id, thread_id)
        channel = socket.channel(topic)
        payload: dict[str, object] = {}
        if after_cursor is not None:
            payload["after_cursor"] = after_cursor
        if before_cursor is not None:
            payload["before_cursor"] = before_cursor
        if include_metadata is not None:
            payload["include_metadata"] = include_metadata
        if limit is not None:
            payload["limit"] = limit
        join_response = await channel.join(payload)
        return cls(channel, join_response)

    # Join or create a team-scoped keyed thread
    @staticmethod
    def topic_team_keyed(team_id: str, key: str) -> str:
        return f"api:chat:team:{team_id}:key:{key}"

    # Join or create a team-scoped keyed thread
    @classmethod
    async def join_team_keyed(
        cls,
        socket: "Socket",
        team_id: str,
        key: str,
        *,
        after_cursor: str | None = None,
        before_cursor: str | None = None,
        include_metadata: bool | None = None,
        limit: int | None = None,
    ) -> "ApiChatChannel":
        topic = cls.topic_team_keyed(team_id, key)
        channel = socket.channel(topic)
        payload: dict[str, object] = {}
        if after_cursor is not None:
            payload["after_cursor"] = after_cursor
        if before_cursor is not None:
            payload["before_cursor"] = before_cursor
        if include_metadata is not None:
            payload["include_metadata"] = include_metadata
        if limit is not None:
            payload["limit"] = limit
        join_response = await channel.join(payload)
        return cls(channel, join_response)

    # Join a team-scoped transient (ephemeral) thread
    @staticmethod
    def topic_team_transient(team_id: str, key: str) -> str:
        return f"api:chat:team:{team_id}:transient:{key}"

    # Join a team-scoped transient (ephemeral) thread
    @classmethod
    async def join_team_transient(
        cls,
        socket: "Socket",
        team_id: str,
        key: str,
        *,
        after_cursor: str | None = None,
        before_cursor: str | None = None,
        include_metadata: bool | None = None,
        limit: int | None = None,
    ) -> "ApiChatChannel":
        topic = cls.topic_team_transient(team_id, key)
        channel = socket.channel(topic)
        payload: dict[str, object] = {}
        if after_cursor is not None:
            payload["after_cursor"] = after_cursor
        if before_cursor is not None:
            payload["before_cursor"] = before_cursor
        if include_metadata is not None:
            payload["include_metadata"] = include_metadata
        if limit is not None:
            payload["limit"] = limit
        join_response = await channel.join(payload)
        return cls(channel, join_response)

    # Join a user-scoped thread by ID
    @staticmethod
    def topic_user_thread(thread_id: str) -> str:
        return f"api:chat:user:thread:{thread_id}"

    # Join a user-scoped thread by ID
    @classmethod
    async def join_user_thread(
        cls,
        socket: "Socket",
        thread_id: str,
        *,
        after_cursor: str | None = None,
        before_cursor: str | None = None,
        include_metadata: bool | None = None,
        limit: int | None = None,
    ) -> "ApiChatChannel":
        topic = cls.topic_user_thread(thread_id)
        channel = socket.channel(topic)
        payload: dict[str, object] = {}
        if after_cursor is not None:
            payload["after_cursor"] = after_cursor
        if before_cursor is not None:
            payload["before_cursor"] = before_cursor
        if include_metadata is not None:
            payload["include_metadata"] = include_metadata
        if limit is not None:
            payload["limit"] = limit
        join_response = await channel.join(payload)
        return cls(channel, join_response)

    # Join or create a user-scoped keyed thread
    @staticmethod
    def topic_user_keyed(key: str) -> str:
        return f"api:chat:user:key:{key}"

    # Join or create a user-scoped keyed thread
    @classmethod
    async def join_user_keyed(
        cls,
        socket: "Socket",
        key: str,
        *,
        after_cursor: str | None = None,
        before_cursor: str | None = None,
        include_metadata: bool | None = None,
        limit: int | None = None,
    ) -> "ApiChatChannel":
        topic = cls.topic_user_keyed(key)
        channel = socket.channel(topic)
        payload: dict[str, object] = {}
        if after_cursor is not None:
            payload["after_cursor"] = after_cursor
        if before_cursor is not None:
            payload["before_cursor"] = before_cursor
        if include_metadata is not None:
            payload["include_metadata"] = include_metadata
        if limit is not None:
            payload["limit"] = limit
        join_response = await channel.join(payload)
        return cls(channel, join_response)

    # Join a user-scoped transient (ephemeral) thread
    @staticmethod
    def topic_user_transient(key: str) -> str:
        return f"api:chat:user:transient:{key}"

    # Join a user-scoped transient (ephemeral) thread
    @classmethod
    async def join_user_transient(
        cls,
        socket: "Socket",
        key: str,
        *,
        after_cursor: str | None = None,
        before_cursor: str | None = None,
        include_metadata: bool | None = None,
        limit: int | None = None,
    ) -> "ApiChatChannel":
        topic = cls.topic_user_transient(key)
        channel = socket.channel(topic)
        payload: dict[str, object] = {}
        if after_cursor is not None:
            payload["after_cursor"] = after_cursor
        if before_cursor is not None:
            payload["before_cursor"] = before_cursor
        if include_metadata is not None:
            payload["include_metadata"] = include_metadata
        if limit is not None:
            payload["limit"] = limit
        join_response = await channel.join(payload)
        return cls(channel, join_response)

    # Leave the underlying channel.
    async def leave(self):
        await self._channel.leave()

    # Fork a sub-thread from an existing message
    async def api_chat_fork_thread(self, payload: ApiChatForkThreadInput) -> dict[str, object]:
        return await self._channel.push("api:chat:fork_thread", payload)

    # Mark a thread as read up to a given message
    async def api_chat_mark_thread_read(
        self, payload: ApiChatMarkThreadReadInput
    ) -> dict[str, object]:
        return await self._channel.push("api:chat:mark_thread_read", payload)

    # List all messages in the current thread
    async def api_chat_list_messages(self, payload: dict) -> dict[str, object]:
        return await self._channel.push("api:chat:list_messages", payload)

    # Load additional messages with cursor-based pagination
    async def api_chat_load_more_messages(
        self, payload: ApiChatLoadMoreMessagesInput
    ) -> dict[str, object]:
        return await self._channel.push("api:chat:load_more_messages", payload)

    # Post a new message with optional uploads and reply-to
    async def api_chat_post_message(self, payload: ApiChatPostMessageInput) -> dict[str, object]:
        return await self._channel.push("api:chat:post_message", payload)

    # Post a simple text message
    async def api_chat_post_simple_message(
        self, payload: ApiChatPostSimpleMessageInput
    ) -> dict[str, object]:
        return await self._channel.push("api:chat:post_simple_message", payload)

    # Edit an existing message's content
    async def api_chat_edit_message(self, payload: ApiChatEditMessageInput) -> dict[str, object]:
        return await self._channel.push("api:chat:edit_message", payload)

    # Delete a message
    async def api_chat_delete_message(
        self, payload: ApiChatDeleteMessageInput
    ) -> dict[str, object]:
        return await self._channel.push("api:chat:delete_message", payload)

    # Add an emoji reaction to a message
    async def api_chat_add_reaction(self, payload: ApiChatAddReactionInput) -> dict[str, object]:
        return await self._channel.push("api:chat:add_reaction", payload)

    # Remove an emoji reaction from a message
    async def api_chat_remove_reaction(
        self, payload: ApiChatRemoveReactionInput
    ) -> dict[str, object]:
        return await self._channel.push("api:chat:remove_reaction", payload)

    # Broadcast when a new message is added to a thread
    def on_message_added(
        self, callback: Callable[[MessageAddedPayload], None]
    ) -> Callable[[], None]:
        return self._channel.on("message_added", callback)

    # Broadcast when a message is updated or removed
    def on_message_updated(
        self, callback: Callable[[MessageUpdatedPayload], None]
    ) -> Callable[[], None]:
        return self._channel.on("message_updated", callback)

    # Broadcast thread-level events (agent updates, read state, unread counts)
    def on_thread_event(self, callback: Callable[[ThreadEventPayload], None]) -> Callable[[], None]:
        return self._channel.on("thread_event", callback)

    # Broadcast system-wide events
    def on_system_event(self, callback: Callable[[SystemEventPayload], None]) -> Callable[[], None]:
        return self._channel.on("system_event", callback)
